# root endpoint request
displayName: AsyncTasks
description: Administration des Tâches Asynchrones.
type: collection

/{id_async}:
  displayName: AsyncTask
  type: { collection-item-write: { createModel: task_status, exampleModel: !include ../samples/task_status.sample, answearModel: async_status, exampleAnswearModel: !include ../samples/async_status.sample } }
  is: [ standardErrors ]
  patch:

  /result:
    displayName: AsyncTask Result
    description: Permet de récupérer les résultats d'une tâche asynchrone (si elle en a).
    type: base
    is: [ standardErrors ]
    get:
      description: Récupère les résultats.
      responses:
        200:
          body:
            application/json:
              schema: genericObject
              example: !include ../samples/genericSample.sample
