- standardHeaders:
    headers:
      X-RequestId:
        type: string
        description: Identifiant unique de la requête.
        example: AbDUh67jj
      FullApiVersion:
        type:  string
        description: Version complète de l'API.
        example: V2.56
- standardWorkspace:
    responses:
      200?:
        headers:
          X-Folder-Parent:
            description: Chemin du Folder Parent
            type: string
      201?:
        headers:
          X-Folder-Parent:
            description: Chemin du Folder Parent
            type: string

- digestDelete:
    headers:
      X-DigestValue:
        type: string
        description: Digest of the object to delete
        required: true
      X-DigestAlgo:
        type: string
        description: Algorithm used by the digest among MD5, SHA-256, SHA-512
        required: true
- strategyStorage:
    headers:
      X-Strategy-Id:
        description: Identifiant de la Stratégie pour Offres de stockage et Copies (conservation)
        type: string
        required: true

- x-get:
    headers:
      X-HTTP-Method-Override:
        description: doit être GET
        required: true
        type: string
        enum: ["GET"]
- x-put:
    headers:
      X-HTTP-Method-Override:
        description: doit être PUT
        required: true
        type: string
        enum: ["PUT"]
- x-patch:
    headers:
      X-HTTP-Method-Override:
        description: doit être PATCH
        required: true
        type: string
        enum: ["PATCH"]
- x-delete:
    headers:
      X-HTTP-Method-Override:
        description: doit être DELETE
        required: true
        type: string
        enum: ["DELETE"]
- allows:
    headers:
      Accept:
        description: Permet de spécifier si un résultat doit contenir uniquement des métadonnées ('_application/json_'), un DIP complet (un ZIP contenant les métadonnées et les objets) ou seulement des _Objects_ avec un contenu binaire ('_application/octet-stream_').
        type: string
        enum: [ "application/json", "application/zip", "application/octet-stream" ]
- standardErrors:
    responses:
      401:
        description: Unauthorized
        headers:
          X-RequestId:
            type: string
            description: Identifiant unique de la requête.
            example: AbDUh67jj
          FullApiVersion:
            type:  string
            description: Version complète de l'API.
            example: V2.56
        body:
          application/json:
            schema: error
            example: !include ../samples/error-401.sample
      404:
        description: Not Found
        headers:
          X-RequestId:
            type: string
            description: Identifiant unique de la requête.
            example: AbDUh67jj
          FullApiVersion:
            type:  string
            description: Version complète de l'API.
            example: V2.56
        body:
          application/json:
            schema: error
            example: !include ../samples/error-404.sample
      412:
        description: Precondition Failed
        headers:
          X-RequestId:
            type: string
            description: Identifiant unique de la requête.
            example: AbDUh67jj
          FullApiVersion:
            type:  string
            description: Version complète de l'API.
            example: V2.56
        body:
          application/json:
            schema: error
            example: !include ../samples/error-412.sample
- conflict:
    responses:
      409:
        description: Conflict
        headers:
          X-RequestId:
            type: string
            description: Identifiant unique de la requête.
            example: AbDUh67jj
          FullApiVersion:
            type:  string
            description: Version complète de l'API.
            example: V2.56
        body:
          application/json:
            schema: error
            example: !include ../samples/error-409.sample
- unsupportedMediaType:
    responses:
      415:
        description: Unsupported Media Type
        headers:
          X-RequestId:
            type: string
            description: Identifiant unique de la requête.
            example: AbDUh67jj
          FullApiVersion:
            type:  string
            description: Version complète de l'API.
            example: V2.56
        body:
          application/json:
            schema: error
            example: !include ../samples/error-415.sample

- storageHeaders:
    headers:
      X-Tenant-Id:
        type: string
        description: Identifiant unique du tenant.
        required: true
        example: tenantId1
