# root endpoint request
displayName: Ingests
description: API de versement (Ingest). Ce point d'entrée permet de chercher ou de créer une transaction de versement. Une transaction de versement est volatile, c'est à dire qu'elle disparaîtra dès qu'elle sera terminée.
type: { collection-write: { createModel: genericObject, exampleModel: !include ../samples/genericSample.sample, answearModel: genericObject, exampleAnswearModel: !include ../samples/genericSample.sample } }
is: [ standardErrors ]
post:
  description: |
    Crée une transaction de versement :
    - une requête unique, avec un 'body' contenant toutes les informations (Métadonnées dans un foirmat SEDA XML ou Json ainsi que tous les binaires) probablement dans un ZIP

/{id_async}:
  displayName: Ingest
  description: Accès à une transaction de versement.
  type: { collection-item-write: { createModel: task_status, exampleModel: !include ../samples/task_status.sample, answearModel: async_status, exampleAnswearModel: !include ../samples/async_status.sample } }
  is: [ standardErrors ]
  get:
    description: Comme dans /async_tasks/{id_ingest}, retourne le statut courant de cette transaction de versement.
