# Configuration
@access-contract = ContratTNR
@tenant = 0

### Recherche d'une unitée archivistique dont le titre correspond à 'héritag' sur le tenant 0 et avec le contract d'accès 'ContratTNR'
GET {{url-access}}/access-external/v1/units/
Accept: application/json
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}

{
  "$roots": [],
  "$query": [
    {
      "$match": {
              "Title": "héritag"
      }
    }
  ],
  "$filter": {
    "$offset": 0,
    "$limit": 100
  },
  "$projection": {}
}

### Recherche d'une unitée archivistique dont la description inclu 'Proin bibendum odio quam, in placerat dui congue nec'
GET {{url-access}}/access-external/v1/units/
Accept: application/json
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}

{
  "$roots": [],
  "$query": [
    {
      "$match": {
        "Description": "Proin bibendum odio quam, in placerat dui congue nec"
      }
    }
  ],
  "$filter": {
    "$offset": 0,
    "$limit": 100
  },
  "$projection": {}
}

### Recherche d'une unitée archivistique dont la description contient 'RATP' **ET** dont le titre n'est pas 'Eglise de Pantin'
GET {{url-access}}/access-external/v1/units/
Accept: application/json
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}

{
  "$roots": [],
  "$query": [
    {
      "$and": [
        {
          "$match": {
            "Description": "RATP"
          }
        },
        {
          "$not": [
            {
              "$eq": {
                "Title": "Eglise de Pantin"
              }
            }
          ]
        }
      ]
    }
  ],
  "$filter": {
    "$offset": 0,
    "$limit": 100
  },
  "$projection": {
    "$fields": {}
  }
}

### Recherche d'une unitée archivistique qui possède un object group **ET** dont la description contient 'RATP'
GET {{url-access}}/access-external/v1/units/
Accept: application/json
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}

{
  "$roots": [],
  "$query": [
    {
      "$and": [
        {
          "$match": {
            "Description": "RATP"
          }
        },
        {
          "$exists": "#object"
        }
      ]
    }
  ],
  "$filter": {
    "$offset": 0,
    "$limit": 100
  },
  "$projection": {
    "$fields": {}
  }
}

### Recherche d'une unitée archivistique dont la description contiens 'SNCF' **OU** dont la description contient 'RATP'
GET {{url-access}}/access-external/v1/units/
Accept: application/json
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}

{
  "$roots": [],
  "$query": [
    {
      "$or": [
        {
          "$match": {
            "Description": "RATP"
          }
        },
        {
          "$match": {
            "Description": "SNCF"
          }
        }
      ]
    }
  ],
  "$filter": {
    "$offset": 0,
    "$limit": 100
  },
  "$projection": {
    "$fields": {}
  }
}

### Recherche d'une unitée archivistique fille directe de 'aeaqaaaaaahgynv2aanysaln2jvxewiaaaba' et dont le titre correspond à 'pantin'
GET {{url-access}}/access-external/v1/units/
Accept: application/json
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}

{
  "$roots": [
    "aeaqaaaaaahgynv2aanysaln2jvxewiaaaba"
  ],
  "$query": [
    {
      "$match": {
        "Title": "pantin"
      },
      "$depth": 1
    }
  ],
  "$filter": {
    "$offset": 0,
    "$limit": 100
  },
  "$projection": {}
}
