---

- name: Remove former elasticsearch-curator package
  package:
    name: elasticsearch-curator
    state: absent
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"

- name: Install vitam-elasticsearch-curator package
  package:
    name: vitam-elasticsearch-curator
    state: latest
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"

- name: Ensure curator directories exist
  file:
    path: "{{ item }}"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    state: directory
    mode: "{{ vitam_defaults.folder.folder_permission }}"
  with_items:
    - "{{ curator_conf_dir }}"
    - "{{ curator_conf_dir }}/curator.d"
    - "{{ curator_log_dir }}"
    - "{{ curator_script_dir }}"

- name: Apply curator configuration
  template:
    src: curator.yml.j2
    dest: "{{ curator_conf_dir }}/curator.yml"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"

- name: Copy curator script
  template:
    src: run_curator.sh.j2
    dest: "{{ curator_script_dir }}/run_curator.sh"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.script_permission }}"

- name: Find existing deployed configurations
  find:
    paths: "{{ curator_conf_dir }}/curator.d/"
    patterns: '*'
  register: existing_configurations

- block:

    - name: Define expected configurations
      set_fact:
        expected_configurations: "{{ expected_configurations | default([]) + [ curator_conf_dir + '/curator.d/' + item.0 + '_index_' + item.1 + '.yml' ] }}"
      loop: "{{ action | product(index_name) | list }}"

    - name: Delete unused configurations
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ existing_configurations.files }}"
      when: item.path not in expected_configurations

    - name: Copy close and delete configuration files for logstash indices
      template:
        src: "{{ item[0] }}_index.yml.j2"
        dest: "{{ curator_conf_dir }}/curator.d/{{ item[0] }}_index_{{ item[1] }}.yml"
        owner: "{{ vitam_defaults.users.vitam }}"
        group: "{{ vitam_defaults.users.group }}"
        mode: "{{ vitam_defaults.folder.conf_permission }}"
      loop: "{{ action | product(index_name) | list }}"

    - name: Copy close and delete systemd unit and timer for curator
      template:
        src: systemd/vitam-curator-old-indexes.{{ item[1] }}.j2
        dest: "{{ '/lib/systemd/system' if ansible_os_family == 'Debian' else '/usr/lib/systemd/system' }}/vitam-curator-{{ item[0] }}-old-indexes.{{ item[1] }}"
        mode: '0644'
      loop: "{{ action | product(systemd) | list }}"

    - name: Enable systemd timers
      systemd:
        name: "vitam-curator-{{ item }}-old-indexes.timer"
        daemon_reload: true
        enabled: "{{ curator.at_boot | default(service_at_boot) }}"
        state: started
      loop: "{{ action }}"

  vars:
    action: ['close', 'delete']
    index_name: "{{ curator.indices }}"
    systemd: ['service', 'timer']
