import { Component, OnInit } from '@angular/core';

const data1 = {
  'httpCode': 200,
  '$hits': {
    'total': 1,
    'offset': 0,
    'limit': 10000,
    'size': 1
  },
  '$results': [{
    '_id': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
    'evId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
    'evType': 'PROCESS_SIP_UNITARY',
    'evDateTime': '2017-09-05T02:12:41.401',
    'evDetData': '{\n  "EvDetailReq" : "Matrice cadastrale num\\u00E9rique.",\n  "ArchivalAgreement" : "ArchivalAgreementWithProfil",\n  "ArchivalProfile" : "PROFIL-TNR"\n}',
    'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
    'evTypeProc': 'INGEST',
    'outcome': 'STARTED',
    'outDetail': 'PROCESS_SIP_UNITARY.STARTED',
    'outMessg': 'Début du processus d\'entrée du SIP : aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
    'agId': '{"Name":"vitam-iaas-app-01","Role":"ingest-external","ServerId":539449684,"SiteId":1,"GlobalPlatformId":136796500}',
    'agIdApp': null,
    'agIdAppSession': null,
    'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
    'agIdSubm': null,
    'agIdOrig': 'DGFIP',
    'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
    'obIdReq': null,
    'obIdIn': 'Matrice cadastrale numérique.',
    'events': [{
      'evId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evType': 'STP_UPLOAD_SIP',
      'evDateTime': '2017-09-05T02:12:40.496',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'STARTED',
      'outDetail': 'PROCESS_SIP_UNITARY.STARTED',
      'outMessg': 'Début du processus de réception du SIP',
      'agId': '{"Name":"vitam-iaas-app-02","Role":"ingest-internal","ServerId":2116443750,"SiteId":1,"GlobalPlatformId":237395558}',
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evType': 'STP_UPLOAD_SIP',
      'evDateTime': '2017-09-05T02:12:40.594',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'OK',
      'outDetail': 'PROCESS_SIP_UNITARY.OK',
      'outMessg': 'Succès du processus de réception du SIP',
      'agId': '{"Name":"vitam-iaas-app-02","Role":"ingest-internal","ServerId":2116443750,"SiteId":1,"GlobalPlatformId":237395558}',
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2rpaaaaaq',
      'evType': 'STP_INGEST_CONTROL_SIP',
      'evDateTime': '2017-09-05T02:12:42.817',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'STARTED',
      'outDetail': 'STP_INGEST_CONTROL_SIP.STARTED',
      'outMessg': 'Début du processus du contrôle du bordereau',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2snaaaaaq',
      'evType': 'CHECK_SEDA',
      'evDateTime': '2017-09-05T02:12:42.932',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'STARTED',
      'outDetail': 'CHECK_SEDA.STARTED',
      'outMessg': 'Début de la vérification globale du SIP',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2snaaaaba',
      'evType': 'CHECK_SEDA',
      'evDateTime': '2017-09-05T02:12:42.932',
      'evDetData': '{}',
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'OK',
      'outDetail': 'CHECK_SEDA.OK',
      'outMessg': 'Succès de la vérification globale du SIP Detail=  OK:1',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'agIdApp': null,
      'agIdAppSession': null,
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'agIdSubm': null,
      'agIdOrig': null,
      'obId': null,
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2snaaaabq',
      'evType': 'CHECK_HEADER',
      'evDateTime': '2017-09-05T02:12:42.932',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'STARTED',
      'outDetail': 'CHECK_HEADER.STARTED',
      'outMessg': 'Début de la vérification générale du bordereau',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'agIdApp': null,
      'agIdAppSession': null,
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'agIdSubm': null,
      'agIdOrig': null,
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2snaaaaca',
      'evType': 'CHECK_HEADER.CHECK_CONTRACT_INGEST',
      'evDateTime': '2017-09-05T02:12:42.932',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'STARTED',
      'outDetail': 'CHECK_HEADER.CHECK_CONTRACT_INGEST.STARTED',
      'outMessg': 'Début de la vérification et du contrôle',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'agIdApp': null,
      'agIdAppSession': null,
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'agIdSubm': null,
      'agIdOrig': null,
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2snaaaacq',
      'evType': 'CHECK_HEADER.CHECK_CONTRACT_INGEST',
      'evDateTime': '2017-09-05T02:12:42.932',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'KO',
      'outDetail': 'CHECK_HEADER.CHECK_CONTRACT_INGEST.KO',
      'outMessg': 'Échec de la vérification de la présence et contrôle du contrat d\'entrée Detail=  KO:1',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'agIdApp': null,
      'agIdAppSession': null,
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'agIdSubm': null,
      'agIdOrig': null,
      'obId': null,
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2snaaaada',
      'evType': 'CHECK_HEADER',
      'evDateTime': '2017-09-05T02:12:42.932',
      'evDetData': '{"EvDetailReq":"Matrice cadastrale num\\u00E9rique.","ArchivalAgreement":"ArchivalAgreementWithProfil","ArchivalProfile":"PROFIL-TNR"}',
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'KO',
      'outDetail': 'CHECK_HEADER.KO',
      'outMessg': 'Échec de la vérification générale du bordereau Detail=  KO:1',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'agIdApp': null,
      'agIdAppSession': null,
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'agIdSubm': null,
      'agIdOrig': null,
      'obId': null,
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2sniaaaaq',
      'evType': 'STP_INGEST_CONTROL_SIP',
      'evDateTime': '2017-09-05T02:12:42.933',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'KO',
      'outDetail': 'STP_INGEST_CONTROL_SIP.KO',
      'outMessg': 'Échec du processus du contrôle du bordereau',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'agIdApp': null,
      'agIdAppSession': null,
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'agIdSubm': null,
      'agIdOrig': null,
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': '20161012002'
    },{
      'evId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evType': 'STP_TEST',
      'evDateTime': '2017-09-05T02:12:43.496',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'STARTED',
      'outDetail': 'PROCESS_SIP_TEST.STARTED',
      'outMessg': 'Début du processus test',
      'agId': '{"Name":"vitam-iaas-app-02","Role":"ingest-internal","ServerId":2116443750,"SiteId":1,"GlobalPlatformId":237395558}',
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2snaaaaaq',
      'evType': 'CHECK_SEDA_TEST',
      'evDateTime': '2017-09-05T02:12:42.932',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'STARTED',
      'outDetail': 'CHECK_SEDA_TEST.STARTED',
      'outMessg': 'Début de la vérification globale du SIP',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2snaaaaba',
      'evType': 'CHECK_SEDA_TEST',
      'evDateTime': '2017-09-05T02:12:42.932',
      'evDetData': '{}',
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'OK',
      'outDetail': 'CHECK_SEDA_TEST.OK',
      'outMessg': 'Succès de la vérification globale du SIP Detail=  OK:1',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'agIdApp': null,
      'agIdAppSession': null,
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'agIdSubm': null,
      'agIdOrig': null,
      'obId': null,
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2snaaaabq',
      'evType': 'CHECK_HEADER_TEST',
      'evDateTime': '2017-09-05T02:12:42.932',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'STARTED',
      'outDetail': 'CHECK_HEADER_TEST.STARTED',
      'outMessg': 'Début de la vérification générale du bordereau',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'agIdApp': null,
      'agIdAppSession': null,
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'agIdSubm': null,
      'agIdOrig': null,
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2snaaaaca',
      'evType': 'CHECK_HEADER_TEST.CHECK_CONTRACT_INGEST',
      'evDateTime': '2017-09-05T02:12:42.932',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'STARTED',
      'outDetail': 'CHECK_HEADER_TEST.CHECK_CONTRACT_INGEST.STARTED',
      'outMessg': 'Début de la vérification et du contrôle',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'agIdApp': null,
      'agIdAppSession': null,
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'agIdSubm': null,
      'agIdOrig': null,
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2snaaaacq',
      'evType': 'CHECK_HEADER_TEST.CHECK_CONTRACT_INGEST',
      'evDateTime': '2017-09-05T02:12:42.932',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'Warning',
      'outDetail': 'CHECK_HEADER_TEST.CHECK_CONTRACT_INGEST.KO',
      'outMessg': 'Échec de la vérification de la présence et contrôle du contrat d\'entrée Detail=  KO:1',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'agIdApp': null,
      'agIdAppSession': null,
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'agIdSubm': null,
      'agIdOrig': null,
      'obId': null,
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacfxutczaarkwak6j7h2snaaaada',
      'evType': 'CHECK_HEADER_TEST',
      'evDateTime': '2017-09-05T02:12:42.932',
      'evDetData': '{"EvDetailReq":"Matrice cadastrale num\\u00E9rique.","ArchivalAgreement":"ArchivalAgreementWithProfil","ArchivalProfile":"PROFIL-TNR"}',
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'Warning',
      'outDetail': 'CHECK_HEADER_TEST.KO',
      'outMessg': 'Échec de la vérification générale du bordereau Detail=  KO:1',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'agIdApp': null,
      'agIdAppSession': null,
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'agIdSubm': null,
      'agIdOrig': null,
      'obId': null,
      'obIdReq': null,
      'obIdIn': null
    },{
      'evId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evType': 'STP_TEST',
      'evDateTime': '2017-09-05T02:12:43.594',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'Warning',
      'outDetail': 'PROCESS_SIP_TEST.OK',
      'outMessg': 'Fin du processus test',
      'agId': '{"Name":"vitam-iaas-app-02","Role":"ingest-internal","ServerId":2116443750,"SiteId":1,"GlobalPlatformId":237395558}',
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': null
    }, {
      'evId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evType': 'PROCESS_SIP_UNITARY',
      'evDateTime': '2017-09-05T02:12:43.532',
      'evDetData': null,
      'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'evTypeProc': 'INGEST',
      'outcome': 'KO',
      'outDetail': 'PROCESS_SIP_UNITARY.KO',
      'outMessg': 'Entrée en Échec',
      'agId': '{"Name":"vitam-iaas-app-03","Role":"processing","ServerId":1668959321,"SiteId":1,"GlobalPlatformId":192564313}',
      'evIdReq': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obId': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq',
      'obIdReq': null,
      'obIdIn': null
    }],
    '_v': 0,
    '_tenant': 0
  }],
  '$context': {
    '$query': {
      '$and': [{
        '$eq': {
          'evIdProc': 'aedqaaaaacecowkuaawjmak6j7h2gnaaaaaq'
        }
      }]
    },
    '$filter': {
      '$limit': 10000
    },
    '$projection': {}
  }
};

@Component({
  selector: 'vitam-logbook-operation-details',
  templateUrl: './logbook-operation-details.component.html',
  styleUrls: ['./logbook-operation-details.component.css']
})
export class LogbookOperationDetailsComponent implements OnInit {
  public response: any;

  constructor() { }

  ngOnInit() {
    this.response = data1;
  }

}
