---

#### Grafana installation ####

- name: "Install {{ grafana_package }} package"
  package:
    name: "{{ grafana_package }}"
    state: present
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"
  notify: "grafana - restart service"
  when: install_mode != "container"

- name: Create grafana group
  group:
    name: "{{ grafana_group }}"
    state: present

- name: Create grafana user
  user:
    name: "{{ grafana_user }}"
    state: present
    groups: "{{ grafana_group }}"

- name: Ensure grafana directories are present
  file:
    path: "{{ vitam_defaults.folder.root_path }}/{{ item }}/grafana/"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "{{ '0777' if install_mode == 'container' else vitam_defaults.folder.folder_permission }}"
  loop:
    - conf
    - data
    - log
  notify: "grafana - restart {{ 'docker' if install_mode == 'container' else 'service' }}"

- name: Ensure grafana provisioning sub directory is present
  file:
    path: "{{ grafana_path_provisioning }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "{{ '0777' if install_mode == 'container' else vitam_defaults.folder.folder_permission }}"
  notify: "grafana - restart {{ 'docker' if install_mode == 'container' else 'service' }}"

- name: Ensure grafana provisioning sub directories are present
  file:
    path: "{{ grafana_path_provisioning }}/{{ item }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "{{ '0777' if install_mode == 'container' else vitam_defaults.folder.folder_permission }}"
  loop:
    - datasources
    - dashboards
    - plugins
    - alerting
  notify: "grafana - restart {{ 'docker' if install_mode == 'container' else 'service' }}"

# When upgrade the Grafana version, get the corresponding grafana.ini file and replace templates/grafana.ini.j2 with corresponding changes
- name: Apply grafana custom configuration
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_conf_dir if install_mode == 'container' else '/etc/grafana' }}/grafana.ini"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "{{ '0666' if install_mode == 'container' else vitam_defaults.folder.conf_permission }}"
  tags: update_grafana_configuration
  notify: "grafana - restart {{ 'docker' if install_mode == 'container' else 'service' }}"

- block:

  - name: Pull Docker image
    docker_image:
      name: "{{ container_repository.registry_url }}/vitam-external/grafana/grafana:{{ grafana_version }}"
      state: present
    ignore_errors: true

  - name: Start Docker container
    docker_container:
      name: grafana-server
      image: "{{ container_repository.registry_url }}/vitam-external/grafana/grafana:{{ grafana_version }}"
      state: started
      restart_policy: always
      volumes:
        - "{{ grafana_conf_dir }}:{{ grafana_conf_dir }}:rw"
        - "{{ grafana_path_provisioning }}:{{ grafana_path_provisioning }}:rw"
        - "{{ grafana_data_dir }}:{{ grafana_data_dir }}:rw"
        - "{{ grafana_log_dir }}:{{ grafana_log_dir }}:rw"
      network_mode: host
      env:
        GF_PATHS_CONFIG: "/vitam/conf/grafana/grafana.ini"
        GF_PATHS_DATA: "{{ grafana_data_dir }}"
        GF_PATHS_PROVISIONING: "{{ grafana_path_provisioning }}"
        GF_PATHS_PLUGINS: "{{ grafana_path_plugins }}"
        GF_PATHS_LOGS: "{{ grafana_log_dir }}"
      user: "{{ grafana_user }}"

  when: install_mode == "container"

- meta: flush_handlers

- name: Make sure grafana-server is started and enabled at boot
  systemd:
    name: grafana-server
    enabled: "{{ grafana.at_boot | default(service_at_boot) }}"
    state: started
  when: install_mode != "container"

#### Consul configuration ####

- name: Ensure consul config dir is OK
  file:
    path: "{{ consul_folder_conf }}"
    state: directory
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ '0777' if install_mode == 'container' else vitam_defaults.folder.folder_permission }}"

- name: Deploy consul agent service declaration
  template:
    src: service-grafana.json.j2
    dest: "{{ consul_folder_conf }}/service-grafana.json"
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ '0644' if install_mode == 'container' else vitam_defaults.folder.conf_permission }}"
  tags:
    - consul_conf
    - update_grafana_configuration
  notify:
    - "grafana - restart {{ 'docker' if install_mode == 'container' else 'service' }}"

- name: "Wait for grafana-server port {{ grafana.http_port | default(3000) }} to be open"
  wait_for:
    host: "{{ ip_admin }}"
    port: "{{ grafana.http_port | default(3000) }}"
    state: started
    timeout: "{{ vitam_defaults.services.start_timeout | default(300) }}"
