---

- name: Cleanup plugins directory
  file:
    path: "{{ grafana_path_plugins }}"
    state: absent

- name: Create plugins directory
  file:
    path: "{{ grafana_path_plugins }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "{{ '0777' if install_mode == 'container' else vitam_defaults.folder.folder_permission }}"

- name: Install unzip package
  package:
    name: unzip
    state: present
  register: result
  retries: "{{ packages_install_retries_number | default(1) }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay | default(10) }}"

- name: Install plugins
  unarchive:
    src: "{{ item }}"
    dest: "{{ grafana_path_plugins }}"
  with_fileglob:
    - "{{ role_path }}/files/plugins/*.zip"
  notify: "grafana - restart {{ 'docker' if install_mode == 'container' else 'service' }}"
