---

- hosts: hosts_kibana_data
  any_errors_fatal: true
  roles:
    - vitam
    - kibana
    - kibana_dashboards
  vars:
    composant: "{{ kibana.data }}"
    elasticsearch_host: "{{ vitam.elastic_kibana_interceptor.host }}"
    elasticsearch_port: "{{ vitam.elastic_kibana_interceptor.port_service }}"
    vitam_struct: "{{ vitam.elastic_kibana_interceptor }}"
  tags: kibana_data
