---

# mongodb commons (yum install, etc...)
- hosts: hosts_mongodb_data
  any_errors_fatal: true
  roles:
    - mongo_common

# Mongoc replicas configuration
- hosts: hosts_mongoc_data
  gather_facts: false
  any_errors_fatal: true
  roles:
    - mongoc
  vars:
    mongod: hosts_mongod_data
    group_name: hosts_mongoc_data

# Mongod replicas configuration
- hosts: hosts_mongod_data
  gather_facts: false
  any_errors_fatal: true
  roles:
    - mongod
  vars:
    mongoc: hosts_mongoc_data
    group_name: hosts_mongod_data

# Mongos configuration
- hosts: hosts_mongos_data
  gather_facts: false
  any_errors_fatal: true
  roles:
    - mongos
    - mongo_configure
  vars:
    group_name: hosts_mongod_data
    mongoc: hosts_mongoc_data
    mongod: hosts_mongod_data
    mongos: hosts_mongos_data
