org.quartz.scheduler.instanceName=VitamScheduler

org.quartz.scheduler.instanceId=2
org.quartz.scheduler.interruptJobsOnShutdown=true

org.quartz.threadPool.class=fr.gouv.vitam.scheduler.server.util.VitamQuartzExecutorThreadPool
org.quartz.threadPool.threadCount=10

org.quartz.jobStore.isClustered=true
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
org.quartz.jobStore.dataSource=postgresDS

org.quartz.dataSource.postgresDS.driver=org.postgresql.Driver
org.quartz.dataSource.postgresDS.provider=hikaricp
org.quartz.dataSource.postgresDS.URL = jdbc:postgresql://localhost:5432/scheduler
org.quartz.dataSource.postgresDS.user=scheduler
org.quartz.dataSource.postgresDS.password=azerty4
org.quartz.dataSource.postgresDS.maxConnections=10