### Configuration
@transaction-id = aeeaaaaaagfuviy5abdwcame2lioz4iaaaaq
@project-id = aeaaaaaaaafuviy5abdwcame2lhwlniaaaaq
@unit-id = aeeaaaaaachbhdsaaa2zaal7jikmv4aaaaaq
@tenant = 1

### Création d'un nouveau projet
POST {{url-collect}}/collect-external/v1/projects
accept: application/json
content-type: application/json
X-Tenant-Id: {{tenant}}

{
  "ArchivalAgencyIdentifier": "Identifier0",
  "TransferringAgencyIdentifier": "Identifier3",
  "OriginatingAgencyIdentifier": "FRAN_NP_009915",
  "SubmissionAgencyIdentifier": "FRAN_NP_005061",
  "MessageIdentifier": "20220302-000005",
  "Name": "This is my Name",
  "LegalStatus": "Archives privées",
  "AcquisitionInformation": "Versement",
  "ArchivalAgreement":"IC-000001",
  "Comment": "Versement du service producteur : Cabinet de Michel Mercier",
  "UnitUp": "aeaqaaaaaahgnz5dabg42amava5kfoqaaaba"
}

### Mise à jour d'un projet
PUT {{url-collect}}/collect-external/v1/projects
accept: application/json
content-type: application/json
X-Tenant-Id: {{tenant}}

{
  "#id": "{{project-id}}",
  "Name": "Versement premier archive",
  "ArchivalAgencyIdentifier": "Identifier0",
  "TransferringAgencyIdentifier": "Identifier3",
  "OriginatingAgencyIdentifier": "FRAN_NP_009915",
  "SubmissionAgencyIdentifier": "FRAN_NP_005061",
  "MessageIdentifier": "20220302-000006",
  "ArchivalAgreement":"IC-000001",
  "Comment": "Versement du service producteur : Cabinet de Michel Mercier",
  "UnitUp": "aeaqaaaaaahgnz5dabg42amava5kfoqaaaba"
}

### Récuperation de tout les projets associé au tenant
GET {{url-collect}}/collect-external/v1/projects
accept: application/json
X-Tenant-Id: {{tenant}}



### Recherche d'un project par criteria
GET {{url-collect}}/collect-external/v1/projects
accept: application/json
content-type: application/json
X-Tenant-Id: {{tenant}}
Content-Length: 143

{
    "$query":"Versement"
}

### Récuperation d'un projet par id
GET {{url-collect}}/collect-external/v1/projects/{{project-id}}
accept: application/json
content-type: application/json
X-Tenant-Id: {{tenant}}

### Récuperation d'une unité archivistique pas dsl query
GET {{url-collect}}/collect-external/v1/transactions/{{transaction-id}}/units
accept: application/json
content-type: application/json
X-Tenant-Id: {{tenant}}
Content-Length: 143

{
    "$roots": [],
    "$query": [
        {
          "$match": {
            "Title": "Saint"
          }
        }
    ],
    "$filter": {
        "$offset": 0,
        "$limit": 100
    },
    "$projection": {}
}

### Recherche d'unités archivistique par projectId et dsl query
GET {{url-collect}}/collect-external/v1/projects/{{project-id}}/units
accept: application/json
content-type: application/json
X-Tenant-Id: {{tenant}}
Content-Length: 143

{
    "$roots": [],
    "$query": [
        {
            "$match": {
                "Title": "Saint"
            }
        }
    ],
    "$filter": {},
    "$projection": {}
}


### upload zip avec arborescence a traiter
POST {{url-collect}}/collect-external/v1/projects/{{project-id}}/binary
Accept: application/json
Content-Type: application/zip
X-Tenant-Id: {{tenant}}

< /path_tozip/stream.zip



### Mise à jour des metadonnées par un fichier csv
PUT {{url-collect}}/collect-external/v1/transactions/{{transaction-id}}/units
Accept: application/json
Content-Type: application/octet-stream
X-Tenant-Id: {{tenant}}

< /path_tometadata/metadata.csv



### Création d'une nouvelle transaction
POST  {{url-collect}}/collect-external/v1/projects/{{project-id}}/transactions
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}

{
  "Name": "Versement des objets binaires",
  "ArchivalAgreement": "IC-000001",
  "MessageIdentifier": "Transaction de test",
  "ArchivalAgencyIdentifier": "ArchivalAgencyIdentifier5",
  "TransferringAgencyIdentifier": "TransferingAgencyIdentifier5",
  "OriginatingAgencyIdentifier": "FRAN_NP_009913",
  "SubmissionAgencyIdentifier": "FRAN_NP_005761",
  "ArchiveProfile": "ArchiveProfile5",
  "Comment": "Commentaires"
}

### Récupérer une transaction
GET  {{url-collect}}/collect-external/v1/transactions/{{transaction-id}}
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}

{
}

### maj d'une transaction
PUT  {{url-collect}}/collect-external/v1/transactions
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}

{
  "#id": "aeeaaaaaagfuviy5abdwcame2lioz4iaaaaq",
  "Name": "Versement des objets binaires",
  "ArchivalAgreement": "IC-000001",
  "MessageIdentifier": "Transaction de test",
  "ArchivalAgencyIdentifier": "ArchivalAgencyIdentifier5",
  "TransferringAgencyIdentifier": "TransferingAgencyIdentifier5",
  "OriginatingAgencyIdentifier": "FRAN_NP_009913",
  "SubmissionAgencyIdentifier": "FRAN_NP_005761",
  "ArchiveProfile": "ArchiveProfile5",
  "Comment": "Commentaires"
}

### Création et rattachement d'une nouvelle unité archivistique à la transaction
POST  {{url-collect}}/collect-external/v1/transactions/{{transaction-id}}/units
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}

{
  "DescriptionLevel": "Item",
  "Title": "My title3",
  "Description": "Allemant. - Au chemin des Dames : le chateau et la ferme de la Motte totalement detruits.",
  "Descriptions": {
    "fr": "La legendes traduites en anglais."
  },
  "Status": "Pret",
  "Tag": ["Grande Collecte"],
  "Source": "Famille Herve, CP1",
  "CreatedDate": "2014-06-12T09:31:00",
  "TransactedDate": "2014-06-12T09:31:00",
  "#management": {
  }
}

### Création et rattachement d'un usage(BinaryMaster)/version(1) à l'unité archivistique
POST  {{url-collect}}/collect-external/v1/units/{{unit-id}}/objects/BinaryMaster/1
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}

{
  "fileInfo": {
    "filename": "binaire_test.txt"
  }
}

### Rattachement d'un binaire à un usage(BinaryMaster)/version(1)
POST  {{url-collect}}/collect-external/v1/units/{{unit-id}}/objects/BinaryMaster/1/binary
Accept: application/json
Content-Type: application/octet-stream
X-Tenant-Id: {{tenant}}

< /path_tobinary/binaire_test.txt

### Possibilité de création et rattachement d'une version 2 à un usage existant --> vérifier la prise en compte d'un tel scénario dans VITAM
POST  {{url-collect}}/collect-external/v1/units/{{unit-id}}/objects/BinaryMaster/2
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}

{
  "fileInfo": {
    "filename": "binary_version_2.txt"
  }
}

### Rattachement d'un binaire à l'usage(BinaryMaster)/version(2)
POST  {{url-collect}}/collect-external/v1/units/{{unit-id}}/objects/BinaryMaster/2/binary
Accept: application/json
Content-Type: application/octet-stream
X-Tenant-Id: {{tenant}}

< /path_tobinary/binary_version_2.txt

### Fermeture de la transaction
POST  {{url-collect}}/collect-external/v1/transactions/{{transaction-id}}/close
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}


{}

### Génération et envoi du SIP vers VITAM
POST  {{url-collect}}/collect-external/v1/transactions/{{transaction-id}}/send
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}

{}


###

OPTIONS {{url-collect}}/collect-external/v1
X-Tenant-Id: {{tenant}}
