### Configuration
@tenant = 1

### Create a new project
# @name project
POST {{url-collect}}/collect-external/v1/projects
accept: application/json
content-type: application/json
X-Tenant-Id: {{tenant}}

{ "ArchivalAgencyIdentifier": "Identifier0", "TransferringAgencyIdentifier": "Identifier3", "OriginatingAgencyIdentifier": "FRAN_NP_009915", "SubmissionAgencyIdentifier": "FRAN_NP_005061", "MessageIdentifier": "20220302-000005", "Name": "This is my Name", "LegalStatus": "Private Archive", "AcquisitionInformation": "Versement", "ArchivalAgreement": "IC-000001", "Comment": "Versement du service producteur : Cabinet de Michel Mercier", "UnitUp": "aeaqaaaaaahgnz5dabg42amava5kfoqaaaba", "TransformationRules": "{ \n \"Title\": .Title + \" - TRANSFORMED\", // Add suffix to Title field \n \"MyStatus\": [\"Verified\"], // Adds a new field \n *: . // Copies all fields from the input JSON \n }" }

###
@project-id = {{ project.response.body.$.$results.0.#id }}

### Create a new transaction
# @name tx
POST  {{url-collect}}/collect-external/v1/projects/{{project-id}}/transactions
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}

{ "Name": "Versement des objets binaires", "ArchivalAgreement": "IC-000001", "MessageIdentifier": "Transaction de test", "ArchivalAgencyIdentifier": "ArchivalAgencyIdentifier5", "TransferringAgencyIdentifier": "TransferingAgencyIdentifier5", "OriginatingAgencyIdentifier": "FRAN_NP_009913", "SubmissionAgencyIdentifier": "FRAN_NP_005761", "ArchiveProfile": "ArchiveProfile5", "Comment": "Commentaires" }

###
@transaction-id = {{ tx.response.body.$.$results.0.#id }}

### Upload SIP to transaction
POST {{url-collect}}/collect-external/v1/transactions/{{transaction-id}}/uploadSip
Content-Type: application/octet-stream
X-Tenant-Id: {{tenant}}

< ./SIP_OK.zip

# < ./SIP_KO_InvalidManifest.zip

### Check SIP upload status
GET {{url-access}}/admin-external/v1/operations/{{transaction-id}}
Accept: application/json
X-Tenant-Id: {{tenant}}

### Check transaction status
GET  {{url-collect}}/collect-external/v1/transactions/{{transaction-id}}
Accept: application/json
X-Tenant-Id: {{tenant}}

### Close transaction
POST  {{url-collect}}/collect-external/v1/transactions/{{transaction-id}}/close
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}

{}

### Generate SIP
POST {{url-collect}}/collect-external/v1/transactions/{{transaction-id}}/send
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}

{}
