#%RAML 1.0 Library
usage: |
  Use to define global headers for Storage
uses:
  StorageTypes: StorageTypes.raml

traits:
  StrategyStorage:
    displayName: Storate Strategy id
    description: Storage Strategy Id
    headers:
      X-Strategy-Id:
        description: Identifiant de la Stratégie pour Offres de stockage et Copies (conservation)
        type: string
        required: true
