# Configuration
@access-contract = ContratTNR
@tenant = 0
@unit-id = aeaqaaaaaahgynv2aanysaln2jvxeyyaaaaq

### Récupération d'un groupe d'objet dont l'identifiant de l'unité archivistique est 'aeaqaaaaaahgynv2aanysaln2jvxeyyaaaaq'
GET {{url-access}}/access-external/v1/units/{{unit-id}}/objects
Accept: application/json
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}

{
  "$projection": {
    "$fields": {}
  }
}

### Récupération d'une partie (qualifiers) d'un groupe d'objet dont l'identifiant de l'unité archivistique est 'aeaqaaaaaahgynv2aanysaln2jvxeyyaaaaq'
GET {{url-access}}/access-external/v1/units/{{unit-id}}/objects
Accept: application/json
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}

{
  "$projection": {
    "$fields": {
      "#qualifiers": 1
    }
  }
}

### Récupération du 'BinaryMaster_1' de l'unité archivistique 'aeaqaaaaaahgynv2aanysaln2jvxeyyaaaaq'
GET {{url-access}}/access-external/v1/units/{{unit-id}}/objects
Accept: application/octet-stream
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}
X-Qualifier: BinaryMaster
X-Version: 1