# Configuration
@access-contract = ContratTNR
@tenant = 0

### Recherche d'un groupe d'on le nom du fichier correspond à 'IGI1300'
GET {{url-access}}/access-external/v1/objects
Accept: application/json
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}

{
  "$roots": [],
  "$query": [
    {
      "$match": {
        "FileInfo.Filename": "IGI1300"
      }
    }
  ],
  "$filter": {
    "$offset": 0,
    "$limit": 100
  },
  "$projection": {}
}

### Rechercher tout les objects groups avec une précision  sur la taille des résultats 
### !!! authorizeTrackTotalHits should be true in access-external.conf !!!
GET {{url}}/access-external/v1/objects
Accept: application/json
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}

{
  "$roots": [],
  "$query": [
    {
      "$exists": "#id"
    }
  ],
  "$filter": {
    "$offset": 0,
    "$limit": 100,
    "$track_total_hits": true
  },
  "$projection": {
    "$fields": {
      "#id": 1
    }
  }
}