get?:
  responses:
    200?:
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    201?:
      description: Created
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    202?:
      description: Accepted
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    206?:
      description: Partial Content
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    304?:
      description: Not Modified
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    400?:
      description: Bad Request
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    401?:
      description: Unauthorized
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-401.sample
    403?:
      description: Forbidden
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    404?:
      description: Not Found
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-404.sample
    405?:
      description: Method Not Allowed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    409?:
      description: Conflict
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    410?:
      description: Gone
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    412?:
      description: Precondition Failed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-412.sample
    413?:
      description: Request Entity Too Large
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    415?:
      description: Unsupported Media Type
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    422?:
      description: Unprocessable Entity
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    429?:
      description: Too Many Requests
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    500?:
      description: Internal Server Error
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    501?:
      description: Not Implemented
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    503?:
      description: Service Unavailable
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
post?:
  responses:
    200?:
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    201?:
      description: Created
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    202?:
      description: Accepted
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    206?:
      description: Partial Content
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    304?:
      description: Not Modified
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    400?:
      description: Bad Request
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    401?:
      description: Unauthorized
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-401.sample
    403?:
      description: Forbidden
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    404?:
      description: Not Found
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-404.sample
    405?:
      description: Method Not Allowed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    409?:
      description: Conflict
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    410?:
      description: Gone
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    412?:
      description: Precondition Failed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-412.sample
    413?:
      description: Request Entity Too Large
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    415?:
      description: Unsupported Media Type
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    422?:
      description: Unprocessable Entity
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    429?:
      description: Too Many Requests
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    500?:
      description: Internal Server Error
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    501?:
      description: Not Implemented
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    503?:
      description: Service Unavailable
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
put?:
  responses:
    200?:
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    201?:
      description: Created
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    202?:
      description: Accepted
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    206?:
      description: Partial Content
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    304?:
      description: Not Modified
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    400?:
      description: Bad Request
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    401?:
      description: Unauthorized
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-401.sample
    403?:
      description: Forbidden
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    404?:
      description: Not Found
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-404.sample
    405?:
      description: Method Not Allowed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    409?:
      description: Conflict
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    410?:
      description: Gone
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    412?:
      description: Precondition Failed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-412.sample
    413?:
      description: Request Entity Too Large
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    415?:
      description: Unsupported Media Type
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    422?:
      description: Unprocessable Entity
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    429?:
      description: Too Many Requests
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    500?:
      description: Internal Server Error
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    501?:
      description: Not Implemented
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    503?:
      description: Service Unavailable
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
patch?:
  responses:
    200?:
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    201?:
      description: Created
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    202?:
      description: Accepted
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    206?:
      description: Partial Content
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    304?:
      description: Not Modified
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    400?:
      description: Bad Request
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    401?:
      description: Unauthorized
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-401.sample
    403?:
      description: Forbidden
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    404?:
      description: Not Found
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-404.sample
    405?:
      description: Method Not Allowed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    409?:
      description: Conflict
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    410?:
      description: Gone
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    412?:
      description: Precondition Failed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-412.sample
    413?:
      description: Request Entity Too Large
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    415?:
      description: Unsupported Media Type
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    422?:
      description: Unprocessable Entity
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    429?:
      description: Too Many Requests
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    500?:
      description: Internal Server Error
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    501?:
      description: Not Implemented
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    503?:
      description: Service Unavailable
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample

delete?:
  responses:
    200?:
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    201?:
      description: Created
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    202?:
      description: Accepted
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    204?:
      description: No Content
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    206?:
      description: Partial Content
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    304?:
      description: Not Modified
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    400?:
      description: Bad Request
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    401?:
      description: Unauthorized
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-401.sample
    403?:
      description: Forbidden
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    404?:
      description: Not Found
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-404.sample
    405?:
      description: Method Not Allowed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    409?:
      description: Conflict
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    410?:
      description: Gone
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    412?:
      description: Precondition Failed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-412.sample
    413?:
      description: Request Entity Too Large
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    415?:
      description: Unsupported Media Type
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    422?:
      description: Unprocessable Entity
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    429?:
      description: Too Many Requests
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    500?:
      description: Internal Server Error
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    501?:
      description: Not Implemented
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    503?:
      description: Service Unavailable
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
head?:
  responses:
    200?:
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    201?:
      description: Created
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    202?:
      description: Accepted
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    206?:
      description: Partial Content
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    304?:
      description: Not Modified
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    400?:
      description: Bad Request
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    401?:
      description: Unauthorized
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-401.sample
    403?:
      description: Forbidden
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    404?:
      description: Not Found
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-404.sample
    405?:
      description: Method Not Allowed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    409?:
      description: Conflict
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    410?:
      description: Gone
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    412?:
      description: Precondition Failed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-412.sample
    413?:
      description: Request Entity Too Large
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    415?:
      description: Unsupported Media Type
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    422?:
      description: Unprocessable Entity
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    429?:
      description: Too Many Requests
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    500?:
      description: Internal Server Error
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    501?:
      description: Not Implemented
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    503?:
      description: Service Unavailable
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
options?:
  responses:
    200?:
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    201?:
      description: Created
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    202?:
      description: Accepted
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    206?:
      description: Partial Content
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    304?:
      description: Not Modified
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
    400?:
      description: Bad Request
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    401?:
      description: Unauthorized
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-401.sample
    403?:
      description: Forbidden
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    404?:
      description: Not Found
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-404.sample
    405?:
      description: Method Not Allowed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    409?:
      description: Conflict
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    410?:
      description: Gone
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    412?:
      description: Precondition Failed
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error-412.sample
    413?:
      description: Request Entity Too Large
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    415?:
      description: Unsupported Media Type
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    422?:
      description: Unprocessable Entity
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    429?:
      description: Too Many Requests
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    500?:
      description: Internal Server Error
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    501?:
      description: Not Implemented
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
    503?:
      description: Service Unavailable
      headers:
        X-RequestId:
          type: string
          description: Identifiant unique de la requête.
          example: AbDUh67jj
        FullApiVersion:
          type:  string
          description: Version complète de l'API.
          example: V2.56
      body:
        application/json:
          schema: error
          example: !include ../samples/error.sample
