    description: API permettant la vérification d'un unique _Object_.
    type: base
    is: [ standardErrors ]
    get:
      description: Vérification utilisant le mode standard GET.
      body:
        application/json:
          schema: genericObject
          example: !include ../samples/sampleObject.sample
      responses:
        200:
          headers:
            Location:
              type: string
              description: Localisation future du résultat de la tâche asynchrone.
              example: http://server/api/{version}/async_tasks/{id}
          body:
            application/json:
              schema: genericObject
              example: !include ../samples/sampleObject.sample
    post:
      is: [ x-get ]
      description: Vérification utilisant le mode compatible POST avec l'option 'X-HTTP-Method-Override=GET'.
      body:
        application/json:
          schema: genericObject
          example: !include ../samples/sampleObject.sample
      responses:
        201:
          headers:
            Location:
              type: string
              description: Localisation future du résultat de la tâche asynchrone.
              example: http://server/api/{version}/async_tasks/{id}
          body:
            application/json:
              schema: genericObject
              example: !include ../samples/sampleObject.sample
