#%RAML 1.0 Library
- Context:
    description: Type of the task.
    type: string
    enum:
      - ingest
      - access
      - query
      - freeze
      - destruction
      - platform
      - internal

- Error:
    type: object
    properties:
      code?:
        description: Short code as in RFC 7231 (Http Status Codes).
        type: integer
      context: Context
      state:
        description: Vitam specific short code.
        type: string
      message: string
      description: string
    example: |
      {
        "code" : 402,
        "context": "ingest",
        "state": "not_authorized",
        "message": "The application is not authorized to use this functionality",
        "description": "The application 'Xxxx' is not authorized to use the 'administration' service, the role 'ADMIN_ROLE' is mandatory."
      }

- ErrorMultiple:
    description: An error message in Vitam DSL
    type: object
    properties:
      code?:
        description: Short code as in RFC 7231 (Http Status Codes).
        type: integer
      context: Context
      state:
        description: Vitam specific short code.
        type: string
      message:
        description: Standard short description.
        type: string
      description:
        description: Long description.
        type: string
      errors?:
        description: Sub error descriptions.
        type: array
        items:
          type: Error
    example: |
      {
        "code": 404,
        "context": "ingest",
        "state": "Item_Not_Found",
        "message": "Item is not found",
        "description": "Operation on item xxx cannot be done since item is not found in <<resourcePathName>>",
        "errors": [
          { "code": 415,
            "context": "ingest",
            "state": "Unsupported_Media_Type",
            "message": "Unsupported media type detected",
            "description": "File xxx has an unsupported media type yyy" },
          { "code": 412,
            "context": "ingest",
            "state": "Precondition_Failed",
            "message": "Precondition in error",
            "description": "Operation on file xxx cannot continue since precondition is in error" }
        ]
      }
