    description: API de gestion des statistiques pour <<name>>.
    type: base
    is: [ standardErrors ]
    get:
      description: Accès aux statistiques.
      body:
        application/json:
          schema: collectionQuery
          example: !include ../samples/collectionQuery.sample
      responses:
        200:
          body:
            application/json:
              schema: <<answearModel>>
              example: <<exampleAnswearModel>>
