---

- hosts: hosts_storage
  any_errors_fatal: true
  roles:
    - vitam
  vars:
    vitam_struct: "{{ vitam.storage }}"
    vitam_certificate_client_type: storage
    vitam_timestamp_usage: secure-storage
  tags: storage
