  - title: Racine
    content: !include home.md
  - title: Accès
    content: !include access.md
  - title: Versement
    content: !include ingest.md
  - title: Gestion
    content: !include management.md
  - title: Administration
    content: !include admin.md
  - title: Iaas/PaaS
    content: !include paas.md
  - title: Partie Commune
    content: !include common.md
