# Configuration
@collection = "Unit"
@tenant_list = ["0"]

### Launch full reindexation of a collection
# @name reindex
POST {{url-ingest}}/adminmanagement/v1/reindex/
Accept: application/json
Content-Type: application/json

[
  {
    "collection": "{{collection}}",
    "tenants": "{{tenant_list}}"
  }
]

### Switch the associated alias to the newly created index
@index-name = {{ reindex.response.body.$.$results.0.OK.0.indexName }}
@alias-name = {{ reindex.response.body.$.$results.0.OK.0.aliasName }}

POST {{url-ingest}}/adminmanagement/v1/alias/
Accept: application/json
Content-Type: application/json

[
  {
    "alias": "{{alias-name}}",
    "indexName": "{{index-name}}"
  }
]

### Launch differential (delta) reindexation
# Only works for Unit and ObjectGroup collections
POST {{url-ingest}}/adminmanagement/v1/reindex/
Accept: application/json
Content-Type: application/json

[
  {
    "collection": "{{collection}}",
    "tenants": "{{tenant_list}}",
    "indexationStartDate": "2026-05-20"
  }
]
