# root endpoint request
displayName: LogBooks
description: API d'accès aux Journaux.
type: collection

/{id_logbook}:
  displayName: LogBook
  type: { collection-item: { answearModel: logbook, exampleAnswearModel: !include ../samples/sampleLogbook.sample } }
