# root endpoint request
displayName: Transformations
description: API d'administration des batchs de Transformations. Chaque item est un batch, c'est à dire une opération asynchrone. Un batch de Transformations est volatile, ce qui signifie qu'il peut disparaître dès qu'il est terminé. Cependant les Journaux (logbooks) garderont une trace de celui-ci.
type: { collection-write: { createModel: genericObject, exampleModel: !include ../samples/genericSample.sample, answearModel: genericObject, exampleAnswearModel: !include ../samples/genericSample.sample } }
is: [ standardErrors ]
patch:

/{id_async}:
  displayName: Transformation
  type: { collection-item-write: { createModel: genericObject, exampleModel: !include ../samples/genericSample.sample, answearModel: async_status, exampleAnswearModel: !include ../samples/async_status.sample } }
  is: [ standardErrors ]
  patch:

  /stats:
    displayName: Transformation Statistic
    type: { stats: { answearModel: genericObject, exampleAnswearModel: !include ../samples/statistic.sample, name: un batch de Transformation } }
