#!/bin/sh

getent group  vitam >/dev/null || groupadd  vitam
getent passwd vitam >/dev/null || useradd -g vitam -s /bin/bash -c "Vitam application user" vitam
getent group  vitam-admin >/dev/null || groupadd  vitam-admin
