---
# Simple example of offers configuration file.
# Please refer to the offer_opts.yml.example file for more details about all available parameters and their meaning.

## Strategy definition
vitam_strategy:
  - name: offer-fs-1
    referent: true
    rank: 0
  # - name: offer-fs-2
  #   rank: 10
  #   distant: true
  #   vitam_site_name: dc2

## Offers configuration
vitam_offers:
  offer-fs-1:
    provider: filesystem-hash
