---

# Vitam installation mode.
# Allowed values are: legacy, container
# Caution: container installation is in beta mode. Do not use it in production environments.
install_mode: legacy

## Must be set when install_mode == 'legacy'
# vitam_repositories:
#   - key: repo1 # Mandatory: Only on RedHat family (AlmaLinux or RockyLinux)
#     value: http://path_to_repo1 # Mandatory: Path to the repository
#     gpgcheck: 1 # Optionnal: Default to 0 (equivalent as [trusted=yes] on Debian)
#     gpgkey: path_to_custom_key # Optionnal: Only if gpgcheck is enabled; Default to official Vitam GPG Key
#     subtree: "./" # Optionnal: Only on Debian; Default to ./
#     proxy: http://proxy_url # Optionnal: Only on RedHat family (AlmaLinux or RockyLinux); Default to _none_

## Must be set when install_mode == 'container'
# container_repository:
#   registry_url:
#   username:
#   password:
# Add vitam_container_version for specific container version deployment (default: latest)
vitam_container_version: '9.0.0-SNAPSHOT'
