---

prometheus_blackbox_exporter_config_path: "{{ vitam_defaults.folder.root_path }}/conf/blackbox_exporter"

blackbox_exporter_port: "{{ prometheus.blackbox_exporter.port | default(9115) }}"

service_at_boot: "{{ vitam_defaults.services.at_boot | default(false) }}"

blackbox_user: "{{ prometheus.blackbox_exporter.basic_auth.username | default('') }}"
blackbox_password: "{{ prometheus.blackbox_exporter.basic_auth.password | default('') }}"
