#########################################################################################
# Dockerfile to run vitam on one server
# Based on CentOS
#
# Maintained by Vitam
#########################################################################################

# Set the base image to almalinux/9-base
FROM almalinux/9-base
MAINTAINER French Prime minister Office/SGMAP/DINSIC/Vitam Program <contact.vitam@culture.gouv.fr>

# Disable fastestmirror ; helps gain several seconds per yum invocation
COPY fastestmirror.conf /etc/yum/pluginconf.d

# Make sure the package repository and packages are up to date.
RUN yum install -y epel-release && yum -y update && yum -y upgrade && yum clean all

# Install build tools

RUN yum install -y \
    	rpm-build \
        rpmdevtools \
        initscripts.x86_64 \
        createrepo \
        selinux-policy \
        selinux-policy-devel \
        golang \
    && yum clean all

##################################  CONTAINER SETTINGS  #################################

VOLUME [ "/home" ]
WORKDIR /home

COPY entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

