#%RAML 1.0

title: API-Vitam Version Alpha - Collect
version: v1
baseUri: https://api.vitam.gouv.fr/collect-external/{version}
protocols: [ HTTP ]

uses:
  StandardTypes: libraries/StandardTypes.raml
  StandardTraits: libraries/StandardTraits.raml
  CollectTraits: libraries/CollectTraits.raml


securitySchemes:
  VitamPlatform: !include ../externe/securitySchemes/SecuritySchemeVitam.raml

securedBy: [ VitamPlatform ]

mediaType: application/json

types:
  _reserved:
    type: string

documentation:
  - title: Avertissements
    content: !include ../externe/docs-fr/avertissement-collect.md

  - title: Licence
    content: !include ../externe/docs-fr/license.md

  - title: API Collect
    content: API Collect

/projects:
  displayName: Projects
  description: |
    API de collecte. Ce point d'entrée permet d'initialiser et de gérer un projet de versement.

    Création d'un projet :
    - une requête unique, avec un 'body' contenant toutes les informations au format JSON :
      - ArchivalAgencyIdentifier
      - TransferringAgencyIdentifier
      - OriginatingAgencyIdentifier
      - SubmissionAgencyIdentifier
      - MessageIdentifier
      - ArchivalAgreement
      - unitUp
      - Comment
      - LegalStatus
      - Name
  post:
    description: |
      - request body : JSON object
      - response : JSON of saved project / HTTP CODE 200
    is: [CollectTraits.TransactionResponse, StandardTraits.StandardOptionalHeader,
         StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
         StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
    headers:
     x-tenant-id:
        required: true
    body:
       application/json:
          type: object
          example: !include libraries/examples/projectObjectRequest.json
    responses:
       200:
          body:
            application/json:
              type: object
              example: !include libraries/examples/projectObjectResponse.json
  put:
        description: |
          - request body : JSON object
          - response : JSON of saved project / HTTP CODE 200
        is: [CollectTraits.TransactionResponse, StandardTraits.StandardOptionalHeader,
             StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
             StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
        headers:
         x-tenant-id:
            required: true
        body:
           application/json:
              type: object
              example: !include libraries/examples/projectObjectPutRequest.json
        responses:
           200:
              body:
                application/json:
                  type: object
                  example: !include libraries/examples/projectObjectResponse.json
  get:
    description: |
      - request body : JSON object
      - response : JSON of saved project / HTTP CODE 200
    is: [StandardTraits.StandardOptionalHeader,
         StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
         StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
    headers:
     x-tenant-id:
        required: true
    responses:
       200:
          body:
            application/json:
              type: object
              example: !include libraries/examples/listProjectsObjectResponse.json
  /{id}:
    description: |
        API de collecte. Ce point d'entrée permet de supprimer un projet.
    delete:
        is: [ StandardTraits.StandardOptionalHeader,
             StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
             StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
        headers:
         x-tenant-id:
            required: true
        responses:
          200:
  /{id}/transactions:
       displayName: Permet de gerer les transactions d'un projet
       is: [ StandardTraits.StandardOptionalHeader,
             StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
              StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
       post:
        description: |
          - request body : JSON object
          - response : JSON of saved transaction / HTTP CODE 200
        is: [CollectTraits.TransactionResponse, StandardTraits.StandardOptionalHeader,
             StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
                    StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
        headers:
         x-tenant-id:
            required: true
        body:
           application/json:
              type: object
              example: !include libraries/examples/transactionObjectRequest.json
        responses:
           200:
              body:
                application/json:
                  type: object
                  example: !include libraries/examples/transactionResponse.json

/transactions:
  displayName: Transactions
  put:
        description: |
          - request body : JSON object
          - response : JSON of saved transaction / HTTP CODE 200
        is: [CollectTraits.TransactionResponse, StandardTraits.StandardOptionalHeader,
             StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
             StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
        headers:
         x-tenant-id:
            required: true
        body:
           application/json:
              type: object
              example: !include libraries/examples/transactionPutObjectRequest.json
        responses:
           200:
              body:
                application/json:
                  type: object
                  example: !include libraries/examples/transactionResponse.json
  /{id}/units:
        is: [ StandardTraits.StandardOptionalHeader,
              StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
               StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
        get:
         description: |
           Permet de retourner la liste des unités archivistique associés à l'identifiant du projet
         uriParameters:
             projectId:
               required: true
               description: Identifiant du projet
         body:
           application/json:
             type: object
             example: !include libraries/examples/streamUnitRequest.json
         headers:
          X-tenant-Id:
           required: true
         responses:
            200:
              body:
                application/json:
                  type: object
                  example: !include libraries/examples/CollectUnitObjectResponse.json

  /{id}/close:
        displayName: Fermer une transaction -> statut Close
        is: [ StandardTraits.StandardOptionalHeader,
              StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
               StandardTraits.StandardHeader409, StandardTraits.StandardHeader412 ]
        post:
         description: |
           Permet de fermer une transaction
         body:
          application/json:
         headers:
          X-tenant-Id:
           required: true
         responses:
            200:
              body:
                application/json:
                  type: object
                  example: !include libraries/examples/CollectTransactionCloseObjectResponse.json

  /{id}/send:
            displayName: Générer un SIP et envoyer le SIP a Vitam (Ingest)
            is: [ StandardTraits.StandardOptionalHeader,
                  StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
                   StandardTraits.StandardHeader409, StandardTraits.StandardHeader412 ]
            post:
             description: |
               Permet de génerer un SIP et l'envoyer a Vitam (Ingest)
             body:
              application/json:
             headers:
              X-tenant-Id:
               required: true
             responses:
                200:
                  body:
                    application/json:
                      type: object
                      example: !include libraries/examples/CollectIngestObjectResponse.json
  /{id}:
    description: |
        API de collecte. Ce point d'entrée permet de supprimer une transaction.
    get:
        is: [ StandardTraits.StandardOptionalHeader,
             StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
             StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
        headers:
         x-tenant-id:
            required: true
        responses:
          200:
            body:
              application/json:
                type: object
                example: !include libraries/examples/transactionResponse.json
    delete:
        is: [ StandardTraits.StandardOptionalHeader,
             StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
             StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
        headers:
         x-tenant-id:
            required: true
        responses:
          200:
  /{id}/upload:
    displayName: upload d'une archive Zip
    is: [ StandardTraits.StandardOptionalHeader,
          StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
           StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
    post:
     description: |
       Permet de soumettre un ensemble de binaire au format Zip
     body:
      application/zip:
     headers:
      X-tenant-Id:
       required: true
     responses:
        200:
          body:
            application/json:

/units:
  displayName: Units
  description: |
    API de collecte. Ce point d'entrée permet de gérer une unité archivistique et les groupe d'objets.
  is: [ StandardTraits.StandardOptionalHeader,
  StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
  StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]

  /{id}:
        is: [ StandardTraits.StandardOptionalHeader,
              StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
               StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
        get:
         description: |
           Permet de retourner une unité archivistique par son id
         headers:
          X-tenant-Id:
           required: true
         responses:
            200:
              body:
                application/json:
                  type: object
                  example: !include libraries/examples/CollectUnitObjectResponse.json

  /{id}/objects/{usage}/{version}:
    displayName: Ajout d'un groupe d'objects
    is: [ StandardTraits.StandardOptionalHeader,
          StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
           StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
    post:
     description: |
       Permet de rajouter un groupe d'objects
     body:
      application/json:
        type: object
        example: !include libraries/examples/CollectObjectGroupObjectRequest.json
     headers:
      X-tenant-Id:
       required: true
     responses:
        200:
          body:
            application/json:
              type: object
              example: !include libraries/examples/CollectObjectGroupObjectResponse.json

  /{id}/objects/{usage}/{version}/binary:
        displayName: Ajout d'un binaire
        is: [ StandardTraits.StandardOptionalHeader,
              StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
               StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
        get:
         description: |
           Permet de télécharger un binaire
         headers:
          X-tenant-Id:
           required: true
         responses:
            200:
              body:
                application/octet-stream:
                  description: Binary object as a file

        post:
         description: |
           Permet de rajouter un binaire
         body:
           application/octet-stream:
             description: Binary object as a file
         headers:
          X-tenant-Id:
           required: true
         responses:
            200:
              body:
                application/json:
                  type: object
                  example: !include libraries/examples/CollectBinaryObjectResponse.json

/objects:
  displayName: Objects
  description: |
    API de collecte. Ce point d'entrée permet de gérer les groupe d'objets.
  is: [ StandardTraits.StandardOptionalHeader,
  StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
  StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]

  /{id}:
        is: [ StandardTraits.StandardOptionalHeader,
              StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
               StandardTraits.StandardHeader409, StandardTraits.StandardHeader412]
        get:
         description: |
           Permet de retourner une groupe d'object par son id
         headers:
          X-tenant-Id:
           required: true
         responses:
            200:
              body:
                application/json:
                  type: object
                  example: !include libraries/examples/objectGroupResponse.json