#%RAML 1.0

title: API-Vitam Version Beta - Ingest
version: v1
baseUri: https://api.vitam.gouv.fr/ingest-external/{version}
protocols: [ HTTPS ]

uses:
  StandardTypes: libraries/StandardTypes.raml
  StandardTraits: libraries/StandardTraits.raml
  IngestTypes: libraries/IngestTypes.raml
  IngestTraits: libraries/IngestTraits.raml
  DslTypes: libraries/DslTypes.raml

mediaType: application/json

types:
  _reserved:
    type: string

documentation:
  - title: Avertissements
    content: !include docs-fr/avertissement.md

  - title: Licence
    content: !include docs-fr/license.md

  - title: API Ingest
    content: !include docs-fr/ingest.md

/ingests:
  displayName: Ingests
  description: |
    API de versement (Ingest). Ce point d'entrée permet de chercher ou de créer une transaction de versement. Une transaction d'entrée est volatile, c'est à dire qu'elle disparaîtra dès qu'elle sera terminée. Sa terminaison est liée à la production du rapport et sa récupération par le service de transfert ayant effectué l'entrée.

    Crée une transaction d'entrée :
    - une requête unique, avec un 'body' contenant toutes les informations dans un ZIP ou un TAR ou un TAR.GZ ou TAR.BZ2:
      - Métadonnées dans un format SEDA XML ou Json de nom manifest.xml ou manifest.json (json **UNSUPPORTED**)
      - Tous les binaires dans le répertoire "/content"
    - d'autres formes pourront être implémentées dans des versions ultérieures (multipart/form-data) avec de multiples requêtes utilisant les sous-collections futures *Units* et *Objects*

  post:
    description: |
          response : JSON asynchronous state / HTTP CODE 202 or  500 for KO
    is: [IngestTraits.IngestCreationResponseAsync]
    responses:
          202:
            body:
    headers:
      X-Action:
        enum: [ "RESUME", "PAUSE" ]
        required: true
      X-Context-Id:
        required: false
        description: |
            Il indique le workflow à exécuter DefaultIngestWorkflow pour lancer le workflow INGEST (avec toutes les étapes) ou DefaultIngestWorkflowBlankTest pour lancer le workflow INGEST-TEST (test à blanc sans les étapes de stockage d'objets et d'indéxation des UA et des GOT)
        enum: [ "DefaultIngestWorkflow", "DefaultIngestWorkflowBlankTest", "DefaultFilingSchemeWorkflow", "DefaultHoldingSchemeWorkflow" ]

  /{objectId}/{type}:
      displayName: IngestsType
      description: |
        Télécharger un objet associé au processus INGEST (reports ou manifests)
      is: [ StandardTraits.StandardOptionalHeader,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
      StandardTraits.StandardHeader409, StandardTraits.StandardHeader412, IngestTraits.IngestFinalResponse ]
      get:
        description:  |
          Permet de télécharger un objet en précisant son identifiant et son type (reports ou manifests)


/operations:
  # root endpoint request
  displayName: Opérations
  description: |
    Administration des Workflows Asynchrones (opérations). Certaines opérations devraient être limitées aux seuls administrateurs car elles impactent le back-office.

    **DEPRECATED** Les fonctions sensibles (PAUSE, CANCEL, NEXT) seront déplacées sur une ressources spécifique d'administration pour la V1.
  is: [ StandardTraits.StandardOptionalHeader,
  StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
  StandardTraits.StandardHeader409, StandardTraits.StandardHeader412 ]
  get:
    description: |
      Request that will return a listing of ingests operations
    is: [IngestTraits.IngestListingResponse ]

  /{id}:
    displayName: Operation
    is: [ StandardTraits.StandardOptionalHeader,
    StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
    StandardTraits.StandardHeader409, StandardTraits.StandardHeader412 ]
    get:
      description:  |
        Permet de récupérer le statut de l'opération dont l'identifiant est passée en paramètre
    put:
      description: |
       **DEPRECATED** : ne sera plus supporté en V1 car déplacé dans functional-administration.

       Permet de mettre à jour une opération lancée en précisant l'action à exécuter dans le header X-Action-Id; PAUSE pour la mettre en pause,
       NEXT pour exécuter l'étape suivante, RESUME pour continuer l'exécution de l'opération jusqu'au bout.
       **Cette opération ne devrait être ouverte qu'aux administrateurs**
      headers:
       X-Action:
        required: true
        enum: [ "RESUME", "NEXT", "PAUSE" ]
    delete:
     description: |
       **DEPRECATED** : ne sera plus supporté en V1 car déplacé dans functional-administration.

       Permet d'annuler un workflow lancé.
       **Cette opération ne devrait être ouverte qu'aux administrateurs**
    head:
      description: |
        Permet d'obtenir le statut d'une opération
      responses:
       200:
         description: |
           L'opération existe et est terminé, le statut est retourné
       202:
         description: |
           L'opération existe mais n'est pas terminée
       404:
         description: |
           Opération introuvable

/workflows:
  # root endpoint request
  displayName: Définitions de workflow
  description: |
    Gestion des définitions des Workflows disponibles.

  is: [ StandardTraits.StandardOptionalHeader,
    StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
    StandardTraits.StandardHeader409, StandardTraits.StandardHeader412 ]
  get:
    description: |
     Request that will return a listing of ingests operations
    is: [IngestTraits.IngestWorkflowsResponse ]

/status:
  get:
    is: [ StandardTraits.StandardHeader204,
      StandardTraits.StandardHeader404, StandardTraits.StandardHeader503 ]
