#%RAML 1.0

title: API-Vitam - Ingest
version: v1
baseUri: https://api.vitam.gouv.fr/ingest-external/{version}
protocols: [ HTTPS ]

uses:
  StandardTypes: libraries/StandardTypes.raml
  StandardTraits: libraries/StandardTraits.raml
  IngestTypes: libraries/IngestTypes.raml
  IngestTraits: libraries/IngestTraits.raml
  DslTypes: libraries/DslTypes.raml

mediaType: application/json

types:
  _reserved:
    type: string

documentation:
  - title: Avertissements
    content: !include docs-fr/avertissement.md

  - title: Licence
    content: !include docs-fr/license.md

  - title: API Ingest
    content: !include docs-fr/ingest.md

/ingests:
  displayName: Ingests
  description: |
    API de versement (Ingest). Ce point d'entrée permet de créer une transaction de versement. Une transaction d'entrée est volatile, c'est à dire qu'elle disparaîtra dès qu'elle sera terminée.
    Sa terminaison est liée à la production du rapport et sa récupération par le service de transfert ayant effectué l'entrée.

    Créé une transaction d'entrée :
    - une requête unique, avec un 'body' contenant toutes les informations dans un ZIP ou un TAR ou un TAR.GZ ou TAR.BZ2:
      - Métadonnées dans un format SEDA XML de nom manifest.xml
      - Tous les binaires dans le répertoire "/content"
    - une requête unique, avec un 'body' contenant un chemin vers un fichier binaire présent sur le disque local du dossier spécifié dans la configuration de l'ingest externe. Le format du body est json.
    - d'autres formes pourront être implémentées dans des versions ultérieures (multipart/form-data) avec de multiples requêtes utilisant les sous-collections futures *Units* et *Objects*

  post:
    description: |
          response : JSON asynchronous state / HTTP CODE 202 or  500 for KO
    is: [IngestTraits.IngestCreationResponseAsync]
    responses:
          202:
            body:
    headers:
      X-Action:
        required: true
        description: |
          Il indique le type de workflow à exécuter : RESUME correspond au mode nominal, NEXT correspond au mode pas à pas
        enum: [ "RESUME", "NEXT" ]
      X-Context-Id:
        required: false
        description: |
            Il indique le workflow à exécuter DEFAULT_WORKFLOW pour lancer le workflow INGEST (avec toutes les étapes) ou BLANK_TEST pour lancer le workflow INGEST-TEST
            (test à blanc sans les étapes de stockage d'objets et d'indéxation des UA et des GOT) ou encore FILING_SCHEME pour les plans de classements et enfin HOLDING_SCHEME pour les arbres de positionnement
        enum: [ "DEFAULT_WORKFLOW", "BLANK_TEST", "FILING_SCHEME", "HOLDING_SCHEME" ]
      X-Manifest-Digest-Value:
        required: false
        description: |
            Il indique, si présent, la valeur de l'empreinte attendue du manifest du versement en cours (ex. 3112e4f4f66c70f0565b95ea270c7488f074ace3ab28f74feaa975751b424619ff429490416f1c4b630361ab16f0bb5f16d92f5a867e6f94c886464e95f82ca5).
            Doit être spécifié en même temps que l'entête X-Manifest-Digest-Algo
      X-Manifest-Digest-Algo:
        required: false
        description: |
            Il indique, si présent, l'algorithme de l'empreinte du manifest du versement en cours. Doit être spécifié en même temps que l'entête X-Manifest-Digest-Value
        enum: [ "SHA-512", "SHA-384", "SHA-256" ]

  /{operationId}/{type}:
      displayName: IngestsType
      uriParameters:
        type:
          required: true
          description: |
            Type de l'objet à télécharger
          enum: [ "manifests", "archivetransferreply" ]
        operationId:
          required: true
          description: |
            Identifiant de l'opération sous forme d'un GUID

      description: |
        Télécharger un objet associé au processus INGEST (archivetransferreply ou manifests)
      is: [ StandardTraits.StandardOptionalHeader,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
      StandardTraits.StandardHeader409, StandardTraits.StandardHeader412, IngestTraits.IngestFinalResponse ]
      get:
        description:  |
          Permet de télécharger un objet en précisant l'identifiant de l'opération à l'origine de l'objet et son type (archivetransferreply ou manifests)

/:
  displayName: Endpoints
  description: |
   API qui liste les endpoints de la ressource /ingest-external/{version}.
  options:
    description: |
      Request that will return list of endpoints
    is: [ StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader404, StandardTraits.StandardHeader503 ]

/status:
  get:
    is: [ StandardTraits.StandardHeader204,
      StandardTraits.StandardHeader404, StandardTraits.StandardHeader503 ]
