#%RAML 1.0

title: API-Vitam Version Alpha - Logbook
version: v1
baseUri: https://api.vitam.gouv.fr/{version}
protocols: [ HTTPS ]

uses:
  StandardTypes: libraries/StandardTypes.raml
  StandardTraits: libraries/StandardTraits.raml
  LogbookTypes: libraries/LogbookTypes.raml
  LogbookTraits: libraries/LogbookTraits.raml
  DslTypes: libraries/DslTypes.raml

mediaType: application/json

types:
  _reserved:
    type: string

documentation:
  - title: Avertissements
    content: !include docs-fr/avertissement.md

  - title: Licence
    content: !include docs-fr/license.md

  - title: API Logbook
    content: !include docs-fr/logbook.md

/logbookoperations:
  displayName: Operations Logbooks
  description: |
    API d'accès aux Journaux d'opérations (Logbooks Operations). Ce point d'entrée permet de chercher une opération (entrée, audit, élimination, préservation, ...).

    La recherche sur cette API retourne pour chaque opération, la première entrée (la création à la date de démarrage de l'opération) et la dernière entrée (dans l'état connu par le journal à la date de la dernière étape de cette opération).
  get:
    description: |
      Response model for the listing of Logbook operations.
    is: [LogbookTraits.OperationListingResponse ]
  post:
    description: |
      Response model for the listing of Logbook operations. The request is using POST with X-Http-Method-Override: GET
    is: [LogbookTraits.OperationListingResponse, StandardTraits.OverrideGet]


  /{idop}:
    displayName: Operation Logbook
    description: Accès à une opération.
    get:
      description: Response model for one Logbook operation item.
      is: [LogbookTraits.OperationItemResponse]
    post:
      description: |
        Response model for one Logbook operation item. The request is using POST with X-Http-Method-Override: GET
      is: [LogbookTraits.OperationItemResponse, StandardTraits.OverrideGet]

    /logbookunitlifecycles:
      displayName: Unit Life Cycles Logbooks For Operation
      description: |
        **UNSUPPORTED** API d'accès aux Journaux de cycle de vie des Units. Ce point d'entrée permet de chercher un cycle de vie
        ayant été impacté par cette opération (pour une entrée les archives ayant été intégrées, pour une élimination les archives ayant été éliminées, ...).

        La recherche sur cette API retourne uniquement la première ligne et la dernière connue pour chaque journal du cycle de vie en rapport avec l'opération concernée.
      get:
        description: |
          **UNSUPPORTED** Response model for the listing of Logbook unit life cycles
        is: [LogbookTraits.UnitLifeCycleListingResponse ]
      post:
        description: |
          **UNSUPPORTED** Response model for the listing of Logbook unit life cycles. The request is using POST with X-Http-Method-Override: GET
        is: [LogbookTraits.UnitLifeCycleListingResponse, StandardTraits.OverrideGet]

      /{id_lfc}:
        displayName: Unit Life Cycle Logbook For Operation
        description: |
          **UNSUPPORTED** Accès à un cycle de vie lié à l'opération en référence (Unit).

          Le cycle de vie concerné est retourné complet ou tronqué aux seuls événements liés à l'opération en référence selon l'argument X-Full.
        get:
          description: |
            **UNSUPPORTED** Response model for one Logbook unit life cycle item.
          is: [LogbookTraits.UnitLifeCycleItemResponse]
        post:
          description: |
            **UNSUPPORTED** Response model for one Logbook unit life cycle item. The request is using POST with X-Http-Method-Override: GET
          is: [LogbookTraits.UnitLifeCycleItemResponse, StandardTraits.OverrideGet]

    /objectlifecycles:
      displayName: Object Life Cycles Logbooks For Operation
      description: |
        **UNSUPPORTED** API d'accès aux Journaux de cycle de vie des Objects. Ce point d'entrée permet de chercher un cycle de
        vie ayant été impacté par cette opération (pour une entrée les archives ayant été intégrées, pour une élimination les archives ayant été éliminées, ...).

        La recherche sur cette API retourne uniquement la première ligne et la dernière connue pour chaque journal du cycle de vie en rapport avec l'opération concernée.
      get:
        description : |
          **UNSUPPORTED** Response model for the listing of Logbook object life cycles
        is: [LogbookTraits.ObjectLifeCycleListingResponse ]
      post:
        description : |
          **UNSUPPORTED** Response model for the listing of Logbook object life cycles. The request is using POST with X-Http-Method-Override: GET
        is: [LogbookTraits.ObjectLifeCycleListingResponse, StandardTraits.OverrideGet]

      /{id_lfc}:
        displayName: Object Life Cycle Logbook For Operation
        description: |
          **UNSUPPORTED** Accès à un cycle de vie lié à l'opération en référence (Object).

          Le cycle de vie concerné est retourné complet ou tronqué aux seuls événements liés à l'opération en référence selon l'argument X-Full.
        get:
          description : |
           **UNSUPPORTED** Response model for one Logbook object life cycle item
          is: [LogbookTraits.ObjectLifeCycleItemResponse]
        post:
          description : |
            **UNSUPPORTED** Response model for one Logbook object life cycle item. The request is using POST with X-Http-Method-Override: GET
          is: [LogbookTraits.ObjectLifeCycleItemResponse, StandardTraits.OverrideGet]

/logbookunitlifecycles:
  displayName: Unit Life Cycle Logbook
  description: |
    API d'accès aux Journaux de cycle de vie des Units.

    La recherche sur cette API retourne uniquement la première ligne et la dernière connue pour chaque journal du cycle de vie.
  get:
    description : |
      **UNSUPPORTED**  Response model for the listing of Logbook unit life cycles
    is: [LogbookTraits.UnitLifeCycleListingResponse ]
  post:
    description : |
      **UNSUPPORTED**  Response model for the listing of Logbook unit life cycles. The request is using POST with X-Http-Method-Override: GET
    is: [LogbookTraits.UnitLifeCycleListingResponse, StandardTraits.OverrideGet]

  /{id_lfc}:
    displayName: Unit Life Cycle
    description: Accès à un cycle de vie (Unit).

      Le cycle de vie concerné est retourné complet.
    get:
      description : |
        Response model for one Logbook unit life cycle item
      is: [LogbookTraits.UnitLifeCycleItemResponse]
    post:
      description : |
        Response model for one Logbook unit life cycle item. The request is using POST with X-Http-Method-Override: GET
      is: [LogbookTraits.UnitLifeCycleItemResponse, StandardTraits.OverrideGet]

/objectlifecycles:
  displayName: Object Life Cycle Logbook
  description: |
    API d'accès aux Journaux du Cycle de Vie des archives (Object).

    La recherche sur cette API retourne uniquement la première ligne et la dernière connue pour chaque journal du cycle de vie.
  get:
    description : |
      **UNSUPPORTED** Response model for the listing of Logbook object life cycles
    is: [LogbookTraits.ObjectLifeCycleListingResponse ]
  post:
    description : |
      **UNSUPPORTED**  Response model for the listing of Logbook object life cycles. The request is using POST with X-Http-Method-Override: GET
    is: [LogbookTraits.ObjectLifeCycleListingResponse, StandardTraits.OverrideGet]

  /{id_lfc}:
    displayName: Object Life Cycle
    description: Accès à un cycle de vie (Object).

      Le cycle de vie concerné est retourné complet.
    get:
      description : Response model for one Logbook object life cycle item
      is: [LogbookTraits.ObjectLifeCycleItemResponse]
    post:
      description : |
        Response model for one Logbook object life cycle item. The request is using POST with X-Http-Method-Override: GET
      is: [LogbookTraits.ObjectLifeCycleItemResponse, StandardTraits.OverrideGet]



/traceability:
  displayName: Operation Logbook Security
  description: |
    **DEPRECATED** : ne sera plus supporté en V1 car déplacé dans functional-administration.

    Lancement d'une opération de sécurisation des journaux d'opération.

  /check:
    displayName: Operation Logbook Security
    description: |
      **DEPRECATED** : ne sera plus supporté en V1 car déplacé dans functional-administration.

      Lancement d'une opération de sécurisation des journaux d'opération.
    post:
      description: |
        Permet de lancer une opération de sécurisation des journaux d'opération sur un tenant donné.
      is: [StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader200, StandardTraits.StandardHeader400,
        , StandardTraits.StandardHeader500, StandardTraits.StandardHeader401, StandardTraits.StandardHeader200, StandardTraits.StandardHeader417]
      body:
        application/json:
          description: Body contains a Query in DSL Vitam to filter the Logbook operations
          schema: DslTypes.DslQuery
      responses:
       200:
         description: |
           L'opération a été réalisée avec succès. L'ID de l'opération est retournée.
       400:
         description: |
           Le tenant n'est pas indiqué, l'opération n'a pu être réalisée.
       500:
         description: |
           Un problème interne a empêché l'opération de se dérouler.

  /{idop}:
    displayName: Operation Logbook Security Conformity report
    description: |
      **DEPRECATED** : ne sera plus supporté en V1 car déplacé dans functional-administration.

      Demande le rapport de conformité d'une opération de sécurisation
    get:
      description: |
        Permet de lancer une vérification d'une opération de sécurisation des journaux d'opération sur un tenant donné.
      is: [LogbookTraits.RegisterFileItemResponse, StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader200, StandardTraits.StandardHeader412]
      responses:
       200:
         description: |
           L'opération a été réalisée avec succès. Le rapport au format ZIP est retourné.
         body:
           application/zip:
             description: Security report
       412:
         description: |
           Le tenant n'est pas indiqué, l'opération n'a pu être 

       500:
         description: |
           Un problème interne (ou des arguments incorrects, comme le tenant) a empêché l'opération de se dérouler.

/status:
  get:
    is: [ StandardTraits.StandardHeader204,
      StandardTraits.StandardHeader404, StandardTraits.StandardHeader503 ]
