---
# Confirm launching this playbook
- hosts: localhost
  any_errors_fatal: true
  gather_facts: false
  vars_prompt:
    name: confirmation
    prompt: "This playbook will delete old collect data and binaries.\n\nAre you sure you want to run this playbook?\nAnswer with 'YES'"
    default: 'NO'
    private: false
  tasks:
    - name: Check Confirmation
      fail:
        msg: Playbook run confirmation failed
      when: not confirmation | bool
      tags: always

- hosts: hosts_collect
  roles:
    - purge_collect

- hosts: hosts_mongos_data
  gather_facts: false
  run_once: true
  roles:
    - update_collect_referential_data
