---

- hosts: localhost
  any_errors_fatal: true
  gather_facts: false
  vars_prompt:
    name: confirmation
    prompt: "/!\\ WARNING : This playbook will cleanup kibana configuration indexes for your kibana data and kibana log.\n\nAre you sure you want to run this playbook?\nAnswer with 'YES'"
    default: 'NO'
    private: false
  tasks:
    - name: Check Confirmation
      fail:
        msg: Playbook run confirmation failed
      when: not confirmation | bool
      tags: always

- hosts: hosts_kibana_log
  roles:
    - remove_kibana_conf_indexes

- hosts: hosts_kibana_data
  roles:
    - remove_kibana_conf_indexes
