---

- name: Create input.d folder
  file:
    path: /etc/filebeat/inputs.d
    state: directory
    mode: 0755
  notify: "filebeat - restart service"

- set_fact:
    services_on_vm: "{{ group_names | regex_replace('hosts_', '') | regex_replace('storage_offer_default', 'storageofferdefault') | regex_replace('storage_engine', 'storageengine') | regex_replace('access_external', 'accessexternal') | regex_replace('access_internal', 'accessinternal') | regex_replace('batch_report', 'batchreport') | regex_replace('ingest_external', 'ingestexternal') | regex_replace('ingest_internal', 'ingestinternal') }}"

- block:

  - set_fact:
      vitam_keys: "{{ vitam.keys() | list }}"

  - set_fact:
      vitam_service_list: "{{ services_on_vm | intersect(vitam_keys) }}"

  - name: Add Vitam filebeat inputs
    template:
      src: inputs/vitam_services.yml.j2
      dest: /etc/filebeat/inputs.d/vitam-services.yml
      mode: 0644
    notify: "filebeat - restart service"

  when: inventory_hostname in groups['vitam']

- name: Add Antivirus filebeat inputs
  template:
    src: inputs/antivirus.yml.j2
    dest: /etc/filebeat/inputs.d/antivirus.yml
    mode: 0644
  when: inventory_hostname in groups['hosts_ingest_external']
  notify: "filebeat - restart service"

- set_fact:
    cots_on_vm: "{{ services_on_vm + ['consul'] }}"

- set_fact:
    cots_service_list: "{{ cots_on_vm | intersect(cots_list) }}"

- name: Add COTS filebeat inputs
  template:
    src: inputs/cots.yml.j2
    dest: /etc/filebeat/inputs.d/cots.yml
    mode: 0644
  notify: "filebeat - restart service"
