---

- name: Create modules.d folder
  file:
    path: "{{ filebeat_modules_dir }}"
    state: directory
    mode: "{{ vitam_defaults.folder.folder_permission }}"
  notify: "filebeat - restart service"

- name: Add kibana filebeat module
  template:
    src: modules/kibana.yml.j2
    dest: "{{ filebeat_modules_dir }}/kibana.yml"
    mode: 0644
  when:
    - inventory_hostname in groups['hosts_kibana_data'] or
      inventory_hostname in groups['hosts_kibana_log']
  notify: "filebeat - restart service"

- name: Add elasticsearch filebeat module
  template:
    src: modules/elasticsearch.yml.j2
    dest: "{{ filebeat_modules_dir }}/elasticsearch.yml"
    mode: 0644
  when:
    - inventory_hostname in groups['hosts_elasticsearch_data'] or
      inventory_hostname in groups['hosts_elasticsearch_log']
  notify: "filebeat - restart service"

- name: Add logstash filebeat module
  template:
    src: modules/logstash.yml.j2
    dest: "{{ filebeat_modules_dir }}/logstash.yml"
    mode: 0644
  when:
    - inventory_hostname in groups['hosts_logstash']
  notify: "filebeat - restart service"

- name: Add mongodb filebeat module
  template:
    src: modules/mongodb.yml.j2
    dest: "{{ filebeat_modules_dir }}/mongodb.yml"
    mode: 0644
  when:
    - inventory_hostname in groups['hosts_mongos_data'] or
      inventory_hostname in groups['hosts_mongod_data'] or
      inventory_hostname in groups['hosts_mongoc_data'] or
      inventory_hostname in groups['hosts_mongos_offer'] or
      inventory_hostname in groups['hosts_mongod_offer'] or
      inventory_hostname in groups['hosts_mongoc_offer']
  notify: "filebeat - restart service"

- name: Add apache filebeat module
  template:
    src: modules/apache.yml.j2
    dest: "{{ filebeat_modules_dir }}/apache.yml"
    mode: 0644
  when: inventory_hostname in groups['reverse']
  notify: "filebeat - restart service"

- name: Add system filebeat module
  template:
    src: modules/system.yml.j2
    dest: "{{ filebeat_modules_dir }}/system.yml"
    mode: 0644
  when:
    - filebeat.system.enable_log | bool or
      filebeat.system.enable_auth | bool
  notify: "filebeat - restart service"

- name: Disable system filebeat module
  file:
    path: "{{ filebeat_modules_dir }}/system.yml"
    state: absent
  when:
    - not filebeat.system.enable_log | bool
    - not filebeat.system.enable_auth | bool
  notify: "filebeat - restart service"
