---

- name: Stop filebeat service
  systemd:
    name: filebeat
    state: stopped
  ignore_errors: true

- name: Uninstall filebeat package
  package:
    name: "{{ filebeat_package }}"
    state: absent
  notify: daemon reload

- name: Clean systemd
  command: systemctl reset-failed
