---

- name: Stop filebeat service
  systemd:
    name: filebeat
    state: stopped
  ignore_errors: true

- name: Uninstall filebeat package
  package:
    name: "{{ filebeat_package }}"
    state: absent
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"
  notify: daemon reload

- name: Clean systemd
  command: systemctl reset-failed
