
# Configuration MongoDB
mongoDbNodes:
- dbHost: localhost
  dbPort: 27017
dbName: masterdata
dbAuthentication: true
dbUserName: functional-admin
dbPassword: azerty3

#Basic Authentication
adminBasicAuth:
- userName: adminUser
  password: adminPassword

#Basic Authentication
adminBasicAuth:
- userName: adminUser
  password: adminPassword

jettyConfig: jetty-config.xml
urlWorkspace: http://workspace.service.consul:8201/
urlProcessing: http://processing.service.consul:8203/

# ElasticSearch
clusterName: elasticsearch-data
elasticsearchConfigurationFile: elasticsearch-settings/elasticsearch-configuration.json
elasticsearchNodes:
- hostName: localhost
  httpPort: 9200

# ElasticSearch tenant indexation
elasticsearchTenantIndexation:
  default_config:
    number_of_shards: 1
    number_of_replicas: 0
  ontology:
    number_of_shards: 2
    number_of_replicas: 0

# ExternalId configuration
listEnableExternalIdentifiers:
  0:
    - INGEST_CONTRACT
    - ACCESS_CONTRACT
    - MANAGEMENT_CONTRACT
    - ARCHIVE_UNIT_PROFILE
  1:
    - INGEST_CONTRACT
    - ACCESS_CONTRACT
    - MANAGEMENT_CONTRACT
    - PROFILE
    - SECURITY_PROFILE
    - CONTEXT


listMinimumRuleDuration:
  2:
    AppraisalRule : 1 year

accessionRegisterSymbolicThreadPoolSize: 4
ruleAuditThreadPoolSize: 4

customSearchOnFields:
  default_config:
    unit:
      fields:
        - fieldPath: Title
          types:
            - Strict
            - Minimal
        - fieldPath: Description
          types:
            - Minimal
    objectgroup:
      fields:
        - fieldPath: Description
          types:
            - Strict

  dedicated_tenants:
    - tenants: '2, 3'
      unit:
         fields:
            - fieldPath: Title
              types:
                - Strict
                - LightMinimal
            - fieldPath: Description
              types:
                - Strict
      objectgroup:
         fields:
            - fieldPath: Description
              types:
                - Strict
  grouped_tenants:
    - name: 'grp1'
      tenants: '5, 8'
      unit:
         fields:
            - fieldPath: Title
              types:
                - Any
                - Minimal
            - fieldPath: Description
              types:
                - Strict
      objectgroup:
         fields:
            - fieldPath: Description
              types:
                - Strict

      objectgroup:
         fields:
            - fieldPath: Description
              types:
                - Strict
