# root endpoint request
displayName: Servers
description: API d'administration des serveurs.
type: { collection-write: { createModel: genericObject, exampleModel: !include ../samples/genericSample.sample, answearModel: genericObject, exampleAnswearModel: !include ../samples/genericSample.sample } }
is: [ standardErrors ]
patch:

/{id}:
  displayName: Server
  type: { collection-item-write: { createModel: genericObject, exampleModel: !include ../samples/genericSample.sample, answearModel: genericObject, exampleAnswearModel: !include ../samples/genericSample.sample } }
  is: [ standardErrors ]
  patch:
  delete:

  /stats:
    displayName: Server Statistic
    type: { stats: { answearModel: genericObject, exampleAnswearModel: !include ../samples/statistic.sample, name: un Serveur } }
