<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>fr.gouv.vitam</groupId>
        <artifactId>ina-tape-proxy</artifactId>
        <version>9.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>ina-tape-proxy-client</artifactId>

    <dependencies>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>storage-engine-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>common-storage</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>ina-tape-proxy-common</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>ina-tape-proxy-web</artifactId>
            <version>${project.version}</version>
            <!--Only to ensure ina-tape-proxy-web is build before the client (required for swagger file generation) -->
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-multipart-provider</artifactId>
            <version>${resteasy.client.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.6</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.13.4</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <configuration>
                    <header>../../../../licenses/cecillc.txt</header>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>generate-client</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.parent.basedir}/ina-tape-proxy-web/target/generated-documentation/openapi.yaml</inputSpec>
                            <generatorName>java</generatorName>
                            <output>${project.build.directory}/generated-sources/openapi</output>
                            <apiPackage>fr.gouv.vitam.storage.cold.client</apiPackage>
                            <generateModelTests>false</generateModelTests>
                            <generateModels>false</generateModels>
                            <generateApiTests>false</generateApiTests>
                            <modelPackage>fr.gouv.vitam.storage.engine.common.api.dto</modelPackage>
                            <invokerPackage>fr.gouv.vitam.storage.cold.client.invoker</invokerPackage>
                            <library>resteasy</library>
                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                                <useJakartaEe>true</useJakartaEe>
                                <useAbstractionForFiles>true</useAbstractionForFiles>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>${build-helper-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/openapi</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>