# root endpoint request
displayName: Access Contracts
description: Opérations sur les Contrats d'Accès
type: { collection-write: { createModel: access_contract, exampleModel: !include ../samples/referentials/access_contract.sample, answearModel: access_contract, exampleAnswearModel: !include ../samples/referentials/access_contract.sample } }
is: [ standardErrors ]
patch:

/{id_contract}:
  displayName: Access Contract
  type: { collection-item-write: { createModel: access_contract, exampleModel: !include ../samples/referentials/access_contract.sample, answearModel: access_contract, exampleAnswearModel: !include ../samples/referentials/access_contract.sample } }
  is: [ standardErrors ]
  patch:
  delete:

  /stats:
    displayName: Access Contract Statistic
    type: { stats: { answearModel: genericObject, exampleAnswearModel: !include ../samples/statistic.sample, name: un Contrat d'Accès } }
