  displayName: Global Configuration
  description: Gestion de la configuration globale du SAE
  type: { collection-item-write: { createModel: global_configuration, exampleModel: !include ../samples/referentials/global_configuration.sample, answearModel: global_configuration, exampleAnswearModel: !include ../samples/referentials/global_configuration.sample } }
  is: [ standardErrors ]
  patch:
