# root endpoint request
displayName: Consolidated Storages
description: Administration des offres de stockage consolidées par ensemble logique (offre de conservation sécurisée, offre de diffusion, ...)
type: { collection-write: { createModel: consolidated_storage, exampleModel: !include ../samples/referentials/consolidated_storage.sample, answearModel: consolidated_storage, exampleAnswearModel: !include ../samples/referentials/consolidated_storage.sample } }
is: [ standardErrors ]
patch:

/{id}:
  displayName: Consolidated Storage Item
  type: { collection-item-write: { createModel: consolidated_storage, exampleModel: !include ../samples/referentials/consolidated_storage.sample, answearModel: consolidated_storage, exampleAnswearModel: !include ../samples/referentials/consolidated_storage.sample } }
  is: [ standardErrors ]
  patch:
  delete:
