# root endpoint request
displayName: Consolidated Transformations
description: Administration des règles de transformations consolidées par ensemble logique (Conservation, Diffusion, Vignette, Texte ASCII, ...)
type: { collection-write: { createModel: consolidated_transformation, exampleModel: !include ../samples/referentials/consolidated_transformation.sample, answearModel: consolidated_transformation, exampleAnswearModel: !include ../samples/referentials/consolidated_transformation.sample } }
is: [ standardErrors ]
patch:

/{id}:
  displayName: Consolidated Transformation Item
  type: { collection-item-write: { createModel: consolidated_transformation, exampleModel: !include ../samples/referentials/consolidated_transformation.sample, answearModel: consolidated_transformation, exampleAnswearModel: !include ../samples/referentials/consolidated_transformation.sample } }
  is: [ standardErrors ]
  patch:
  delete:
