# root endpoint request
displayName: Formats
description: Référentiel des Formats.
type: { collection-write: { createModel: genericObject, exampleModel: !include ../samples/sampleFormat.sample, answearModel: genericObject, exampleAnswearModel: !include ../samples/sampleFormat.sample } }

/{id_format}:
  displayName: Format
  type: { collection-item-write: { createModel: genericObject, exampleModel: !include ../samples/sampleFormat.sample, answearModel: genericObject, exampleAnswearModel: !include ../samples/sampleFormat.sample } }
  is: [ standardErrors ]
  patch:
  delete:

  /stats:
    displayName: Formats Statistic
    type: { stats: { answearModel: genericObject, exampleAnswearModel: !include ../samples/statistic.sample, name: un Format } }

  /transformations: !include Transformation_Rules-write.raml
