# root endpoint request
displayName: Freeze Preservation Contracts
description: Opérations sur les Contrats de Préservation de Gel
type: { collection-write: { createModel: freeze_preservation_contract, exampleModel: !include ../samples/referentials/freeze_preservation_contract.sample, answearModel: freeze_preservation_contract, exampleAnswearModel: !include ../samples/referentials/freeze_preservation_contract.sample } }
is: [ standardErrors ]
patch:

/{id_contract}:
  displayName: Freeze Preservation Contract
  type: { collection-item-write: { createModel: freeze_preservation_contract, exampleModel: !include ../samples/referentials/freeze_preservation_contract.sample, answearModel: freeze_preservation_contract, exampleAnswearModel: !include ../samples/referentials/freeze_preservation_contract.sample } }
  is: [ standardErrors ]
  patch:
  delete:

  /stats:
    displayName: Freeze Preservation Contract Statistic
    type: { stats: { answearModel: genericObject, exampleAnswearModel: !include ../samples/statistic.sample, name: un Contrat de Preservation de Gel } }
