  displayName: Generic Collection Item
  type: { collection-item-write: { createModel: genericObject, exampleModel: !include ../samples/genericSample.sample, answearModel: genericObject, exampleAnswearModel: !include ../samples/genericSample.sample } }
  is: [ standardErrors ]
  patch:
