# root endpoint request
displayName: Ingests Contracts
description: Opérations sur les Contrats de Versement
type: { collection-write: { createModel: ingest_contract, exampleModel: !include ../samples/referentials/ingest_contract.sample, answearModel: ingest_contract, exampleAnswearModel: !include ../samples/referentials/ingest_contract.sample } }
is: [ standardErrors ]
patch:

/{id_contract}:
  displayName: Ingest Contract
  type: { collection-item-write: { createModel: ingest_contract, exampleModel: !include ../samples/referentials/ingest_contract.sample, answearModel: ingest_contract, exampleAnswearModel: !include ../samples/referentials/ingest_contract.sample } }
  is: [ standardErrors ]
  patch:
  delete:

  /stats:
    displayName: Ingest Contract Statistic
    type: { stats: { answearModel: genericObject, exampleAnswearModel: !include ../samples/statistic.sample, name: un Contrat de Versement } }

  /destruction:
    displayName: Ingest Contract destruction
    description: API qui permet de déclencher un batch d'élimination sur un contrat de versement particulier.
    type: object-item-check
    is: [ standardErrors ]
    get:
      description: Activation d'un batch de destruction pour ce contrat de versement
    post:
      description: Activation d'un batch de destruction pour ce contrat de versement (identique avec POST)

/destruction:
  displayName: Ingests Contract destruction
  description: API qui permet de déclencher un batch d'élimination sur un ensemble de contrats de versement.
  type: collection
  get:
    description: Activation d'un batch de destruction pour un ensemble de contrats de versement
  post:
    description: Activation d'un batch de destruction pour un ensemble de contrats de versement (identique avec POST)
