# root endpoint request
displayName: Metadata Schemas
description: Opérations sur les Schémas de Métadonnées (Note pour le moment, un schéma XSD est fourni en exemple mais devrait être un schéma JSON)
type: { collection-write: { createModel: schema_model, exampleModel: !include ../samples/referentials/schema.sample, answearModel: schema_model, exampleAnswearModel: !include ../samples/referentials/schema.sample } }
is: [ standardErrors ]
patch:

/{id_schema}:
  displayName: Metadata Schema
  description: Opérations sur un Schéma de Métadonnées (Note pour le moment, un schéma XSD est fourni en exemple mais devrait être un schéma JSON)
  type: { collection-item-write: { createModel: schema_model, exampleModel: !include ../samples/referentials/schema.sample, answearModel: schema_model, exampleAnswearModel: !include ../samples/referentials/schema.sample } }
  is: [ standardErrors ]
  patch:
  delete:

  /stats:
    displayName: Metadata Schema Statistic
    type: { stats: { answearModel: genericObject, exampleAnswearModel: !include ../samples/statistic.sample, name: un Schéma de Métadonnées } }
