# root endpoint request
displayName: Transfers
description: Administration des Transferts (hors REST).
type: { collection-write: { createModel: genericObject, exampleModel: !include ../samples/sampleTransfer.sample, answearModel: genericObject, exampleAnswearModel: !include ../samples/sampleTransfer.sample } }
is: [ standardErrors ]
patch:

/{id_transfer}:
  displayName: Transfer
  type: { collection-item-write: { createModel: genericObject, exampleModel: !include ../samples/sampleTransfer.sample, answearModel: genericObject, exampleAnswearModel: !include ../samples/sampleTransfer.sample } }
  is: [ standardErrors ]
  patch:
  delete:

  /stats:
    displayName: Transfer Statistic
    type: { stats: { answearModel: genericObject, exampleAnswearModel: !include ../samples/statistic.sample, name: un Transfer } }
