# root endpoint request
displayName: Transformation Rules
description: Administration des règles de Transformation en mode modification. Chaque règle de transformation utilise le format parent courant comme source et un autre format dans ses métadonnées comme cible.
type: { collection-write: { createModel: genericObject, exampleModel: !include ../samples/sampleTransformation_Rule.sample, answearModel: genericObject, exampleAnswearModel: !include ../samples/sampleTransformation_Rule.sample } }
is: [ standardErrors ]
patch:

/{id_transformation}:
  displayName: Transformation Rule
  type: { collection-item-write: { createModel: genericObject, exampleModel: !include ../samples/sampleTransformation_Rule.sample, answearModel: genericObject, exampleAnswearModel: !include ../samples/sampleTransformation_Rule.sample } }
  is: [ standardErrors ]
  patch:
  delete:

  /stats:
    displayName: Transformation Rule Statistic
    type: { stats: { answearModel: genericObject, exampleAnswearModel: !include ../samples/statistic.sample, name: une Règle de Transformation } }
