#%RAML 1.0 Library

usage: |
  Use to define global headers for Access
uses:
  StandardTypes: StandardTypes.raml
  StandardTraits: StandardTraits.raml
  AccessTypes: AccessTypes.raml

traits:

  AccessUnitResponse:
    description: Response model for Units collection in access
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.PaginationRequestHeader,  StandardTraits.PaginationNextHeader,  StandardTraits.PaginationResponseHeader,
      StandardTraits.StandardHeader200, StandardTraits.StandardHeader206,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    body:
      application/json:
        description: Body contains in JSON format the VITAM DSL request part
        type: AccessTypes.AccessQuery
        example: !include examples/accessUnitQuery.json
    responses:
      200:
        description: Returns the list of Units results
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/accessUnitResponse.json
          application/zip:
            description: Metadata and Binary object(s)
          application/x-tar:
            description: Metadata and Binary object(s)
          application/octet-stream:
            description: Binary object
      206:
        description: Returns the list of Units results using Cursor
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/accessUnitResponse.json

  AccessObjectResponse:
    description: Response model for Objects collection in access
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.PaginationRequestHeader,  StandardTraits.PaginationNextHeader,  StandardTraits.PaginationResponseHeader,
      StandardTraits.StandardHeader200, StandardTraits.StandardHeader206,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    body:
      application/json:
        description: Body contains in JSON format the VITAM DSL request part
        type: AccessTypes.AccessQuery
        example: !include examples/accessObjectQuery.json
    responses:
      200:
        description: Returns the list of Objects matching the DSL query
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/accessObjectResponse.json
          application/zip:
            description: Metadata and Binary object(s)
          application/x-tar:
            description: Metadata and Binary object(s)
          application/octet-stream:
            description: Binary object
      206:
        description: Returns the list of Objects matching the DSL query, using Cursor
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/accessObjectResponse.json

  AccessUniqueObjectQualifierHeadResponse:
    description: Response model for Object collection under Units collection in access or direct access to get one specific Qualifier version
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.StandardHeader204, StandardTraits.StandardHeader404]
    headers:
      X-Qualifier?:
        type: AccessTypes.Qualifiers
        description: |
         The requested qualifier only when used with Accept: application/octet-stream or application/zip or application/x-tar.
         If the qualifier is missing, it means the Dissemination.
         Extra qualifier "All" means all Qualifiers in conjunction with application/zip or application/x-tar for GET (HEAD allows all).
         **ONLY VALID with Accept application/octet-stream, application/zip or application/x-tar**
      X-Version?:
        type: integer
        description: |
          The rank of the version only when used with Accept: application/octet-stream or application/zip or application/x-tar. If the rank is missing, it means the last version.
          Extra qualifier "All" means all Qualifiers and all Versions in conjunction with application/zip or application/x-tar for GET (HEAD allows all).
          **ONLY VALID with Accept application/octet-stream, application/zip or application/x-tar**
    responses:
      204:
        headers:
          X-Qualifier?:
            type: AccessTypes.Qualifiers
            description: |
             The requested qualifier only when used with Accept: application/octet-stream or application/zip or application/x-tar.
             If the qualifier is missing, it means the Dissemination.
             Extra qualifier "All" means all Qualifiers in conjunction with application/zip or application/x-tar for GET (HEAD allows all).
             **ONLY VALID with Accept application/octet-stream, application/zip or application/x-tar**
          X-Version?:
            type: integer
            description: |
              The rank of the version only when used with Accept: application/octet-stream or application/zip or application/x-tar. If the rank is missing, it means the last version.
              Extra qualifier "All" means all Qualifiers and all Versions in conjunction with application/zip or application/x-tar for GET (HEAD allows all).
              **ONLY VALID with Accept application/octet-stream, application/zip or application/x-tar**


  AccessUniqueObjectQualifierResponse:
    description: Response model for Object collection under Units collection in access or direct access to get one specific Qualifier version
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    responses:
      200:
        description: Returns the list of 1 Object matching the DSL query
        headers:
          X-Qualifier?:
            type: AccessTypes.Qualifiers
            description: |
             The requested qualifier only when used with Accept: application/octet-stream or application/zip or application/x-tar.
             If the qualifier is missing, it means the Dissemination.
             Extra qualifier "All" means all Qualifiers in conjunction with application/zip or application/x-tar for GET (HEAD allows all).
             **ONLY VALID with Accept application/octet-stream, application/zip or application/x-tar**
          X-Version?:
            type: integer
            description: |
              The rank of the version only when used with Accept: application/octet-stream or application/zip or application/x-tar. If the rank is missing, it means the last version.
              Extra qualifier "All" means all Qualifiers and all Versions in conjunction with application/zip or application/x-tar for GET (HEAD allows all).
              **ONLY VALID with Accept application/octet-stream, application/zip or application/x-tar**
        body:
          application/zip:
            description: Metadata and Binary object(s)
          application/x-tar:
            description: Metadata and Binary object(s)
          application/octet-stream:
            description: Binary object

  AccessUniqueObjectResponse:
    description: Response model for Object collection under Units collection in access
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    body:
      application/json?:
        description: Body contains in JSON format the VITAM DSL request part if any (may be absent, meaning access to this Object)
        type: AccessTypes.AccessQuery
        example: !include examples/accessObjectQuery.json
    responses:
      200:
        description: Returns the list of 1 or many Object result according to DSL query
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/access1ObjectResponse.json
          application/zip:
            description: Metadata and Binary object(s)
          application/x-tar:
            description: Metadata and Binary object(s)
          application/octet-stream:
            description: Binary object

  AccessUpdateUnitResponse:
    description: Response model for Update Unit under Units collection in access
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader200,
          StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    body:
      application/json?:
        description: Body contains in JSON format the VITAM DSL request part for Update action
        type: AccessTypes.AccessQuery
        example: !include examples/access1UnitUpdateQuery.json
    responses:
      200:
        description: Returns the list of 1 or many Object result according to DSL query
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/access1UnitUpdateResponse.json

  AccessDeleteUnitResponse:
    description: Response model for delete for one Unit
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader204,
          StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    body:
      application/json?:
        description: Body contains in JSON format the VITAM DSL request part for Update action
        type: AccessTypes.AccessQuery
        example: !include examples/access1UnitUpdateQuery.json

  CreateOrSelectUnitResponse:
    description: Response model for Units creation
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.PaginationRequestHeader,  StandardTraits.PaginationNextHeader,  StandardTraits.PaginationResponseHeader,
      StandardTraits.StandardHeader200, StandardTraits.StandardHeader206,
      StandardTraits.StandardHeader201,       StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
      StandardTraits.StandardHeader409, StandardTraits.StandardHeader412 ]
    body:
      application/json:
        description: Body contains in JSON format the VITAM DSL request part in create or select mode
        type: AccessTypes.AccessQuery
        example: !include examples/accessUnitQuery.json
    responses:
      200:
        description: Returns the list of Units results
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/accessUnitResponse.json
          application/zip:
            description: Metadata and Binary object(s)
          application/x-tar:
            description: Metadata and Binary object(s)
          application/octet-stream:
            description: Binary object
      206:
        description: Returns the list of Units results using Cursor
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/accessUnitResponse.json
      201:
        description: Returns the Unit created as a list of 1
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/accessUnitResponse.json


  AccessUpdateObjectResponse:
    description: Response model for Update ObjectGroup under ObjectGroup collection in access
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader200,
          StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    body:
      application/json:
        description: Body contains in JSON format the VITAM DSL request part for Update action
        type: AccessTypes.AccessQuery
        example: !include examples/access1UnitUpdateQuery.json
    responses:
      200:
        description: Returns the list of 1 or many Object result according to DSL query
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/access1UnitUpdateResponse.json

  AccessDeleteObjectResponse:
    description: Response model for delete for one ObjectGroup
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader204,
          StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    body:
      application/json?:
        description: Body contains in JSON format the VITAM DSL request part for Update action
        type: AccessTypes.AccessQuery
        example: !include examples/access1UnitUpdateQuery.json

  CreateOrSelectObjectResponse:
    description: Response model for ObjectGroup creation
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.PaginationRequestHeader,  StandardTraits.PaginationNextHeader,  StandardTraits.PaginationResponseHeader,
      StandardTraits.StandardHeader200, StandardTraits.StandardHeader206,
      StandardTraits.StandardHeader201,       StandardTraits.StandardHeader401, StandardTraits.StandardHeader404,
      StandardTraits.StandardHeader409, StandardTraits.StandardHeader412 ]
    body:
      application/json:
        description: Body contains in JSON format the VITAM DSL request part in create or select mode
        type: AccessTypes.AccessQuery
        example: !include examples/accessUnitQuery.json
    responses:
      200:
        description: Returns the list of ObjectGroup results
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/accessUnitResponse.json
          application/zip:
            description: Metadata and Binary object(s)
          application/x-tar:
            description: Metadata and Binary object(s)
          application/octet-stream:
            description: Binary object
      206:
        description: Returns the list of ObjectGroup results using Cursor
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/accessUnitResponse.json
      201:
        description: Returns the ObjectGroup created as a list of 1
        body:
          application/json:
            description: Metadata
            type: AccessTypes.AccessResponse
            example: !include examples/accessUnitResponse.json

  AccessUnitRawResponse:
    description: Response model for raw Units collection in access
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader200, 
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    responses:
      200:
        description: Returns the list of Units results containing one result
        body:
          application/json:
            description: Metadata
            example: !include examples/accessUnitRawResponse.json

  AccessObjectRawResponse:
    description: Response model for raw Objects collection in access
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader200, 
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    responses:
      200:
        description: Returns the list of Objects results containing one result
        body:
          application/json:
            description: Metadata
            example: !include examples/accessObjectRawResponse.json

  TransferReplyResponseAsync:
    description: Requête de transfert reply
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader202 ]
    body:
      application/json:
        description: Body contient la requête ayant un DSL **multiple** et d'autres paramètres au format JSON.
        type: AccessTypes.TransferRequest
    responses:
      202:
        description: |
          Renvoie le statut de l'opération de Transfer
        body:
          application/json:
            description: Operation de Transfer acceptée
            type: StandardTypes.AsyncStatus
            example: !include examples/transfer.json
      500:
        description: Renvoie ce statut en cas d'erreur interne
        body:
          application/json:
            description: Internal server error