#%RAML 1.0 Library

usage: |
  Use to define global headers for Collect
uses:
  StandardTypes: StandardTypes.raml
  StandardTraits: StandardTraits.raml
  CollectTypes: CollectTypes.raml

traits:

  TransactionResponse:
    description: Request that will return the response model for Collect listing
    is: [ StandardTraits.StandardOptionalHeader,
      StandardTraits.PaginationRequestHeader,StandardTraits.StandardHeader401,
       StandardTraits.StandardHeader404, StandardTraits.StandardHeader412,  ]
    body:
      application/json:
        description: Body containing a Json object
        type: CollectTypes.TransactionRequest
    responses:
      200:
        description: Returns the saved transaction
        body:
          application/json:
            description: Saved transaction
            type: CollectTypes.TransactionResponse

  CollectUnitWithInheritedRulesResponse:
    description: Response model for units with inherited rules in collect
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.StandardHeader200, StandardTraits.StandardHeader400,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader403, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    body:
      application/json:
        description: Contient la requête DSL multiple au format JSON.
        type: AccessTypes.AccessMultipleQuery
    responses:
      200:
        description: Renvoie la liste des résultats d'Unités d'archives correspondant à la requête DSL ainsi que leurs règles héritées.
        body:
          application/json:
            description: Réponse DSL multiple pour Access contenant les métadonnées des Unités d'archives ainsi que leurs règles héritées.
            type: AccessTypes.AccessMultipleResponse
            example: !include examples/collectUnitWithInheritedRulesResponse.json

  ProjectResponse:
    description: Request that will return the response model for a collect project
    is: [ StandardTraits.StandardOptionalHeader,
      StandardTraits.PaginationRequestHeader,StandardTraits.StandardHeader401,
       StandardTraits.StandardHeader404, StandardTraits.StandardHeader412,  ]
    responses:
      200:
        description: get selected project
        type: CollectTypes.ProjectResponse
