#%RAML 1.0 Library

usage: |
  Use to define global types for Logbook

uses:
    StandardTypes: StandardTypes.raml
    DslTypes: DslTypes.raml

#Pour le moment, LogbookResponse est générique (operations, unitlifecycle, objectlifecycle) mais
#à l'avenir, il conviendra certainement de gérer plusieurs type
types:
  LogbookOperation:
    description: Logbook Operation schema
    properties:
      eventIdentifier:
        description: GUID of this particular event
        type: string
      eventType:
        description: Enum among several task ids
        type: string
      eventDateTime:
        type: datetime
      eventIdentifierProcess:
        description: GUID of this operation (primary key)
        type: string
      eventTypeProcess:
        type: string
        enum: [Ingest, Access, Query, Freeze, Destruction, Audit, Preservation, Platform, Internal]
      outcome :
        type: string
        enum: [ STARTED, OK, WARNING, KO, FATAL ]
      eventOutcomeDetail:
        description: Vitam Code using HTTPSTATUS_VITAMCODE
        type: string
      eventOutcomeDetailMessage:
        description: Information ouput related to this log entry
        type: string
      agentIdentifier:
        description: Agent from which this entry is set
        type: string
      agentIdentifierApplication:
        description: Application from which this eventProces is requested
        type: string
      agentIdentifierApplicationSession:
        description: Application Session ID from which this eventProces is requested
        type: string
      eventIdentifierRequest:
        description: Internal Vitam Session ID from which this eventProces is requested
        type: string
      agentIdentifierSubmission:
        description: Submission Agency from which this eventProces is requested
        type: string
      agentIdentifierOriginating:
        description: Originating Agency from which this eventProces is requested
        type: string
      objectIdentifier:
        description: Id of the item on which the operation is (For Entry objectIdentifier = GUID of SIP)
        type: string
      objectIdentifierRequest:
        description: Request that select the various items on which the operation is (for operations occuring on a select query)
        type: string
      objectIdentifierIncome:
        description: Id from SEDA as MessageIdentifier
        type: string

  LogbookResponse:
    description: Logbook Response
    properties:
      $hits:
        description: Contains the hits for the response
        required: true
        type: object
        properties:
          total:
            description: Total estimated possible answears
            type: integer
          offset:
            description: Offset on possible answears
            type: integer
          limit:
            description: Limit specified in the request (or implicit) from Offset
            type: integer
          size:
            description: Number of currently returned answears
            type: integer
          time_out?:
            description: True means the request was too long and so only partial result could be retrieved
            type: boolean
      $context:
        required: true
        description: Contains Request related to this to reply
        type: DslTypes.DslQuery
      $results:
        required: true
        description: Contains list of items
        type: object[]
