#%RAML 1.0 Library

usage: |
  Use to define global headers for Storage
uses:
  StorageTypes: StorageTypes.raml

traits:
  StrategyStorage:
    displayName: Storate Strategy id
    description: Storage Strategy Id
    headers:
      X-Strategy-Id:
        description: Identifiant de la Stratégie pour Offres de stockage et Copies (conservation)
        type: string
        required: true
  StrategyStorageCheck:
    displayName: StrategyStorageCheck
    description: Strategy Storage Check
    headers:
      X-Tenant-Id:
        type: number
        required: true
        description: Identifiant unique du tenant
        example: 0
      X-digest:
        type: string
        required: false
        description: Empreinte du digest - Requis pour la validation digest
      X-digest-algorithm:
        type: string
        required: false
        description: Algorithme du digest - Requis pour la validation digest
  StorageLog:
    description: Model for storage log
    body:
      application/json:
        description: query for storage log
        type: StorageTypes.StorageLogQuery
        example: !include examples/sampleStorageLogRequest.json
    responses:
      200:
        description: Storage logs
        body:
          application/json:
            example: !include examples/sampleStorageLogResponse.json
