---

- include_tasks: prometheus_mongodb_exporter_enabled.yml
  when: prometheus.mongodb_exporter.enabled | default(true) | bool

- include_tasks: prometheus_mongodb_exporter_disabled.yml
  when: not prometheus.mongodb_exporter.enabled | default(true) | bool
