---

#### Installation ####
- name: Install vitam-mongodb-exporter package
  package:
    name: vitam-mongodb-exporter
    state: latest
  register: result
  retries: "{{ packages_install_retries_number | default(1) }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay | default(10) }}"

#### mongoc ####
- name: Deploy systemd service file for vitam-mongoc-exporter
  template:
    src: vitam-mongoc-exporter.service.j2
    dest: "{{ '/lib/systemd/system' if ansible_distribution == 'Debian' else '/usr/lib/systemd/system' }}/vitam-mongoc-exporter.service"
    owner: root
    group: root
    mode: "0644"
  notify: "prometheus-mongoc-exporter - restart service"
  when: inventory_hostname in groups['hosts_mongoc_data'] or inventory_hostname in groups['hosts_mongoc_offer']

#### mongod ####
- name: Deploy systemd service file for vitam-mongod-exporter
  template:
    src: vitam-mongod-exporter.service.j2
    dest: "{{ '/lib/systemd/system' if ansible_distribution == 'Debian' else '/usr/lib/systemd/system' }}/vitam-mongod-exporter.service"
    owner: root
    group: root
    mode: "0644"
  notify: "prometheus-mongod-exporter - restart service"
  when: inventory_hostname in groups['hosts_mongod_data'] or inventory_hostname in groups['hosts_mongod_offer']

#### Configuration ####
- name: Check that mongodb_exporter directories exist
  file:
    path: "{{ vitam_defaults.folder.root_path | default('/vitam') }}/{{ item }}/mongodb_exporter"
    state: directory
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ vitam_defaults.folder.folder_permission | default('0750') }}"
  with_items:
    - app
    - bin
    - conf
    - lib
    - log
    - data
    - tmp

#### mongodb configuration ####
- name: Ensure mongodb config dir is OK
  file:
    path: "{{ prometheus_mongodb_exporter_config_path }}"
    state: directory
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ vitam_defaults.folder.folder_permission | default('0750') }}"

# Ensure that the installation is complete
- meta: flush_handlers

#### mongoc ####
- name: Ensure vitam-mongoc-exporter service is started
  service:
    name: vitam-mongoc-exporter
    state: started
    enabled: "{{ prometheus.mongodb_exporter.at_boot | default(service_at_boot) }}"
  when: inventory_hostname in groups['hosts_mongoc_data'] or inventory_hostname in groups['hosts_mongoc_offer']

#### mongod ####
- name: Ensure vitam-mongod-exporter service is started
  service:
    name: vitam-mongod-exporter
    state: started
    enabled: "{{ prometheus.mongodb_exporter.at_boot | default(service_at_boot) }}"
  when: inventory_hostname in groups['hosts_mongod_data'] or inventory_hostname in groups['hosts_mongod_offer']

#### mongoc ####
- name: Wait for mongodb_exporter port {{ prometheus.mongodb_exporter.port_mongoc | default(9216) }} to be open
  wait_for:
    host: "{{ ip_admin }}"
    port: "{{ prometheus.mongodb_exporter.port_mongoc | default(9216) }}"
    state: "started"
    timeout: "{{ vitam_defaults.services.start_timeout | default(300) }}"
  when: inventory_hostname in groups['hosts_mongoc_data'] or inventory_hostname in groups['hosts_mongoc_offer']

#### mongod ####
- name: Wait for mongodb_exporter port {{ prometheus.mongodb_exporter.port_mongoc | default(9217) }} to be open
  wait_for:
    host: "{{ ip_admin }}"
    port: "{{ prometheus.mongodb_exporter.port_mongod | default(9217) }}"
    state: "started"
    timeout: "{{ vitam_defaults.services.start_timeout | default(300) }}"
  when: inventory_hostname in groups['hosts_mongod_data'] or inventory_hostname in groups['hosts_mongod_offer']
