#########################################################################################
# Dockerfile to build vitam and run on one server
# Based on Debian
#
# Maintained by Vitam Integration Team
# Image name: vitam/dev-deb-base
#########################################################################################

# Set the base image to Debian 12.5
FROM debian:12.5

MAINTAINER French Prime minister Office/SGMAP/DINSIC/Vitam Program <contact.vitam@culture.gouv.fr>

#ENV DEBIAN_FRONTEND noninteractive

RUN apt-get clean && apt-get update && apt-get install -y apt-utils procps init

# Make sure the package repository and packages are up to date.

COPY deb/bookworm-backports.list /etc/apt/sources.list.d/

RUN apt-get clean && apt-get update && apt-get upgrade -y

RUN apt-get remove -y openjdk*

RUN apt-get update && apt-get install -y openjdk-21-jdk-headless

#RUN apt-get install -y systemd-sysv

################################  Configure systemd  ###############################

# Hint for systemd that we are running inside a container
ENV container docker
ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y systemd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup* \
    /lib/systemd/system/systemd-update-utmp*

################################  Install build tools (rpm / maven / java)  ###############################

RUN apt-get clean && apt-get update && apt-get install -y openssl curl sudo net-tools git vim unzip wget gawk && apt-get clean

# to bypass the "trustAnchors parameter must be non-empty" problem
# See http://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty
RUN /var/lib/dpkg/info/ca-certificates-java.postinst configure

RUN apt-get clean && apt-get update && apt-get install -y curl && apt-get clean

# Add Java to path
ENV JAVA_HOME /usr/lib/jvm/java-21-openjdk-amd64

# Install & configure maven
RUN curl -k https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.7/apache-maven-3.8.7-bin.tar.gz --output /tmp/maven.tgz \
   && tar xvzf /tmp/maven.tgz --directory /opt \
   && rm -f /tmp/maven.tgz \
   && ln -s /opt/apache-maven-3.8.7 /opt/maven \
   && mkdir -p /devhome/.m2 \
   && chmod -R 777 /devhome

# Add Maven & java to path
ENV M2_HOME /opt/maven
ENV PATH ${M2_HOME}/bin:${JAVA_HOME}/bin:${PATH}

################################  Install ansible  ###############################
# for sudo in automatic deployment ; note : ansible needs epel repo

RUN apt-get install -y golang

RUN apt-get install -y node-gyp  libnode-dev && \
    apt-get install -y nodejs
# symbolic link is not necessary anymore
# RUN apt-get -y install ansible

##################################  Declare local deb repo  #################################

# Note : declare at the end ; else other commands will fail.
RUN apt-get update && apt-get install -y  dpkg-dev gnupg2 \
    && apt-get clean

COPY deb/ansible.list /etc/apt/sources.list.d/ansible.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 93C4A3FD7BB9C367
RUN apt-get clean && apt-get update && apt-get install -y ansible

COPY deb/local.list /etc/apt/sources.list.d/local.list

RUN apt-get update && apt-get install -y  dpkg-dev gnupg2 locales \
    && apt-get clean

RUN echo "LC_ALL=en_US.UTF-8" >> /etc/environment && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    echo "LANG=en_US.UTF-8" > /etc/locale.conf && \
    export LC_ALL=en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    export LANGUAGE=en_US.UTF-8 && \
    locale-gen en_US.UTF-8 \

################################## Add dev helpers #################################

RUN ln -s \
    /code/dev-deployment/dev-base/deb/profile-build-repo.sh \
    /code/dev-deployment/dev-base/profile-prompt-usage.sh \
    /etc/profile.d/
COPY .bashrc /devhome
COPY vitam-usage.txt /etc/
COPY deb/sudo-nopwd /etc/sudoers.d/
RUN chmod 664 /etc/sudoers.d/sudo-nopwd

ENV TERM xterm

# If we don't install openjdk a 2nd time, sometimes it doesn't work, why ???
RUN apt-get install -y openjdk-21-jdk-headless

##################################  CONTAINER SETTINGS  #################################

VOLUME [ "/sys/fs/cgroup" ]
VOLUME [ "/code" ]
VOLUME [ "/devhome/.m2" ]

#ENV DEBIAN_FRONTEND teletype

# System tuning for elasticsearch
RUN echo "vm.max_map_count = 262144" >> /etc/sysctl.conf

RUN ln -s \
    /code/dev-deployment/dev-base/deb/vitam-build-griffins \
    /code/dev-deployment/dev-base/deb/vitam-build-repo \
    /code/dev-deployment/dev-base/deb/vitam-maven-build-only \
    /code/dev-deployment/dev-base/deb/vitam-recreate-repo \
    /code/dev-deployment/dev-base/vitam-bench-ingest \
    /code/dev-deployment/dev-base/vitam-command \
    /code/dev-deployment/dev-base/vitam-deploy \
    /code/dev-deployment/dev-base/vitam-deploy-extra \
    /code/dev-deployment/dev-base/vitam-mongo-cli \
    /code/dev-deployment/dev-base/vitam-mongo-cli-rs \
    /code/dev-deployment/dev-base/vitam-redeploy \
    /code/dev-deployment/dev-base/vitam-redeploy-extra \
    /code/dev-deployment/dev-base/vitam-restart \
    /code/dev-deployment/dev-base/vitam-start \
    /code/dev-deployment/dev-base/vitam-stop \
    /usr/bin/

WORKDIR /code

# Entry Point to systemd init
CMD ["/sbin/init"]
