#########################################################################################
# Dockerfile to run vitam on one server
# Based on AlmaLinux
#
# Maintained by Vitam Integration Team
# Image name: vitam/jenkins-slave-base
#########################################################################################

# Set the base image to almalinux/9-base
FROM almalinux/9-base
MAINTAINER French Prime minister Office/SGMAP/DINSIC/Vitam Program <contact.vitam@culture.gouv.fr>

# Make sure the package repository and packages are up to date.
RUN dnf install -y epel-release && dnf -y update && dnf -y upgrade && dnf clean all

################################  Configure systemd  ###############################

# Hint for systemd that we are running inside a container
ENV container docker

# Remove useless units
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*; \
    rm -f /etc/systemd/system/*.wants/*; \
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*; \
    rm -f /lib/systemd/system/anaconda.target.wants/*;

################################  Install build tools (rpm / maven / java)  ###############################

RUN yum remove -y java-11*

RUN dnf install -y \
        java-21-openjdk-devel \
        rpm-build \
        rpmdevtools \
        initscripts.x86_64 \
        golang \
        npm \
    && dnf clean all

# Add Java to path
ENV JAVA_HOME /usr/lib/jvm/java

# Install & configure maven
RUN curl -k https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.7/apache-maven-3.8.7-bin.tar.gz --output /tmp/maven.tgz \
    && tar xvzf /tmp/maven.tgz --directory /opt \
    && rm -f /tmp/maven.tgz \
    && ln -s /opt/apache-maven-3.8.7 /opt/maven \
    && mkdir -p /devhome/.m2 \
    && chmod -R 777 /devhome

# Add Maven & java to path
ENV M2_HOME /opt/maven
ENV PATH ${M2_HOME}/bin:${JAVA_HOME}/bin:${PATH}

################################  Install deployment tools  ###############################

# for sudo in automatic deployment ; note : ansible needs epel repo
RUN dnf install -y sudo ansible openssl which && dnf clean all

##################################  install git and vim  #################################

RUN dnf install -y git vim && dnf clean all

##################################  Declare local rpm repo  #################################

# Note : declare at the end ; else other dnf commands will fail. Ideally, we would need a "createrepo" here, but it wouldn't work, as the volume /code is normally mounted externally.
RUN dnf install -y createrepo \
    && dnf clean all
COPY rpm/devlocal.repo /etc/yum.repos.d/devlocal.repo

################################## Add dev helpers #################################

RUN ln -s \
    /code/dev-deployment/dev-base/rpm/profile-build-repo.sh \
    /code/dev-deployment/dev-base/profile-prompt-usage.sh \
    /etc/profile.d/
COPY .bashrc /devhome
COPY vitam-usage.txt /etc
COPY rpm/wheel-nopwd /etc/sudoers.d
RUN chmod 664 /etc/sudoers.d/wheel-nopwd

# Disable fastestmirror ; helps gain several seconds per dnf invocation
COPY rpm/fastestmirror.conf /etc/yum/pluginconf.d

ENV TERM xterm


##################################  CONTAINER SETTINGS  #################################

VOLUME [ "/sys/fs/cgroup" ]
VOLUME [ "/code" ]
VOLUME [ "/devhome/.m2" ]

RUN dnf install -y --disablerepo=local selinux-policy selinux-policy-devel

# System tuning for elasticsearch
RUN echo "vm.max_map_count = 262144" >> /etc/sysctl.conf

RUN ln -s \
    /code/dev-deployment/dev-base/rpm/vitam-build-griffins \
    /code/dev-deployment/dev-base/rpm/vitam-build-repo \
    /code/dev-deployment/dev-base/rpm/vitam-deploy-cots \
    /code/dev-deployment/dev-base/rpm/vitam-maven-build-only \
    /code/dev-deployment/dev-base/rpm/vitam-recreate-repo \
    /code/dev-deployment/dev-base/vitam-bench-ingest \
    /code/dev-deployment/dev-base/vitam-command \
    /code/dev-deployment/dev-base/vitam-deploy \
    /code/dev-deployment/dev-base/vitam-deploy-extra \
    /code/dev-deployment/dev-base/vitam-mongo-cli \
    /code/dev-deployment/dev-base/vitam-mongo-cli-rs \
    /code/dev-deployment/dev-base/vitam-redeploy \
    /code/dev-deployment/dev-base/vitam-redeploy-extra \
    /code/dev-deployment/dev-base/vitam-restart \
    /code/dev-deployment/dev-base/vitam-start \
    /code/dev-deployment/dev-base/vitam-stop \
    /usr/bin/

WORKDIR /code

# Entry Point to systemd init
CMD ["/usr/sbin/init"]
