#!/usr/bin/env bash
# KWA Script : rebuild the entire repository.
echo "Building maven rpm..."
mvn clean package rpm:rpm -DskipTests
echo "Building platform rpm..."
pushd rpm/vitam-product ; ./build.sh vitam-user-vitam ; popd
pushd rpm/vitam-product ; ./build.sh vitam-user-vitamdb ; popd
pushd rpm/vitam-product ; ./build.sh vitam-consul ; popd
pushd rpm/vitam-product ; ./build.sh vitam-siegfried ; popd
pushd rpm/vitam-external ; ./build_repo.sh ; popd

echo "Creating local yum repository..."
createrepo -x '.git/*' .
echo "Cleaning up yum cache..."
yum clean all
echo "Done ! Available rpm packages in local vitam-product repository :"
yum --disablerepo="*" --enablerepo="local" list available
echo "Build done ! Now you can deploy VITAM: vitam-deploy [local|fulllocal]"
