#%RAML 1.0 Library

usage: |
  Use to define global types for Access

uses:
    DslTypes: DslTypes.raml
    BatchUpdateTypes: BatchUpdateTypes.raml

types:
  AccessMultipleQuery:
      type: DslTypes.DslMultipleQuery
      displayName: Requête DSL multiple pour Access
      description: Requête DSL multiple Vitam externe pour Access
      example: !include examples/accessUnitQuery.json

  AccessMultipleQueryWithPrecisionForUnit:
      type: DslTypes.DslMultipleQueryForMetadata
      displayName: Requête DSL multiple pour Access
      description: Requête DSL multiple Vitam externe pour Access
      example: !include examples/accessUnitQuery.json

  AccessMultipleQueryWithPrecisionForGot:
      type: DslTypes.DslMultipleQueryForMetadata
      displayName: Requête DSL multiple pour Access
      description: Requête DSL multiple Vitam externe pour Access
      example: !include examples/accessGotQuery.json

  AccessStreamMultipleQuery:
      type: DslTypes.DslStreamMultipleQuery
      displayName: Requête DSL multiple pour Access
      description: Requête DSL multiple Vitam externe pour Access
      example: !include examples/accessStreamUnitQuery.json

  AccessStreamResponse:
      type: DslTypes.JsonListResponse
      displayName: Requête DSL multiple pour Access
      description: Requête DSL multiple Vitam externe pour Access
      example: !include examples/streamUnitResponse.jsonl

  EliminationRequest:
      displayName: Requête DSL multiple de traitement de masse pour élimination
      description: Requête DSL multiple Vitam de traitement de masse pour élimination
      type: object
      properties:
        dslRequest:
          description: Contient la requête de recherche
          type: DslTypes.DslBatchProcessionQuery
        date:
          description: La date d'élimination
          type: string
      example:
        {
           "dslRequest": {
             "$roots": [ "id0" ],
             "$query": [
               {
                 "$match": { "title": "titre" },
                 "$depth": 4
               }
             ],
             "$threshold": 10000
           },
           "date": "2018-01-23"
        }

  EliminationResponse:
      displayName: Requête DSL multiple de traitement de masse pour élimination
      description: Requête DSL multiple Vitam de traitement de masse pour élimination
      type: object
      properties:
        httpCode:
          description: Http status code la reponse
          type: integer
      example:
        {
           "httpCode" : 202
        }

  PreservationRequest:
      displayName: Requête DSL multiple de traitement de masse pour la préservation
      description: Requête DSL multiple de traitement de masse pour la préservation
      type: object
      properties:
        dslQuery:
          description: Contient la requête de recherche
          type: DslTypes.DslBatchProcessionQuery
        scenarioId:
          description: L'identifiant du scénario de préservation
          type: string
        targetUsage:
          description: usage du binaire générer
          type: string
        sourceUsage:
          description: usage du binaire cible
          type: string
        version:
          description: La version du binaire sur lequel on veux opérer une action de préservation
          type: string
      example:
        {
          "dslQuery" : {
            "$roots": [],
            "$query": [
              {
                "$eq": {
                  "#id": "aeaqaaaaaaezyoa6abacealifcom6xyaaaaq"
                }
              }
            ],
            "$threshold": 40
           },
          "scenarioId" : "PSC-000001",
          "targetUsage": "BinaryMaster",
          "sourceUsage": "BinaryMaster",
          "version": "FIRST"
        }

  PreservationResponse:
      displayName: Requête DSL multiple de traitement de masse pour la préservation
      description: Requête DSL multiple de traitement de masse pour la préservation
      type: object
      properties:
        httpCode:
          description: Http status code la reponse
          type: integer
      example:
        {
        "httpCode" : 202
        }

  UnitBatchUpdateRequest:
    displayName: Requête de lancement du traitement de masse pour mise à jour des métadonnées des AU
    description: Requête de lancement du traitement de masse pour mise à jour des métadonnées des AU
    type: object
  UnitBatchRuleUpdateRequest:
    displayName: Requête de lancement du traitement de masse pour mise à jour des métadonnées de gestion des AU
    description: Requête de lancement du traitement de masse pour mise à jour des métadonnées de gestion des AU
    type: object
    properties:
      dslRequest:
        description: Contient la requête de recherche
        type: object
      ruleActions:
        description: |
          Contient le POJO de mise à jour des métadonnées de gestion (Voir exemple).

          Il est possible d'ajouter (add), mettre à jour (update) ou supprimer (delete) des catégories de règles de gestion (règles et propriétés), ainsi que de mettre à jour les métadonnées de gestion hors catégories de règles (addOrUpdateMetadata/deleteMetadata).

          Pour les catégories de règles de gestion, voici les champs autorisés à la racine des catégories (règles et propriétés):

          | Champ                         | Catégorie spécifique       | Commentaire                                                                                                |
          |-------------------------------|----------------------------|------------------------------------------------------------------------------------------------------------|
          | Rules                         | Toutes                     | Permet de définir les modifications sur les règles de gestion de l'unité archivistique                     |
          | PreventInheritance            | Toutes                     | Permet de définir si la catégorie hérite (false) ou non (true) des règles de l'unité archivistique parente |
          | PreventRulesId                | Toutes                     | Permet de définir une liste de règles qui ne seront pas hérités de l'unité archivistique parente           |
          | FinalAction                   | StorageRule, AppraisalRule | Permet de définir le sort final de la catégorie (valeurs spécifiques selon la catégorie)                   |
          | ClassificationLevel           | ClassificationRule         | Permet de définir le niveau de classification                                                              |
          | ClassificationOwner           | ClassificationRule         | Permet de définir le service émetteur                                                                      |
          | ClassificationAudience        | ClassificationRule         | Permet de définir le champ de diffusion                                                                    |
          | ClassificationReassessingDate | ClassificationRule         | Permet de définir la date de réévaluation                                                                  |
          | NeedReassessingAuthorization  | ClassificationRule         | Permet de définir si les modifications sont soumises (true) ou non (false) à validation humaine            |

          Pour les règles de gestion, voici les champs autorisés dans le tableau de règles (champ Rules) d'une catégorie

          | Champ                      | Catégorie spécifique | Contraintes                                 | Commentaire                                                                                                          |
          |----------------------------|----------------------|---------------------------------------------|----------------------------------------------------------------------------------------------------------------------|
          | OldRule                    | Toutes               | update, obligatoire                         | Permet de définir l'identifiant de règle que l'on veut modifier                                                      |
          | Rule                       | Toutes               | add/delete, obligatoire; update, facultatif | Permet de définir l'identifiant de la règle que l'ont veut ajouter/supprimer ou de celle remplaçant l'ancienne règle |
          | StartDate                  | Toutes               | add/update, facultatif                      | Permet de définir la date de début de la règle ajoutée/modifiée                                                      |
          | DeleteStartDate            | Toutes               | update, facultatif                          | Permet de supprimer (true) la date de début de la règle à mettre à jour                                              |
          | HoldEndDate                | HoldRule             | add/update, facultatif                      | Permet de définir la date de fin de gel explicite.                                                                   |
          | DeleteHoldEndDate          | HoldRule             | update, facultatif                          | Permet de supprimer (true) la date de fin de gel explicite.                                                          |
          | HoldOwner                  | HoldRule             | add/update, facultatif                      | Permet de définir le propriétaire de la demande de gel.                                                              |
          | DeleteHoldOwner            | HoldRule             | update, facultatif                          | Permet de supprimer (true) le propriétaire de la demande de gel.                                                     |
          | HoldReason                 | HoldRule             | add/update, facultatif                      | Permet de définir le motif de la demande de gel.                                                                     |
          | DeleteHoldReason           | HoldRule             | update, facultatif                          | Permet de supprimer (true) le motif de la demande de gel.                                                            |
          | HoldReassessingDate        | HoldRule             | add/update, facultatif                      | Permet de définir la date de réévaluation du gel.                                                                    |
          | DeleteHoldReassessingDate  | HoldRule             | update, facultatif                          | Permet de supprimer (true) la date de réévaluation du gel.                                                           |
          | PreventRearrangement       | HoldRule             | add/update, facultatif                      | Permet de définir si le blocage de la reclassification est activé (true) ou non (false).                             |
          | DeletePreventRearrangement | HoldRule             | update, facultatif                          | Permet de supprimer (true) le blocage de la reclassification.                                                        |
        type: object
    example: !include examples/unitBatchUpdate.json
  
  BulkAtomicUpdateRequest:
    displayName: Requête de lancement du traitement de masse pour mise à jour unitaire des métadonnées des AU
    description: Requête de lancement du traitement de masse pour mise à jour unitaire des métadonnées des AU
    type: object
    properties:
      threshold?:
        description: Contient le seuil du traitement en masse unitaire en nombre de queries (optionnel)
        type: integer
        required: false
        minimum: 1
        maximum: 100000000
      queries:
        description: Contient la liste des requêtes de mise à jour unitaire des métadonnées
        type: array
        items:
          type: DslTypes.DslAtomicUpdateQuery

  AccessMultipleResponse:
    type: DslTypes.DslMultipeResponse
    displayName: Réponse DSL multiple pour Access
    description: Réponse DSL mutiple Vitam externe pour Access

  AccessGetByIdQuery:
      type: DslTypes.DslGetByIdQuery
      displayName: Requête DSL unitaire pour Access
      description: Requête DSL unitaire Vitam externe pour Access

  AccessGetByIdResponse:
    type: DslTypes.DslGetByIdResponse
    displayName: Réponse DSL unitaire pour Access
    description: Réponse DSL unitaire Vitam externe pour Access

  AccessUpdateByIdQuery:
      type: DslTypes.DslUpdateByIdQuery
      displayName: Requête DSL unitaire de modification pour Access
      description: Requête DSL unitaire de modification Vitam externe pour Access

  AccessUpdateByIdResponse:
    type: DslTypes.DslUpdateByIdResponse
    displayName: Réponse DSL unitaire de modification pour Access
    description: Réponse DSL unitaire de modification Vitam externe pour Access

  X-Qualifiers:
    description: |
      Qualifiers for Objects. For the moment, only the number version of each qualifier is returned. (see examples)
    type: string
    enum:
      - PhysicalMaster
      - BinaryMaster
      - Dissemination
      - Thumbnail
      - TextContent

  DipRequest:
      displayName: Requête pour faire un export DIP
      description: Requête pour faire un export DIP
      type: object
      properties:
        dipExportType:
          description: Le type d'export DIP
          type: string
          enum: [MINIMAL, FULL]
          required: true
        exportWithLogBookLFC:
          description: True pour inclure les logbook de cycle de vie des unités archivistiques et groupes d'objets
          type: boolean
          required: false
        dslRequest:
          description: Contient la requête de recherche
          type: DslTypes.DslMultipleQuery
          required: true
        dataObjectVersionToExport:
          description: L'identifiant du scénario de préservation
          type: object
          required: false
          properties:
            dataObjectVersions:
              description: Liste des versions d'objets à inclure dans l'export
              type: array
              items:
                type: string
        dipRequestParameters:
          description: Les paramètres nécessaires pour faire un export DIP, ce champs est obligatoire quand le dipExportType est FULL
          type: object
          required: false
          properties:
            archivalAgreement:
              description: Contrat d'entrée
              type: string
              required: false
            originatingAgencyIdentifier:
              description: Identifiant du service producteur
              type: string
              required: false
            comment:
              description: Intitulé
              type: string
              required: false
            submissionAgencyIdentifier:
              description: Identifiant du service versant
              type: string
              required: false
            archivalAgencyIdentifier:
              description: Identifiant du service d'archives. Si Vitam trouve un seul service d'archives pour la selection d'unités archivistiques, ce service sera utilisé par défaut.
              type: string
              required: true
            messageRequestIdentifier:
              description: Identifiant de la demande
              type: string
              required: true
            requesterIdentifier:
              description: Identifiant du demandeur
              type: string
              required: true
            authorizationRequestReplyIdentifier:
              description: Identifiant de la réponse à une demande d'autorisation
              type: string
              required: false
        maxSizeThreshold:
          description: Le seuil du poids binaire max autorisé pour un DIP ou un SIP de transfert
          type: integer
          required: false
        sedaVersion:
          description: La version SEDA d'export de DIP ou d'un SIP de transfert ( 2.2 par défaut )
          type: string
          required: false
      example: !include examples/dipRequest.json

  TransferRequest:
      displayName: Requête pour faire un transfert
      description: Requête pour faire un transfert d'unités archivistiques
      type: object
      properties:
        transferWithLogBookLFC:
          description: True pour inclure les logbook de cycle de vie des unités archivistiques et groupes d'objets pour le transfert
          type: boolean
          required: false
        dslRequest:
          description: Contient la requête de recherche
          type: DslTypes.DslMultipleQuery
          required: true
        maxSizeThreshold:
          description: Le seuil du poids binaire max autorisé pour un DIP ou un SIP de transfert
          type: integer
          required: false
        dataObjectVersionToExport:
          description: L'identifiant du scénario de préservation
          type: object
          required: false
          properties:
            dataObjectVersions:
              description: Liste des versions d'objets à inclure dans l'export
              type: array
              items:
                type: string
        transferRequestParameters:
          description: Les paramètres nécessaires pour faire un transfert d'unités archivistiques
          type: object
          required: true
          properties:
            archivalAgreement:
              description: Contrat d'entrée
              type: string
              required: true
            originatingAgencyIdentifier:
              description: Identifiant du service producteur
              type: string
              required: true
            archivalAgencyIdentifier:
              description: Identifiant du service d'archives
              type: string
              required: true
            comment:
              description: Intitulé
              type: string
              required: false
            submissionAgencyIdentifier:
              description: Identifiant du service versant
              type: string
              required: false
            transferringAgency:
              description: Service versant
              type: string
              required: false
            transferRequestReplyIdentifier:
              description: Identifiant de la réponse à une demande de transfert
              type: string
              required: false
            relatedTransferReference:
              description: Référence à un transfert d'archives lié
              type: array
              required: false
              items:
                type: string
        sedaVersion:
          description: La version SEDA d'export de DIP ou d'un SIP de transfert ( 2.2 par défaut )
          type: string
          required: false
      example: !include examples/transferRequest.json

  DeleteGotVersionsRequest:
      displayName: Requête DSL multiple pour la suppression des versions des groupes d'objects
      description: Requête DSL multiple pour la suppression des versions des groupes d'objects
      type: object
      properties:
        DslQuery:
          description: Contient la requête de recherche
          type: DslTypes.DslBatchProcessionQuery
        UsageName:
          description: Le nom d'usage pour le groupe d'objet
          type: string
        SpecificVersions:
          description: Liste des versions des groupes d'objets à supprimer
          type: array
          items:
           type: integer
      example:
        {
          "dslQuery" : {
            "$roots": [],
            "$query": [
              {
                "$eq": {
                  "#id": "aeaqaaaaaaezyoa6abacealifcom6xyaaaaq"
                }
              }
            ],
            "$threshold": 40
           },
          "UsageName" : "BinaryMaster",
          "SpecificVersions": [2,3,4]
        }

  DeleteGotVersionsResponse:
      displayName: Requête DSL multiple pour la suppression des versions des groupes d'objets
      description: Requête DSL multiple pour la suppression des versions des groupes d'objets
      type: object
      properties:
        httpCode:
          description: Http status code la réponse
          type: integer
      example:
        {
        "httpCode" : 202
        }

  ObjectAccessRequestCreationResponse:
      displayName: Réponse d'une demande de création d'une demande d'accès pour l'objet
      description: |
        Réponse d'une demande de création d'une demande d'accès pour l'objet
        Si l'objet est persisté sur une offre de stockage « froide », une demande d'accès est créée et renvoyée.
        Si l'objet est persisté sur une offre de stockage « chaude », aucune demande d'accès n'est renvoyée.
      type: object
      properties:
        httpCode:
          description: Http status code la réponse
          type: integer
        $results:
          description: |
            Contient la demande d'accès à l'objet, si celle-ci a bien été créée.

            Si l'objet est persisté sur une offre de stockage « froide », une demande d'accès est renvoyée.
            Si l'objet est persisté sur une offre de stockage « chaude », aucune demande d'accès n'est renvoyée.
          type: array
          items:
            type: AccessRequestReference

  AccessRequestReference:
      displayName: Les références d'une demande d'accès d'une stratégie stockage « froide »
      description: Les références d'une demande d'accès d'une stratégie stockage « froide »
      type: object
      properties:
        accessRequestId:
          description: L'identifiant de la demande d'accès
          required: true
          type: string
        storageStrategyId:
          description: Stratégie de stockage associée à la demande d'accès
          required: true
          type: string
      example: {
        "accessRequestId": "aeaaaaaaaag5nq65ag2cgal54k3u7aqaaaaq",
        "storageStrategyId": "tape"
      }

  CheckAccessRequestStatusesRequest:
    displayName: Requête de vérification des statuts d'un lot de demandes d'accès
    description: |
      Liste (non vide, sans doublons) des demandes d'accès à vérifier.
    type: array
    items:
      type: AccessRequestReference
      example: [
        {
          "accessRequestId": "aeaaaaaaaag5nq65ag2cgal54mxefmqaaaaq",
          "storageStrategyId": "tape"
        },
        {
          "accessRequestId": "aeaaaaaaaahjpju4ab4wgal54rrp2vaaaaaq",
          "storageStrategyId": "tape"
        }
      ]

  CheckAccessRequestStatusesResponse:
      displayName: Résultat de vérification des statuts d'un lot de demandes d'accès
      description: |
        Résultat de vérification des statuts d'un lot de demandes d'accès

        À chaque demande d'accès en paramètre, un statut dans l'offre :
        - **READY** : La demande d'accès est prête.
        - **NOT_READY** : La demande d'accès est n'est pas encore prête.
        - **EXPIRED** : La demande d'accès a expiré
        - **NOT_FOUND** : La demande d'accès n'est pas trouvée (supprimée, purgée au bout d'un délais après expiration, non existante ou non visible depuis le contexte du tenant d'appel...)

      type: object
      properties:
        httpCode:
          description: Http status code la réponse
          type: integer
        $results:
          description: Statuts pour chaque demandes d'accès
          type: array
          items:
            type: StatusByAccessRequestReference

  StatusByAccessRequestReference:
      displayName: Le statut d'une demande d'accès sur stratégie stockage « froide »
      description: Le statut d'une demande d'accès sur stratégie stockage « froide »
      type: object
      properties:
        accessRequestReference:
          description: La demande d'accès concernée
          required: true
          type: AccessRequestReference
        accessRequestStatus:
          description: Le statut de la demande d'accès
          required: true
          type: string
          enum: ["READY", "NOT_READY", "EXPIRED", "NOT_FOUND"]
      example: {
        "accessRequestReference": {
          "accessRequestId": "aeaaaaaaaag5nq65ag2cgal54mxefmqaaaaq",
          "storageStrategyId": "tape"
        },
        "accessRequestStatus": "NOT_FOUND"
      }
