#%RAML 1.0 Library

usage: |
  Use to define global headers for Access
uses:
  StandardTypes: StandardTypes.raml
  StandardTraits: StandardTraits.raml
  AccessTypes: AccessTypes.raml

traits:

  AccessUnitResponse:
    description: Response model for Units collection in access
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.StandardHeader200, StandardTraits.StandardHeader400,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader403, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    headers:
      X-Access-Contract-Id:
        type: string
        required: true
    body:
      application/json:
        description: Contient la requête DSL multiple au format JSON.
        type: AccessTypes.AccessMultipleQuery
        example: !include examples/accessUnitQuery.json
    responses:
      200:
        description: Renvoie la liste des résultats d'Unités d'archives correspondant à la requête DSL
        body:
          application/json:
            description: Réponse DSL multiple pour Access contenant les métadonnées des Unités d'archives
            type: AccessTypes.AccessMultipleResponse
            example: !include examples/accessUnitResponse.json

  AccessUniqueUnitResponse:
    description: Response model for Unit item in access
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.StandardHeader200, StandardTraits.StandardHeader400,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader403, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    headers:
      X-Access-Contract-Id:
        type: string
        required: true
    body:
      application/json:
        description: Body contient la requête DSL unitaire au format JSON.
        type: AccessTypes.AccessGetByIdQuery
        example: !include examples/access1UnitQuery.json
    responses:
      200:
        description: Renvoie la liste de résultats contenant 1 Unité d'archive correspondant à la requête DSL
        body:
          application/json:
            description: Réponse DSL multiple pour Access contenant les métadonnées de l'Unité d'archive
            type: AccessTypes.AccessGetByIdResponse
            example: !include examples/access1UnitResponse.json


  AccessUnitWithInheritedRulesResponse:
    description: Response model for units with inherited rules in access
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.StandardHeader200, StandardTraits.StandardHeader400,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader403, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    headers:
      X-Access-Contract-Id:
        type: string
        required: true
    body:
      application/json:
        description: Contient la requête DSL multiple au format JSON.
        type: AccessTypes.AccessMultipleQuery
        example: !include examples/accessUnitQuery.json
    responses:
      200:
        description: Renvoie la liste des résultats d'Unités d'archives correspondant à la requête DSL ainsi que leurs règles héritées.
        body:
          application/json:
            description: Réponse DSL multiple pour Access contenant les métadonnées des Unités d'archives ainsi que leurs règles héritées.
            type: AccessTypes.AccessMultipleResponse
            example: !include examples/accessUnitWithInheritedRulesResponse.json

  AccessUniqueObjectQualifierResponse:
    description: Response model for Object collection under Units collection in access or direct access to get one specific Qualifier version
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.StandardHeader200, StandardTraits.StandardHeader400,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader403, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    headers:
      X-Qualifier?:
        type: string
        enum:
          - PhysicalMaster
          - BinaryMaster
          - Dissemination
          - Thumbnail
          - TextContent
        description: |
         L'usage est utilisée et obligatoire uniquement en présence de Accept: application/octet-stream.
         **ONLY VALID with Accept application/octet-stream**
      X-Version?:
        type: integer
        description: |
          La version est utilisée et obligatoire uniquement en présence de Accept: application/octet-stream.
          **ONLY VALID with Accept application/octet-stream**
      X-Access-Contract-Id:
        type: string
        required: true
    responses:
      200:
        description: Renvoie l'objet binaire (Returns the list of 1 Object matching the DSL query)
        headers:
          X-Qualifier?:
            type: AccessTypes.X-Qualifiers
            description: |
              L'usage est utilisée et obligatoire uniquement en présence de Accept: application/octet-stream.
              **ONLY VALID with Accept application/octet-stream**
          X-Version?:
            type: integer
            description: |
              La version est utilisée et obligatoire uniquement en présence de Accept: application/octet-stream.
              **ONLY VALID with Accept application/octet-stream**
        body:
          application/octet-stream:
            description: Objet binaire

  AccessGOTResponse:
    description: Réponse sur les groupes d'objets
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.StandardHeader200, StandardTraits.StandardHeader400,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader403, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    responses:
      200:
        description: Renvoie la liste de résultats correspondant à la requête DSL
        body:
          application/json:
            description: Résultats json correspondant à la requête DSL

  AccessUniqueObjectResponse:
    description: Response model for Object collection under Units collection in access
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AllowsHeader,
      StandardTraits.StandardHeader200, StandardTraits.StandardHeader400,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader403, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    headers:
      X-Access-Contract-Id:
        type: string
        required: true
    body:
      application/json:
        description: |
          Body contient la requête DSL unitaire au format JSON. Il est utilisé et obligatoire uniquement en présence de Accept: application/json.
          **ONLY VALID with Accept application/json**
        type: AccessTypes.AccessGetByIdQuery
        example: !include examples/access1ObjectQuery.json
    responses:
      200:
        description: Renvoie la liste de résultats contenant 1 Object d'archive correspondant à la requête DSL
        body:
          application/json:
            description: Réponse DSL unitaire pour Access contenant les métadonnées
            type: AccessTypes.AccessGetByIdResponse
            example: !include examples/access1ObjectResponse.json
          application/octet-stream:
            description: Objet binaire

  AccessUpdateUnitResponse:
    description: Response model for Update Unit under Units collection in access
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader200, StandardTraits.StandardHeader400,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader403, StandardTraits.StandardHeader404, StandardTraits.StandardHeader405, StandardTraits.StandardHeader412 ]
    headers:
      X-Access-Contract-Id:
        type: string
        required: true
    body:
      application/json:
        description: Body contient la requête DSL unitaire de modification au format JSON.
        type: AccessTypes.AccessUpdateByIdQuery
        example: !include examples/access1UnitUpdateQuery.json
    responses:
      200:
        description: Renvoie l'état d'execution de la modification correspondant à la requête DSL
        body:
          application/json:
            description: Réponse DSL unitaire de modification pour Access contenant l'état d'execution de la modification.
            type: AccessTypes.AccessUpdateByIdResponse
            example: !include examples/access1UnitUpdateResponse.json

  DipCreationResponseAsync:
    description: Requête de création d'un DIP
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader202 ]
    body:
      application/json:
        description: Body contient la requête DSL **multiple** au format JSON.
        type: AccessTypes.AccessMultipleQuery
        example: !include examples/accessUnitQuery.json
    responses:
      202:
        description: |
          Renvoie le statut de l'opération de DIP
        body:
          application/json:
            description: Operation de DIP acceptée
            type: StandardTypes.AsyncStatus
            example: !include examples/dip.json
      500:
        description: Renvoie ce statut en cas d'erreur interne
        body:
          application/json:
            description: Internal server error

  DipV2Async:
    description: Requête de création d'un DIP v2
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader202 ]
    body:
      application/json:
        description: Body contient la requête DSL **multiple** au format JSON.
        type: AccessTypes.DipRequest
    responses:
      202:
        description: |
          Renvoie le statut de l'opération de DIP V2
        body:
          application/json:
            description: Operation de DIP V2 acceptée
            type: StandardTypes.AsyncStatus
            example: !include examples/dip.json
      500:
        description: Renvoie ce statut en cas d'erreur interne
        body:
          application/json:
            description: Internal server error

  TransferCreationResponseAsync:
    description: Requête de création d'un transfer SIP
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader202 ]
    body:
      application/json:
        description: Body contient la requête ayant un DSL **multiple** et d'autres paramètres au format JSON.
        type: AccessTypes.TransferRequest
    responses:
      202:
        description: |
          Renvoie le statut de l'opération de Transfer
        body:
          application/json:
            description: Operation de Transfer acceptée
            type: StandardTypes.AsyncStatus
            example: !include examples/transfer.json
      500:
        description: Renvoie ce statut en cas d'erreur interne
        body:
          application/json:
            description: Internal server error

  EliminationResponseAsync:
    description: Requête d'élimination
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader202 ]
    body:
      application/json:
        description: Body contient la requête DSL **multiple** au format JSON ainsi que la date d'élimination.
        type: AccessTypes.EliminationRequest
        example: !include examples/eliminationRequest.json
    responses:
      202:
        description: |
          Renvoie le statut de l'opération de l'élimination
        body:
          application/json:
            description: Operation d'élimination acceptée
            type: AccessTypes.EliminationResponse
            example: !include examples/eliminationResponse.json
      500:
        description: Renvoie le statut final de l'opération d'élimination en KO
        body:
          application/json:
            description: Rapport final de l'opération d'élimination

  PreservationResponseAsync:
    description: Requête de préservation
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader202 ]
    body:
      application/json:
        description: |
          Body contient la requête DSL au format JSON.
          l'Identifiant du scénario de préservation.
          l'usage source source du binaire à traité,
          La version du binaire source (FIRST ou LAST) et
          l'usage cible du binaire à générer
        type: AccessTypes.PreservationRequest
        example: !include examples/preservationRequest.json
    responses:
      202:
        description: |
          Renvoie le statut de l'opération de préservation
        body:
          application/json:
            description: Operation de préservation acceptée
            type: AccessTypes.PreservationResponse
            example: !include examples/preservationResponse.json
      500:
        description: Renvoie le statut final de l'opération de préservation en KO
        body:
          application/json:
            description: Rapport final de l'opération de préservation

  UnitBatchUpdateResponse:
      description: Requête de mise à jour de masse des métadonnées de gestion des unitiés archivistiques
      is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader202 ]
      body:
        application/json:
          type: AccessTypes.UnitBatchUpdateRequest
      responses:
        202:
          description: |
            Renvoie le statut de l'opération de mise à jour
          body:
            application/json:
              description: Operation de mise à jour acceptée
        500:
          description: Renvoie le statut final de l'opération en KO
          body:
            application/json:
              description: informations sur l'echec du lancement de l'opération

  UnitComputedInheritedRulesDeleteResponse:
          description: Requête de suppression de masse des métadonnées de gestion calculées des unitiés archivistiques
          is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader202 ]
          body:
            application/json:
              example: !include examples/launchComputeInheritedRulesAfterIngest.json
          responses:
            202:
              description: |
                Renvoie le statut de l'opération de mise à jour
              body:
                application/json:
                  description: Operation de mise à jour acceptée
            500:
              description: Renvoie le statut final de l'opération en KO
              body:
                application/json:
                  description: informations sur l'echec du lancement de l'opération

  UnitComputedInheritedRulesResponse:
        description: Requête de mise à jour de masse des métadonnées de gestion calculées des unitiés archivistiques
        is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader202 ]
        body:
          application/json:
            example: !include examples/launchComputeInheritedRulesAfterIngest.json
        responses:
          202:
            description: |
              Renvoie le statut de l'opération de mise à jour
            body:
              application/json:
                description: Operation de mise à jour acceptée
          500:
            description: Renvoie le statut final de l'opération en KO
            body:
              application/json:
                description: informations sur l'echec du lancement de l'opération

  TransferReplyResponseAsync:
    description: Requête de transfert reply
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader202 ]
    body:
      application/json:
        description: Body contient la requête ayant un DSL **multiple** et d'autres paramètres au format JSON.
        type: AccessTypes.TransferRequest
    responses:
      202:
        description: |
          Renvoie le statut de l'opération de Transfer
        body:
          application/json:
            description: Operation de Transfer acceptée
            type: StandardTypes.AsyncStatus
            example: !include examples/transfer.json
      500:
        description: Renvoie ce statut en cas d'erreur interne
        body:
          application/json:
            description: Internal server error