#%RAML 1.0 Library

usage: |
  Use to define global types for Vitam's administration

types:

  TenantRequest:
      displayName: Tenant
      type: integer
      required: true  		

  AdminReindexationRequest:
      displayName: Requête de réindexation
      description: Requête Vitam de réindexation
      type: object
      properties:
        collection:
          type: string
          required: true
        tenants:
          type: array
          items: TenantRequest
          required: false
      example: [{
        "collection": "ObjectGroup",
        "tenants": [0]
        }]

  AdminSwitchRequest:
      displayName: Requête de switch d'indexes
      description: Requête Vitam de switch
      type: object
      properties:
        alias:
          type: string
          required: true
        indexName:
          type: string
          required: true
      example: [{
        "alias": "ObjectGroup",
        "indexName": "objectgroup_20_20180126_143919"
        }]
