#%RAML 1.0 Library

usage: |
  Use to define global headers for Access
uses:
  StandardTypes: StandardTypes.raml
  StandardTraits: StandardTraits.raml
  AccessTypes: AccessTypes.raml
  AdminTypes: AdminTypes.raml
  DslTypes: DslTypes.raml

traits:

  AdminListingResponse:
    description: Response model for the listing of <<resourcePathName | !uppercamelcase>>
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AccessContractHeader,
       StandardTraits.StandardHeader200, StandardTraits.StandardHeader206,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    body:
      application/json:
        description: Contient la requête DSL simple au format JSON.
        type: DslTypes.DslSingleQuery
        example: !include examples/dslQuery.json
    responses:
      200:
        description:  Renvoie la liste des résultats de type <<resourcePathName | !uppercamelcase>> correspondant à la requête DSL
        body:
          application/json:
            description: Réponse DSL multiple pour Access contenant les <<resourcePathName | !uppercamelcase>>
            type: DslTypes.DslSingleResponse
            #example: !include examples/logbookResponse.json

  AdminItemResponse:
    description: Response model for one <<resourcePathName | !uppercamelcase>> item
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AccessContractHeader,
      StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    responses:
      200:
        description: Retourne un élément de type <<resourcePathName | !uppercamelcase>>
        body:
          application/json:
            description: un élément de type <<resourcePathName | !uppercamelcase>>
            type: DslTypes.DslSingleResponse
            #example: !include examples/logbookResponse.json

  AdminUploadFormat:
    description: Response model for check or upload of <<resourcePathName | !uppercamelcase>>
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AccessContractHeader,
      StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412, StandardTraits.StandardHeader409 ]
    body:
      application/xml:
        description: Contient le fichier source <<resourcePathName | !uppercamelcase>> au format XML (Formats from PRONOM registry)
    responses:
      201:
        description: Réponse si le versement ou la vérification de <<resourcePathName | !uppercamelcase>> est OK

  AdminUploadRule:
    description: Response model for check or upload of <<resourcePathName | !uppercamelcase>>
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AccessContractHeader,
      StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412, StandardTraits.StandardHeader409 ]
    body:
      application/csv:
        description: Contient le fichier source <<resourcePathName | !uppercamelcase>> au format CSV (Rules)
    responses:
      201:
        description: Réponse si le versement ou la vérification de <<resourcePathName | !uppercamelcase>> est OK

  AdminUpdate:
    description: Response model for update of <<resourcePathName | !uppercamelcase>>
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AccessContractHeader,
      StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412, StandardTraits.StandardHeader409 ]
    body:
      application/json:
        description: Body contient la requête DSL unitaire de modification au format JSON.
        type: AccessTypes.AccessUpdateByIdQuery
        example: !include examples/adminUpdateQuery.json
    responses:
      201:
        description: Réponse si la modification de <<resourcePathName | !uppercamelcase>> est OK

  AdminUpload:
    description: Response model for check or upload of <<resourcePathName | !uppercamelcase>>
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AccessContractHeader,
      StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412, StandardTraits.StandardHeader409 ]
    body:
      application/json:
        description: Contient le fichier source <<resourcePathName | !uppercamelcase>> au format Json
      application/octet-stream:
        description: Contient le fichier source <<resourcePathName | !uppercamelcase>> au format InputStream
    responses:
      201:
        description: Réponse si le versement ou la vérification de <<resourcePathName | !uppercamelcase>> est OK

  AdminProfileUpload:
    description: Response model for upload of <<resourcePathName | !uppercamelcase>>
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AccessContractHeader,
      StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    body:
      application/octet-stream:
        description: Contient le fichier source <<resourcePathName | !uppercamelcase>> au format InputStream (for Profile as XSD or RNG format)
    responses:
      201:
        description: Réponse si le versement ou la vérification de <<resourcePathName | !uppercamelcase>> est OK

  AdminFileItemResponse:
    description: Response model for one <<resourcePathName | !uppercamelcase>> download item
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AccessContractHeader,
      StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    responses:
      200:
        description: Retourne un fichier de type <<resourcePathName | !uppercamelcase>>
        body:
          application/octet-stream:
            description: un fichier de type <<resourcePathName | !uppercamelcase>>

  AuditCreationResponseAsync:
    description: Requête pour la création d'un Audit
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AccessContractHeader, StandardTraits.StandardHeader202 ]
    body:
      application/json:
        description: Contient les options de l'audit au format JSON.
        type: AdminTypes.AuditOptions
        example: !include examples/auditLaunchQuery.json
    responses:
      202:
        description: |
          Retourne le status de ACCEPTED en cas de succès de la création de l'opération d'Audit
        body:
          application/json:
            description: Audit operation accepted
            type: StandardTypes.AsyncStatus
            example: !include examples/auditResponse.json
      500:
        description: |
          Retourne le status de KO en cas d'erreur de la création de l'opération d'Audit
        body:
          application/json:
            description: Final Audit report

  TraceabilityCheckResponseAsync:
    description: Request for an Traceability Check
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.AccessContractHeader, StandardTraits.StandardHeader202 ]
    body:
      application/json:
        description: Contient la requête DSL simple au format JSON.
        type: DslTypes.DslSingleQuery
        example: !include examples/logbookQuery.json
    responses:
      202:
        description: |
          Retourne le statut ACCEPTED en cas de succès de l'opération Traceability Check
        body:
          application/json:
            description: Traceability operation accepted
            type: StandardTypes.AsyncStatus
            example: !include examples/traceability.json
      500:
        description: Returns the final result of the Traceability operation in KO status
        body:
          application/json:
            description: Final Traceability report

