#%RAML 1.0 Library

usage: |
  Utilisé pour définir les types pour la mise à jour de masse des métadonnées de gestion

types:
  RuleActions:
    displayName: Actions de mise à jour
    description: Définit les 3 actions possibles de la mise à jour des métadonnées (Ajout/Mise à jour/Suppression)
    type: object
    properties:
      add:
        description: Métadonnées de gestion à ajouter
        type: RuleCategory[]
      update:
        description: Métadonnées de gestion à mettre à jour
        type: RuleCategory[]
      delete:
        description: Métadonnées de gestion à supprimer
        type: RuleCategory[]
      addOrUpdateMetadata:
        description: Modification de valeur de métadonnée(s) de gestion (hors règles de gestion), peut être vide/null
        type: ManagementMetadata
      deleteMetadata:
        description: Suppression de valeur de métadonnée(s) de gestion (hors règles de gestion), peut être vide/null
        type: ManagementMetadata

  RuleCategory:
    displayName: Liste des catégories
    description: Définit les catégories impactées par la modification. La liste peut être vide. Chaque élément de la liste doit contenir une catégorie (Voir exemples)
    type: object
    properties:
      AccessRule?:
        description: Modifications liées aux délais de communicabilité
        type: CategoryMetadata
      AppraisalRule?:
        description: Modification liées aux durées d'utilité administrative'
        type: CategoryMetadata
      ClassificationRule?:
        description: Modifications liées aux durées de classification
        type: CategoryMetadata
      DisseminationRule?:
        description: Modifications liées aux délais de diffusion
        type: CategoryMetadata
      ReuseRule?:
        description: Modifications liées aux durées de réutilisation
        type: CategoryMetadata
      StorageRule?:
        description: Modifications liées aux durées d'utilité courante
        type: CategoryMetadata
      HoldRule?:
        description: Modifications liées aux durées de gel
        type: CategoryMetadata

  ManagementMetadata:
    displayName: Liste des champs de gestion
    description: Définit les champs impactées par la modification
    type: object
    properties:
      ArchiveUnitProfile?:
        description: Modifications de l'identifiant de documents type (La valeur doit être non nulle dans le cas d'une suppression)
        type: string


  CategoryMetadata:
    displayName: Métadonnées par catégories
    description: Définit les métadonnées de gestion impactées par la modification.
    type: object
    properties:
      Rules?:
        description: Permet de définir les règles de gestion à modifier
        type: RuleMetadata[]
      FinalAction?:
        description: |
          Permet de définir un sort final.
          Définit seulement pour les categories "StorageRule (RestrictAccess/Copy/Transfer)" et "AccessRule(Keep/Destroy)".
        type: string
      ClassificationLevel?:
        description: |
          Permet de définir le niveau de classification.
          Définit seulement pour la catégorie "ClassificationRule" parmis des valeurs définies par l'administrateur de la plateforme (vitam.conf / ClassificationLevel)
        type: string
      ClassificationOwner?:
        description: Permet de définir le propriétaire de la classification. Définit seulement pour la catégorie "ClassificationRule".
        type: string
      ClassificationAudience?:
        description: Permet de définir le champ de diffusion. Définit seulement pour la catégorie "ClassificationRule".
        type: string
      ClassificationReassessingDate?:
        description: Permet de définir la date de réévalusation. Définit seulement pour la catégorie "ClassificationRule".
        type: datetime
        example: 2018-11-14T00:00:00.000Z
      NeedReassessingAuthorization?:
        description: Permet de définir si les modifications sont soumises à validation. Définit seulement pour la catégorie "ClassificationRule".
        type: boolean
      PreventInheritance?:
        description: Permet de définir si TOUTES les règles des unités archivistiques parentes sont bloquées(true) ou héritiées(false)
        type: boolean
      PreventRulesId?:
        description: Permet de définir la liste des règles bloquées
        type: string[]

  RuleMetadata:
    displayName: Métadonnées par règle
    description: Définit les métadonnées de règles de gestion.
    type: object
    properties:
      Rule:
        description: Permet de définir l'identifiant à ajouter/supprimer ou le nouvel identifiant de règle lors d'une modification.
        type: string
        example: ACC-000001
      OldRule?:
        description: Permet de définir l'ancien identifiant de règle pour la modification d'une règle (changement d'ID et/ou de date)
        type: string
        example: ACC-000002
      StartDate?:
        description: Permet de définir la date de début d'une nouvelle règle ou de modifier la date de début lors d'une modification.
        type: date-only
        example: 2018-11-14
      DeleteStartDate?:
        description: Permet de supprimer (true) la date de début de la règle à mettre à jour.
        type: boolean
      HoldEndDate?:
        description: Permet de définir la date de fin de gel explicite. Réservé aux règles de gel.
        type: date-only
        example: 2018-11-14
      DeleteHoldEndDate?:
        description: Permet de supprimer (true) la date de fin de gel explicite. Réservé aux règles de gel.
        type: boolean
      HoldOwner?:
        description: Permet de définir le propriétaire de la demande de gel. Réservé aux règles de gel.
        type: string
        example: Hold Owner
      DeleteHoldOwner?:
        description: Permet de supprimer (true) le propriétaire de la demande de gel. Réservé aux règles de gel.
        type: boolean
      HoldReason?:
        description: Permet de définir le motif de la demande de gel. Réservé aux règles de gel.
        type: string
        example: Hold Owner
      DeleteHoldReason?:
        description: Permet de supprimer (true) le motif de la demande de gel. Réservé aux règles de gel.
        type: boolean
      HoldReassessingDate?:
        description: Permet de définir la date de réévaluation du gel. Réservé aux règles de gel.
        type: date-only
        example: 2018-11-14
      DeleteHoldReassessingDate?:
        description: Permet de supprimer (true) la date de réévaluation du gel. Réservé aux règles de gel.
        type: boolean
      PreventRearrangement?:
        description: Permet de définir si le blocage de la reclassification est activé (true) ou non (false). Réservé aux règles de gel.
        type: boolean
      DeletePreventRearrangement?:
        description: Permet de supprimer (true) le blocage de la reclassification. Réservé aux règles de gel.
        type: boolean
