#%RAML 1.0 Library

usage: |
  Use to define global types for Ingest

uses:
    StandardTypes: StandardTypes.raml

types:
  ArchiveTransferReply:
    description: Ingest Seda Response
    schema: !include xsd/seda-2.1-main.xsd#ArchiveTransferReply
    example: !include examples/sedaArchiveTransferReply.xml

  ProcessQuery:
      displayName: Process Query
      description: External Ingest Vitam operations query
      type: object
      properties:
        id?:
          description: Contains a process id
          type: string
        states?:
          description: Contains the states of the processes (valid values = RUNNING, PAUSE, COMPLETED)
          type: string[]
        statuses?:
          description: Contains the statuses of the processes (valid values = UNKNOWN, STARTED, OK, WARNING, KO, FATAL)
          type: string[]
        workflows?:
          description: Contains the workflow identifiers of the processes
          type: string[]
        listSteps?:
          description: Contains the next steps of the processes
          type: string[]
        startDateMin?:
          description: Contains the minimum starting date of the processes with format "DD-MM-YYYY"
          type: string
        startDateMax?:
          description: Contains the maximum starting date of the processes with format "DD-MM-YYYY"
          type: string
      example: {
          "id": "1288",
          "states": ["COMPLETED"]
      }
