#%RAML 1.0 Library

usage: |
  Use to define global headers for Ingest
uses:
  StandardTypes: StandardTypes.raml
  StandardTraits: StandardTraits.raml
  DslTypes: DslTypes.raml
  IngestTypes: IngestTypes.raml

traits:

  IngestListingResponse:
    description: Request that will return the Ingest listing
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader200, StandardTraits.StandardHeader206,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    body:
      application/json:
        description: Body containing a Query in DSL Vitam to filter the Ingest operations
        type: IngestTypes.ProcessQuery
        example: !include examples/processQuery.json
    responses:
      200:
        description: Returns the list of selected ingest operations
        body:
          application/json:
            description: Selected Ingest operations
            type: DslTypes.DslSingleResponse
            example: !include examples/dslOperationsResponse.json
      206:
        description: Returns the list of selected ingest operations using Cursor
        body:
          application/json:
            description: Selected Ingest operations
            type: DslTypes.DslSingleResponse
            example: !include examples/dslOperationsResponse.json

  IngestWorkflowsResponse:
    description: |
      Response model for Workflows definitions
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    responses:
      200:
        description: Returns the list of workflow definitions
        body:
          application/json:
            description: Select Workflows
            type: DslTypes.DslSingleResponse
            example: !include examples/dslWorkflowsResponse.json

  IngestCreationResponse:
    description: Request for an Ingest creation
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader202,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    body:
      application/zip:
        description: Body containing the SIP in ZIP format
      application/x-tar:
        description: Body containing the SIP in TAR format
      application/x-gzip:
        description: Body containing the SIP in TAR.GZ format
      application/x-bzip2:
        description: Body containing the SIP in TAR.BZ2 format
    responses:
      202:
        description: |
           Returns the status of ingest operation accepted
        body:
          application/json:
            description: Ingest operation accepted
            type: StandardTypes.AsyncStatus
            example: !include examples/ingests.json
      200:
        description: Returns the final result of the Ingest operation in OK status
        body:
          application/xml:
            description: Final Ingest report
            type: IngestTypes.ArchiveTransferReply
            example: !include examples/sedaArchiveTransferReply.xml
      206:
        description: Returns the final result of the Ingest operation in Warning status
        body:
          application/xml:
            description: Final Ingest report
            type: IngestTypes.ArchiveTransferReply
            example: !include examples/sedaArchiveTransferReply.xml
      400:
        description: Returns the final result of the Ingest operation in KO status
        body:
          application/xml:
            description: Final Ingest report
            type: IngestTypes.ArchiveTransferReply
            example: !include examples/sedaArchiveTransferReplyKO.xml
  IngestCreationResponseAsync:
    description: Request for an Ingest creation
    is: [ StandardTraits.StandardOptionalHeader, StandardTraits.StandardHeader202 ]
    body:
      application/zip:
        description: Body containing the SIP in ZIP format
      application/x-tar:
        description: Body containing the SIP in TAR format
      application/x-gzip:
        description: Body containing the SIP in TAR.GZ format
      application/x-bzip2:
        description: Body containing the SIP in TAR.BZ2 format
      application/json:
        description: Body containing path information to the local SIP
        example: !include examples/localIngest.json
    responses:
      202:
        description: Returns the status of ingest operation accepted
        body:
          application/json:
            description: Ingest operation accepted
            type: StandardTypes.AsyncStatus
            example: !include examples/ingests.json
      500:
        description: Returns the final result of the Ingest operation in KO status
        body:
          application/xml:
            description: Final Ingest report

  IngestFinalResponse:
    description: Request that will return the final response model for Ingest
    is: [ StandardTraits.StandardOptionalHeader,
      StandardTraits.StandardHeader200,
      StandardTraits.StandardHeader401, StandardTraits.StandardHeader404, StandardTraits.StandardHeader412 ]
    responses:
      200:
        description: Returns the final result of the Ingest operation
        body:
          application/xml:
            description: Final Ingest report
            type: IngestTypes.ArchiveTransferReply
            example: !include examples/sedaArchiveTransferReply.xml
      400:
        description: Returns the final error status of the Ingest operation
        body:
          application/xml:
            description: Final Error Ingest report
            type: IngestTypes.ArchiveTransferReply
            example: !include examples/sedaArchiveTransferReplyKO.xml
