#%RAML 1.0 Library

usage: |
  Use to define global types

uses:
  DslTypes: DslTypes.raml

types:
  Context:
    description: Type of the task.
    type: string
    #enum:
    #  - ingest
    #  - access
    #  - query
    #  - freeze
    #  - destruction
    #  - audit
    #  - platform
    #  - internal
    #  - External Access"""

  Filter:
    description: Filter for a Request
    type: object
    properties:
      $offset:
        type: integer
        required: false
        minimum: 1
        maximum: 100000
      $limit:
        type: integer
        minimum: 1
        maximum: 100000
        required: false
      $orderby:
        type: object
        required: false

  Projection:
    description: Projection for a Request
    type: object
    properties:
      $fields:
        type: object
        required: false

  Error:
    description: A simple error (unique) in Vitam DSL
    type: object
    properties:
      httpCode:
        description: Short code as in RFC 7231 (Http Status Codes).
        type: integer
      code:
          description: Vitam standard numerical code.
          type: string
      context: Context
      state:
        description: Vitam standard litteral code.
        type: string
      message:
        type: string
        description: Vitam standard description message.
      description:
        type: string
        description: Vitam detailed description of status.

  ErrorMultiple:
    description: An error message in Vitam DSL
    type: object
    properties:
      httpCode:
        description: Short code as in RFC 7231 (Http Status Codes).
        type: integer
      code:
          description: Vitam standard code.
          type: string
      context: Context
      state:
        description: Vitam standard litteral code.
        type: string
      message:
        type: string
        description: Vitam standard description message.
      description:
        type: string
        description: Vitam detailed description of status.
      errors?:
        description: Sub error descriptions.
        type: Error[]


  AsyncResponse:
    type: object
    displayName: Réponse DSL
    description: Réponse DSL externe Vitam
    properties:
      itemId:
        description: Contient le code retrour http
        type: string
      message:
        description: Contient le nombre de hits
        required: true
        type: string
      globalStatus:
        description: Contient le code retrour http
        type: string
      statusMeter:
        description: lala
        type: number[]
      data:
        description: Contient le code retrour http
        type: object
      itemsStatus:
        description: Contient le code retrour http
        type: object
      evDetailData:
        description: Contient le code retrour http
        type: string
      globalState:
        description: Contient le code retrour http
        type: string
      subTaskStatus:
        description: Contient le code retrour http
        type: object
      lifecycleEnable:
        description: Contient le code retrour http
        type: boolean


  AsyncStatus:
    description: Asynchronous Status
    type: DslTypes.AbstractDslResponse
    properties:
      $results:
        type: AsyncResponse[]
    example: {
       httpCode: 200,
       $hits: {
           total: 1,
           offset: 0,
           limit: 0,
           size: 1
       },
       $results: [
           {
               itemId: "operationId",
               message: "",
               globalStatus: "STARTED",
               statusMeter: [0,1,0,0,0,0,0],
               data: {},
               itemsStatus: {},
               evDetailData: "{}",
               globalState: "RUNNING",
               subTaskStatus: {},
               lifecycleEnable: true
           }
       ],
       $facetResults: [],
       $context: {}
    }
