#%RAML 1.0 Library

usage: |
  Use to define global headers
uses:
  StandardTypes: StandardTypes.raml

traits:

  AllowsHeader:
    headers:
      Accept:
        description: |
          Allow to specify if a result must contain only Metadata ('_application/json_'), or a complete DIP (**UNSUPPORTED**) (one ZIP or TAR containing both Metadata and Binary object) ('_application/zip_' or '_application/x-tar_') or only the _Objects_ with a binary content ('_application/octet-stream_').
        type: string
        enum: [ "application/json", "application/zip", "application/octet-stream" ]

  StandardOptionalHeader:
    headers: &optionalheader
      X-Application-Id:
        type: string
        required: false
        description: |
            **UNSUPPORTED** Session Identifier from client Front-Office Application
        example: SESSION-ID-00001
      X-Tenant-Id:
        type: number
        required: true
        description: Unique Tenant Identifier
        example: 0

  StandardHeadHeader:
    headers:
      X-Valid:
        description: |
          **UNSUPPORTED** Allow to check if the item is valid (exists and digest is correct)
        type: boolean
        required: false

  AsynchronousHeader:
    headers:
      X-Callback?:
        description: |
          **UNSUPPORTED** Callback uri when the operation will be done
        type: string
        example: https://callback-host:port/uri/idcallback?status={status}&id={id}
    responses:
      202:
        headers:
          X-Callback?:
            description: |
              **UNSUPPORTED** Callback uri when the operation will be done
            type: string
            example: https://callback-host:port/uri/idcallback?status={status}&id={id}

  PaginationRequestHeader:
    headers:
      X-Cursor?:
        description: |
          **UNSUPPORTED** If present and true means the query could use a cursor as response if necessary
        type: boolean

  PaginationNextHeader:
    headers: &pagination
      X-Cursor-Id?:
        description: |
          **UNSUPPORTED** If present, means the query could continue with the next set of response, according to current position of the Cursor Id
        type: string

  PaginationResponseHeader:
    responses:
      206:
        headers:
          X-Cursor-Id?:
            description: |
              **UNSUPPORTED** If present, means the query could continue with the next set of response, according to current position of the Cursor Id
            type: string
          X-Cursor-Timeout?:
            description: |
              **UNSUPPORTED** When X-Cursor-Id is present, it specifies the date and time limit of the availability of this cursor Id
            type: datetime

  StandardHeader200:
    responses:
      200:
        description: OK, operation in success
        headers: &standardheader
          X-Request-Id:
            type: string
            required: true
            description: Unique Request Identifier
            example: AbDUh67jj
          FullApiVersion:
            type: string
            required: false
            description: Complete Version of the API.
            example: V1.25
          X-Application-Id:
            type: string
            required: false
            description: Session Identifier from client Front-Office Application
            example: SESSION-ID-00001
          X-Tenant-Id:
            type: number
            required: true
            description: Unique Tenant Identifier
            example: 0
  StandardHeader201:
    responses:
      201:
        description: Created, creation operation in success
        headers: *standardheader
  StandardHeader202:
    responses:
      202:
        description: Accepted, Asynchronous operation accepted
        headers: *standardheader
  StandardHeader204:
    responses:
      204:
        description: No Content, Used to test existence or for Status
        headers: *standardheader
  StandardHeader206:
    responses:
      206:
        description: Partial Content, pagination involved
        headers: *standardheader
  StandardHeader400:
    responses:
      400:
        description: Bad Request, syntax might be erroneous
        headers: *standardheader
  StandardHeader401:
    responses:
      401:
        description: Unauthorized, authentication in error
        headers: *standardheader
  StandardHeader403:
    responses:
      403:
        description: Forbidden, requested action is forbidden
        headers: *standardheader
  StandardHeader404:
    responses:
      404:
        description: Not Found, requested resource does not exist
        headers: *standardheader
  StandardHeader409:
    responses:
      409:
        description: Conflict, operation requested is in conflict with existing data
        headers: *standardheader
  StandardHeader412:
    responses:
      412:
        description: Precondition Failed, some predicates are incorrect, therefore the operation is not possible
        headers: *standardheader
  StandardHeader415:
    responses:
      415:
        description: Unsupported Media Type, the Content-Type in the request is not supported
        headers: *standardheader
  StandardHeader417:
    responses:
      417:
        description: Expectation Failed, used in Validation when the required validation (X-Valid) is in error
        headers: *standardheader
  StandardHeader503:
    responses:
      503:
        description: Service Unavailable, the requested service is unavailable

  OverrideGet:
    description: For HTTP clients that do not support GET Request with a body
    headers:
      X-Http-Method-Override?:
        type: string
        enum:
          - GET
  OverridePut:
    description: For HTTP clients that do not support PUT Request with a body
    headers:
      X-Http-Method-Override?:
        type: string
        enum:
          - PUT
  OverrideHead:
    description: For HTTP clients that do not support HEAD Request
    headers:
      X-Http-Method-Override?:
        type: string
        enum:
          - HEAD
  OverrideOptions:
    description: For HTTP clients that do not support OPTIONS Request
    headers:
      X-Http-Method-Override?:
        type: string
        enum:
          - OPTIONS
  OverrideDelete:
    description: For HTTP clients that do not support DELETE Request with a body
    headers:
      X-Http-Method-Override?:
        type: string
        enum:
          - DELETE

  StandardErrors:
    responses:
      404:
        description: Not Found, requested resource does not exist
        body:
          application/json:
            type: StandardTypes.ErrorMultiple
            example: !include examples/error-404.json

      412:
        description: Precondition Failed, some predicates are incorrect, therefore the operation is not possible
        body:
          application/json:
            type: StandardTypes.ErrorMultiple
            example: !include examples/error-412.json
