secret : vitamsecret
filterActivation : true
distributeurBatchSize: 800
distributionThreshold : 100000
eliminationAnalysisThreshold : 100000
eliminationActionThreshold : 100000
computedInheritedRulesThreshold : 100000000
workerBulkSize: 16
intervalDelayCheckIdle : 5000
maxDelayUnusedConnection : 5000
delayValidationAfterInactivity : 2500
tenants :  [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
adminTenant : 1
environmentName : local

reclassificationMaxBulkThreshold: 1000
reclassificationMaxUnitsThreshold: 10000
reclassificationMaxGuildListSizeInLogbookOperation: 1000

classificationLevel :
  allowList :  [Secret Défense, Confidentiel Défense, Non protégé]
  authorizeNotDefined: true

indexInheritedRulesWithAPIV2OutputByTenant: ["0", "1", "2"]
indexInheritedRulesWithRulesIdByTenant: ["0", "1", "2"]

ontologyCacheMaxEntries: 100
ontologyCacheTimeoutInSeconds: 300

eliminationReportExtraFields:
 - tenant: 0
   metadataFields: [ "FilePlanPosition", "SystemId", "OriginatingSystemId", "ArchivalAgencyArchiveUnitIdentifier", "OriginatingAgencyArchiveUnitIdentifier", "TransferringAgencyArchiveUnitIdentifier" ]
 - tenant: 1
   metadataFields: [ "SystemId" ]

ingestReportUnitExtraFields:
  - tenant: 0
    metadataFields: [ "PersistentIdentifier" ]
  - tenant: 1
    metadataFields: [ "OriginatingSystemId" ]

ingestReportObjectExtraFields:
  - tenant: 0
    metadataFields: [ "PersistentIdentifier" ]
  - tenant: 1
    metadataFields: [ "PersistentIdentifier" ]


traceabilityVersionConfiguration:
  - tenant: 0
    logbookOperation: V2
    lfcUnit: V2
    lfcGot: V2
  - tenant: 1
    logbookOperation: V1
    lfcUnit: V1
    lfcGot: V1
  - tenant: 2
    logbookOperation: V1
    lfcUnit: V1
    lfcGot: V1
  - tenant: 3
    logbookOperation: V1
    lfcUnit: V1
    lfcGot: V1
  - tenant: 4
    logbookOperation: V1
    lfcUnit: V1
    lfcGot: V1
  - tenant: 5
    logbookOperation: V1
    lfcUnit: V1
    lfcGot: V1
  - tenant: 6
    logbookOperation: V1
    lfcUnit: V1
    lfcGot: V1
  - tenant: 7
    logbookOperation: V1
    lfcUnit: V1
    lfcGot: V1
  - tenant: 8
    logbookOperation: V1
    lfcUnit: V1
    lfcGot: V1
  - tenant: 9
    logbookOperation: V1
    lfcUnit: V1
    lfcGot: V1
