org.quartz.scheduler.instanceName=VitamScheduler

org.quartz.scheduler.instanceId=1
org.quartz.scheduler.interruptJobsOnShutdown=true

org.quartz.threadPool.class=fr.gouv.vitam.scheduler.server.util.VitamQuartzExecutorThreadPool
org.quartz.threadPool.threadCount=10

## H2DB local non-clustered connector
#
org.quartz.jobStore.isClustered=false
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.dataSource=h2DS
org.quartz.jobStore.tablePrefix=QRTZ_

org.quartz.dataSource.h2DS.driver=org.h2.Driver
org.quartz.dataSource.h2DS.provider=hikaricp
org.quartz.dataSource.h2DS.URL=jdbc:h2:file:/vitam/data/scheduler/quartz-db;DB_CLOSE_ON_EXIT=FALSE
org.quartz.dataSource.h2DS.maxConnections=10

## Postgres clustered connector:
#
# org.quartz.jobStore.isClustered=true
# org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
# org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
# org.quartz.jobStore.dataSource=postgresDS
#
# org.quartz.dataSource.postgresDS.driver=org.postgresql.Driver
# org.quartz.dataSource.postgresDS.provider=hikaricp
# org.quartz.dataSource.postgresDS.URL = jdbc:postgresql://localhost:5432/scheduler
# org.quartz.dataSource.postgresDS.user=scheduler
# org.quartz.dataSource.postgresDS.password=azerty4
# org.quartz.dataSource.postgresDS.maxConnections=10