#!/bin/sh
if [ -x /bin/systemctl ]; then
  systemctl daemon-reload >/dev/null 2>&1 || true
fi

case "$1" in
  upgrade)
    # systemd: start the new version
    if [ -x /bin/systemctl ]; then
      systemctl restart vitam-${unix.name}.service
    fi
    ;;

  purge)
    rm -rf /vitam/log/${unix.name} /vitam/conf/${unix.name} /vitam/tmp/${unix.name}
    ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

   *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac