---

- block:

    - name: Create docker config folder
      file:
        path: "/etc/docker/"
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: Setup docker daemon configuration
      template:
        src: daemon.json.j2
        dest: "/etc/docker/daemon.json"
        owner: root
        group: root
        mode: 0644
        backup: true
      notify: "docker - restart service"

  when:
  - docker_opts.docker_bip is defined
  - docker_opts.docker_address_pools_cidr is defined
  - docker_opts.docker_address_pools_size is defined

- name: Make sure net.ipv4.ip_unprivileged_port_start is disabled
  sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    sysctl_set: yes
    value: '0'
