{
 "title": "Offre froide - _OFFER_ID_",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "datasource", "query": "prometheus" },
   { "name": "offerId", "query": "_OFFER_ID_" }
  ]
 },
 "panels": [
  {
   "title": "Etat des lecteurs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vitam_offer_tape_workers_total{offerId=\"${offerId}\"}",
     "legendFormat": "Nombre de lecteurs disponibles"
    },
    {
     "expr": "vitam_offer_tape_workers_interrupted{offerId=\"${offerId}\"}",
     "legendFormat": "Nombre de lecteurs KO"
    }
   ]
  },
  {
   "title": "Utilisation du cache disque",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vitam_offer_tape_cache_capacity_max{offerId=\"${offerId}\"}",
     "legendFormat": "Capacité maximale"
    },
    {
     "expr": "vitam_offer_tape_cache_capacity_used{offerId=\"${offerId}\"}",
     "legendFormat": "Utilisation actuelle"
    }
   ]
  },
  {
   "title": "Etat de remplissage des bandes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vitam_offer_tape_state_conflict{offerId=\"${offerId}\"}",
     "legendFormat": "Bandes en erreur "
    },
    {
     "expr": "vitam_offer_tape_state_empty{offerId=\"${offerId}\"}",
     "legendFormat": "Bandes vides"
    },
    {
     "expr": "vitam_offer_tape_state_open{offerId=\"${offerId}\"}",
     "legendFormat": "Bandes partiellement écrites"
    },
    {
     "expr": "vitam_offer_tape_state_full{offerId=\"${offerId}\"}",
     "legendFormat": "Bandes remplies"
    }
   ]
  },
  {
   "title": "Demandes d'accès",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "vitam_offer_tape_access_requests_non_ready_count{offerId=\"${offerId}\"}",
     "legendFormat": "Demandes d'accès en préparation"
    },
    {
     "expr": "vitam_offer_tape_access_requests_ready_count{offerId=\"${offerId}\"}",
     "legendFormat": "Demandes d'accès prêtes"
    },
    {
     "expr": "vitam_offer_tape_access_requests_expired_count{offerId=\"${offerId}\"}",
     "legendFormat": "Demandes d'accès expirées"
    }
   ]
  },
  {
   "title": "Ordres de lecture depuis bandes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "vitam_offer_tape_read_orders_ready_count{offerId=\"${offerId}\"}",
     "legendFormat": "Ordres de lecture en attente"
    },
    {
     "expr": "vitam_offer_tape_read_orders_running_count{offerId=\"${offerId}\"}",
     "legendFormat": "Ordres de lecture en cours d'exécution"
    },
    {
     "expr": "vitam_offer_tape_read_orders_error_count{offerId=\"${offerId}\"}",
     "legendFormat": "Ordres de lecture KO"
    }
   ]
  },
  {
   "title": "Ordres d'écriture vers bandes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vitam_offer_tape_write_orders_ready_count{offerId=\"${offerId}\"}",
     "legendFormat": "Ordres d'écriture en attente"
    },
    {
     "expr": "vitam_offer_tape_write_orders_running_count{offerId=\"${offerId}\"}",
     "legendFormat": "Ordres d'écriture en cours d'éxecution"
    },
    {
     "expr": "vitam_offer_tape_write_orders_error_count{offerId=\"${offerId}\"}",
     "legendFormat": "Ordres d'écriture KO"
    }
   ]
  },
  {
   "title": "Nombre d'objets en attente d'archivage sur TARs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "vitam_offer_tape_input_files_count{offerId=\"${offerId}\"}",
     "legendFormat": "Objets reçus en attente d'archivage TAR - Bucket {{ bucket }}"
    }
   ]
  },
  {
   "title": "Volume des objets en attente d'archivage sur TARs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vitam_offer_tape_input_files_size{offerId=\"${offerId}\"}",
     "legendFormat": "Volume des objets reçus en attente d'archivage TAR - Bucket {{ bucket }}"
    }
   ]
  }
 ]
}