{
 "title": "VITAM standard dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "datasource", "query": "prometheus" },
   { "name": "proj", "query": "${VAR_PROJ}" },
   { "name": "acc", "label": "acc", "query": "${VAR_ACC}" },
   { "name": "app1", "label": "app1", "query": "${VAR_APP1}" },
   { "name": "app2", "label": "app2", "query": "${VAR_APP2}" },
   { "name": "dat1", "label": "dat1", "query": "${VAR_DAT1}" },
   { "name": "dat2", "label": "dat2", "query": "${VAR_DAT2}" },
   { "name": "exp", "label": "exp", "query": "${VAR_EXP}" },
   { "name": "sto1", "label": "sto1", "query": "${VAR_STO1}" },
   { "name": "sto2", "label": "sto2", "query": "${VAR_STO2}" },
   { "name": "workspace", "label": "workspace", "query": "${VAR_WORKSPACE}" }
  ]
 },
 "panels": [
  {
   "title": "Alert $proj",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "severity!=\\\"1\\\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Memory Warn",
   "type": "alertlist",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "alertname=\"MemoryUsage\",severity=\"warning\"",
     "filters": "alertname=MemoryUsage",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU Load warn",
   "type": "alertlist",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "alertname=\"high_cpu_load\",severity=\"warning\"",
     "filters": "high_cpu_load",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Disk Space warn",
   "type": "alertlist",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "alertname=\"OutOfDiskSpace\",severity=\"warning\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Init workflow counter rate and current workflow total rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Running_workflows{job=\"vitam-processing\"}[5m])",
     "legendFormat": "Init created workflow"
    },
    {
     "expr": "sum by(workflow) (rate(vitam_processing_workflow_operation_total{job=\"vitam-processing\"}[5m]))",
     "legendFormat": "Total operations per workflow{ workflow: {{workflow}} }"
    }
   ]
  },
  {
   "title": "Memory Crit",
   "type": "alertlist",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "targets": [
    {
     "expr": "alertname=\"MemoryUsage\",severity=\"critical\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU Load crit",
   "type": "alertlist",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "alertname=\"high_cpu_load\",severity=\"critical\"",
     "filters": "alertname=\"high_cpu_load\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Disk Space crit",
   "type": "alertlist",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "targets": [
    {
     "expr": "alertname=\"OutOfDiskSpace\",severity=\"critical\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "severity!=\"1\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Rate of completed workflows ( not ko )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(workflow) (rate(vitam_processing_workflow_operation_total{state=\"COMPLETED\",status!=\"KO\"}[5m]))",
     "legendFormat": "Total operations rate { workflow:{{workflow}} }"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "description": "Number of registred workers",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vitam_processing_worker_registered_total",
     "legendFormat": "Total of regisetred workers"
    }
   ]
  },
  {
   "title": "Paused ingests",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vitam_processing_workflow_operation_total{state=\"PAUSE\",workflow=\"INGEST\"}"
    }
   ]
  },
  {
   "title": "Started ingests",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vitam_processing_workflow_operation_total{status=\"STARTED\",workflow=\"INGEST\"}"
    }
   ]
  },
  {
   "title": "Running ingests",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vitam_processing_workflow_operation_total{state=\"RUNNING\",status=\"OK\",workflow=\"INGEST\"}"
    }
   ]
  },
  {
   "title": "Workspace disk usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=~\"$workspace.*\",mountpoint=\"/vitam\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/vitam\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Pause FATAL ingests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vitam_processing_workflow_operation_total{status=\"FATAL\",state=\"PAUSE\",workflow=\"INGEST\"}"
    }
   ]
  },
  {
   "title": "Running FATAL ingests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vitam_processing_workflow_operation_total{status=\"FATAL\",state=\"RUNNING\",workflow=\"INGEST\"}"
    }
   ]
  },
  {
   "title": "Completed workflows KO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workflow) (vitam_processing_workflow_operation_total{state=\"COMPLETED\",status=\"KO\"})",
     "legendFormat": "Total per workflow {workflow: {{workflow}}}"
    },
    {
     "expr": "rate(vitam_processing_workflow_operation_total{state=\"COMPLETED\",status=\"KO\"}[5m])*100",
     "legendFormat": "Rate of KO on 5 m."
    }
   ]
  },
  {
   "title": "Max ingests FATAL on 24H",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(vitam_processing_workflow_operation_total{state=\"COMPLETED\",status=\"FATAL\",workflow=\"INGEST\"}[24h])"
    }
   ]
  },
  {
   "title": "Max completed Traceabiliy on 24H",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time (vitam_processing_workflow_operation_total{state=\"COMPLETED\",workflow=\"TRACEABILITY\"}[24h])"
    }
   ]
  },
  {
   "title": "Workflow KO et Pause Fatal",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vitam_processing_workflow_operation_total{state=\"COMPLETED\",status=\"KO\",workflow=\"INGEST\"}",
     "legendFormat": "INGEST completed KO"
    },
    {
     "expr": "vitam_processing_workflow_operation_total{state=\"COMPLETED\",status=\"KO\",workflow=\"MASS_UPDATE\"}",
     "legendFormat": "MASS_UPDATE completed KO"
    },
    {
     "expr": "vitam_processing_workflow_operation_total{state=\"PAUSE\",status=\"FATAL\",workflow=\"INGEST\"}",
     "legendFormat": "INGEST pause FATAL"
    }
   ]
  },
  {
   "title": "Rate of 5 minutes of write data in the offer in Kilo Bytes per tenant and strategy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(tenant, strategy) (rate(vitam_requests_size_bytes_sum{job=\"vitam-offer\"}[5m]) /rate(vitam_requests_size_bytes_count{job=\"vitam-offer\"}[5m])) / 1024"
    }
   ]
  },
  {
   "title": "Average over time (24h) traceability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time (vitam_processing_workflow_operation_total{workflow=\"TRACEABILITY\", status=~\"OK|WARNING\"}[24h])",
     "legendFormat": "status: {{status}} state: {{state}}"
    }
   ]
  },
  {
   "title": "Rate 5 minutes of read data from the offer in Kilo Bytes per tenant and strategy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(tenant, strategy) (rate(vitam_responses_size_bytes_sum{job=\"vitam-offer\"}[5m]) /rate(vitam_responses_size_bytes_count{job=\"vitam-offer\"}[5m])) / 1024"
    }
   ]
  },
  {
   "title": "Total operations in state PAUSE status FATAL or UNKNOWN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(workflow) (vitam_processing_workflow_operation_total{state=\"PAUSE\", status=\"FATAL\"})",
     "legendFormat": "vitam_workflow_operation_total{status={{status}}}"
    },
    {
     "expr": "sum without(workflow) (vitam_processing_workflow_operation_total{state=\"PAUSE\", status=\"UNKNOWN\"})",
     "legendFormat": "vitam_workflow_operation_total{status={{status}}}"
    }
   ]
  },
  {
   "title": "ACC server",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$acc.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$acc.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$acc.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$acc.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$acc.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$acc.*\"})",
     "legendFormat": "Mem %"
    },
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=~\"$acc.*\",mountpoint=\"/vitam\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$acc.*\",mountpoint=\"/vitam\",fstype!=\"rootfs\"}",
     "legendFormat": "/vitam"
    }
   ]
  },
  {
   "title": "EXP server",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$exp.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$exp.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$exp.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$exp.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$exp.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$exp.*\"})",
     "legendFormat": "Mem %"
    },
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=~\"$exp.*\",mountpoint=\"/vitam\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$exp.*\",mountpoint=\"/vitam\",fstype!=\"rootfs\"}",
     "legendFormat": "/vitam"
    }
   ]
  },
  {
   "title": "Ingest step execution duration mean",
   "type": "bargauge",
   "description": "Le temps d'execution de chaque step du workflow INGEST",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(vitam_processing_workflow_step_execution_duration_seconds_sum{workflow=\"INGEST\"}[5m]) / rate(vitam_processing_workflow_step_execution_duration_seconds_count{workflow=\"INGEST\"}[5m])",
     "legendFormat": "{{workflow}}:{{step_name}}"
    }
   ]
  },
  {
   "title": "APP 1 server",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$app1.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$app1.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$app1.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$app1.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$app1.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$app1.*\"})",
     "legendFormat": "Mem %"
    }
   ]
  },
  {
   "title": "APP 2 server",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$app2.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$app2.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$app2.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$app2.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$app2.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$app2.*\"})",
     "legendFormat": "Mem %"
    }
   ]
  },
  {
   "title": "DAT 1 server (elk)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$dat1.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$dat1.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$dat1.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$dat1.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$dat1.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$dat1.*\"})",
     "legendFormat": "Mem %"
    }
   ]
  },
  {
   "title": "DAT 2 server (mongo)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$dat2.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$dat2.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$dat2.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$dat2.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$dat2.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$dat2.*\"})",
     "legendFormat": "Mem %"
    }
   ]
  },
  {
   "title": "STO1 server",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$sto1.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$sto1.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$sto1.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$sto1.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$sto1.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$sto1.*\"})",
     "legendFormat": "Mem %"
    }
   ]
  },
  {
   "title": "STO2 server",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$sto2.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$sto2.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$sto2.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$sto2.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$sto2.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$sto2.*\"})",
     "legendFormat": "Mem %"
    }
   ]
  },
  {
   "title": "Temps moyens d'appels (Ingest) entre le distributeur et les workers par worker et par step",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Temps moyen" }
   ],
   "targets": [
    {
     "expr": "rate(vitam_worker_task_execution_duration_seconds_sum{instance=~\".*$proj.*\"\r, workflow=\"ingest\"}[5m]) / rate(vitam_worker_task_execution_duration_seconds_count{instance=~\".*$proj.*\"\r,workflow=\"ingest\"}[5m])",
     "legendFormat": "{{worker_name}}>{{step_name}}"
    }
   ]
  },
  {
   "title": "Disk space available $server3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$sto1.*\",device!~'rootfs',device!~'tmpfs'}"
    }
   ]
  },
  {
   "title": "Disk space available $server4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$sto2.*\",device!~'rootfs',device!~'tmpfs'}"
    }
   ]
  },
  {
   "title": "Temps moyens d'attente des tâches d'ingest dans la queue dans le distributeur",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(vitam_processing_worker_task_idle_duration_in_queue_seconds_sum{workflow=\"INGEST\"}[5m]) / rate(vitam_processing_worker_task_idle_duration_in_queue_seconds_count{workflow=\"INGEST\"}[5m])",
     "legendFormat": "{{worker_family}}:{{step_name}}"
    }
   ]
  },
  {
   "title": "Load 1 - All servers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\".*\"\r}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PUT:application_octet_stream",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(_offer_v1__objects__type___objectId:___:PUT:application_octet_stream:application_json:timer{job=~\".*\",quantile=\"0.999\"}[5m]) * 1024"
    }
   ]
  },
  {
   "title": "Consul - Services Health",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(status)(consul_health_service_status) /  ignoring(status) group_left max(consul_serf_lan_members ) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Consul - Nodes Health",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(status)(consul_health_node_status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Consul - Services passed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(consul_health_service_status{status=\"passing\"} == 1) / max(consul_serf_lan_members)"
    }
   ]
  },
  {
   "title": "Consul - Services critical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(consul_health_service_status{status=\"critical\"} == 1) / max(consul_serf_lan_members)"
    }
   ]
  },
  {
   "title": "Consul Lan serf",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "consul_serf_lan_members" }
   ]
  },
  {
   "title": "Total worker tasks in queue rate 5m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vitam_processing_worker_task_in_queue_total[5m])",
     "legendFormat": "rate 5m task in queue{ worker_family: {{worker_family}}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\".*\"\r} * 100) / node_memory_MemTotal_bytes{instance=~\".*\"\r})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}