{
 "title": "Vitam Main Dashboard",
 "tags": [
  "vitam",
  "main"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "ingest_external",
    "query": {
     "query": "consul_service_checks{service_id=\"ingest-external\"}"
    }
   },
   {
    "name": "processing",
    "query": {
     "query": "consul_service_checks{service_id=\"processing\"}"
    }
   },
   {
    "name": "storage",
    "query": {
     "query": "consul_service_checks{service_id=\"storage\"}"
    }
   },
   {
    "name": "worker",
    "query": {
     "query": "consul_service_checks{service_id=\"worker\"}"
    }
   },
   {
    "name": "workspace",
    "query": {
     "query": "consul_service_checks{service_id=\"workspace\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Elasticsearch Data Health",
   "type": "stat",
   "description": "Etat du cluster Elasticsearch Data",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"elasticsearch-data\",color=\"red\"})==1 or max(elasticsearch_cluster_health_status{cluster=\"elasticsearch-data\",color=\"yellow\"}==1)+2 or max(elasticsearch_cluster_health_status{cluster=\"elasticsearch-data\",color=\"green\"}==1)+4"
    }
   ]
  },
  {
   "title": "Consul Critical Services",
   "type": "stat",
   "description": "Nombre de services Consul en état critique",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(consul_health_service_status{status=\"critical\"}==1) by (node, service_id))"
    }
   ]
  },
  {
   "title": "Consul Critical Services History",
   "type": "timeseries",
   "description": "Historique du nombre de services Consul en état critique",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(max(consul_health_service_status{status=\"critical\"}==1) by (node, service_id))",
     "legendFormat": "Critical Services"
    }
   ]
  },
  {
   "title": "Elasticsearch Log Health",
   "type": "stat",
   "description": "Etat du cluster Elasticsearch Log",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"elasticsearch-log\",color=\"red\"})==1 or max(elasticsearch_cluster_health_status{cluster=\"elasticsearch-log\",color=\"yellow\"}==1)+2 or max(elasticsearch_cluster_health_status{cluster=\"elasticsearch-log\",color=\"green\"}==1)+4"
    }
   ]
  },
  { "title": "Vitam", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Workflows",
   "type": "graph",
   "description": "Nombre de workflows par type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workflow) (vitam_processing_workflow_operation_total)",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Critical Workflows",
   "type": "bargauge",
   "description": "Nombre de workflows en état critique par statut",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (vitam_processing_workflow_operation_total{status!~\"OK|STARTED\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "ingest-external Storage (/)",
   "type": "timeseries",
   "description": "Consommation de l'espace disque par machine hébergeant le service ingest-external pour la partition root",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{hostname=~\"$ingest_external\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{hostname=~\"$ingest_external\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "workspace Storage (/)",
   "type": "timeseries",
   "description": "Consommation de l'espace disque par machine hébergeant le service workspace pour la partition root",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{hostname=~\"$workspace\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{hostname=~\"$workspace\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "worker Storage (/)",
   "type": "timeseries",
   "description": "Consommation de l'espace disque par machine hébergeant le service worker pour la partition root",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{hostname=~\"$worker\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{hostname=~\"$worker\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "worker CPU",
   "type": "timeseries",
   "description": "Consommation du CPU par machine hébergeant le service worker",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(hostname) (rate(node_cpu_seconds_total{job=\"vitam-node-exporter\",mode=\"idle\",hostname=~\"$worker\"}[1m])) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "worker RAM",
   "type": "timeseries",
   "description": "Consommation de la RAM par machine hébergeant le service worker",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{hostname=~\"$worker\"} * 100) / node_memory_MemTotal_bytes{hostname=~\"$worker\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "storage CPU",
   "type": "timeseries",
   "description": "Consommation du CPU par machine hébergeant le service storage",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(hostname) (rate(node_cpu_seconds_total{job=\"vitam-node-exporter\",mode=\"idle\",hostname=~\"$storage\"}[1m])) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "processing CPU",
   "type": "timeseries",
   "description": "Consommation du CPU par machine hébergeant le service processing",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(hostname) (rate(node_cpu_seconds_total{job=\"vitam-node-exporter\",mode=\"idle\",hostname=~\"$processing\"}[1m])) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ingest-external Stockage (/vitam)",
   "type": "timeseries",
   "description": "Consommation de l'espace disque par machine hébergeant le service ingest-external pour la partition vitam",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{hostname=~\"$ingest_external\",mountpoint=\"/vitam\"} * 100) / node_filesystem_size_bytes{hostname=~\"$ingest_external\",mountpoint=\"/vitam\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "workspace Stockage (/vitam)",
   "type": "timeseries",
   "description": "Consommation de l'espace disque par machine hébergeant le service workspace pour la partition vitam",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/vitam\",hostname=~\"$workspace\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/vitam\",hostname=~\"$workspace\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "worker Stockage (/vitam)",
   "type": "timeseries",
   "description": "Consommation de l'espace disque par machine hébergeant le service worker pour la partition vitam",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/vitam\",hostname=~\"$worker\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/vitam\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}