{
 "title": "Vitam Elasticsearch Dashboard",
 "tags": [
  "vitam",
  "elasticsearch"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "stat",
   "description": "Etat du cluster Elasticsearch",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(elasticsearch_cluster_health_status{color=\"green\",cluster=~\"$cluster\"}) + scalar(elasticsearch_cluster_health_status{color=\"yellow\",cluster=~\"$cluster\"}) * 2 + scalar(elasticsearch_cluster_health_status{color=\"red\",cluster=~\"$cluster\"}) * 3"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "stat",
   "description": "Nombre de nodes actives",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})/count(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Data Nodes",
   "type": "stat",
   "description": "Nombre de data nodes actives",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "description": "Nombre de tâches en attente d'exécution",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{cluster=~\"$cluster\"}"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active Shards",
   "type": "stat",
   "description": "Nombre de shards actifs",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "stat",
   "description": "Nombre de primary shards actifs",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "description": "Nombre de shards en cours d'initialisation",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "description": "Nombre de shards en cours de relocalisation",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "description": "Nombre de shards non assignés",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Delayed Unassigned Shards",
   "type": "stat",
   "description": "Nombre de shards non assignés dont la relocalisation a été retardée",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=~\"$cluster\"}"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Documents Indexed",
   "type": "graph",
   "description": "Nombre de documents indexés",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs{cluster=~\"$cluster\"})",
     "legendFormat": "Documents"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "description": "Taille de l'index",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "Index"
    }
   ]
  },
  {
   "title": "Documents Indexed Rate",
   "type": "graph",
   "description": "Nombre de documents indexés par seconde par machine",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=~\"$cluster\"}[1h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "description": "Nombre de requêtes par seconde par machine",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Queries/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{cluster=~\"$cluster\"}[1h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "graph",
   "description": "Nombre de requêtes en attente par type",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{cluster=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Total Memory",
   "type": "stat",
   "description": "Total de RAM sur les machines",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{elastic_cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Memory Available",
   "type": "stat",
   "description": "Total de RAM disponible sur les machines",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{elastic_cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Memory Free",
   "type": "stat",
   "description": "Total de RAM inutilisée sur les machines",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemFree_bytes{elastic_cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "graph",
   "description": "Nombre de thread pools par type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_active_count{cluster=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Thread Pool Rejections",
   "type": "graph",
   "description": "Nombre d'opérations rejetées par machine et type de thread pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_thread_pool_rejected_count{cluster=~\"$cluster\", type!=\"management\"}[5m])",
     "legendFormat": "{{hostname}} {{type}}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Consommation moyenne du CPU par machine",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "100 - (avg by(hostname) (rate(node_cpu_seconds_total{job=\"vitam-node-exporter\",mode=\"idle\",elastic_cluster_name=~\"$cluster\"}[1m])) * 100)",
     "legendFormat": "{{hostname}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "failure_tstamp"
    }
   ]
  },
  {
   "title": "Average Heap",
   "type": "graph",
   "description": "Consommation moyenne de la RAM allouée à la JVM par machine",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\",cluster=~\"$cluster\"}[15m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\",cluster=~\"$cluster\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "RX & TX Rates",
   "type": "graph",
   "description": "Nombre de paquets reçus (RX) et envoyés (TX) par seconde par le cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_transport_rx_packets_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(elasticsearch_transport_tx_packets_total{cluster=~\"$cluster\"}[5m])) * -1",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "graph",
   "description": "Durée de la garbage collection par machine et type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{ hostname }} {{ gc }}"
    }
   ]
  }
 ]
}