{
 "title": "VitamUI Spring Cloud Gateway",
 "description": "Spring Cloud Gateway Dashboard provided by: https://github.com/spring-cloud/spring-cloud-gateway",
 "tags": [
  "vitamui",
  "api-gateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "gatewayService",
    "label": "Gateway Service",
    "query": {
     "query": "label_values(spring_cloud_gateway_requests_seconds_count,job)"
    }
   },
   {
    "name": "routeId",
    "label": "Route Id",
    "query": {
     "query": "label_values(spring_cloud_gateway_requests_seconds_count,routeId)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(spring_cloud_gateway_requests_seconds_count{job=~\"$gatewayService\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Successful Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", job=~\"$gatewayService\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Unsuccessful Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", job=~\"$gatewayService\"}[$__range]))"
    }
   ]
  },
  { "title": "Request Processing Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$routeId",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_sum{routeId=~\"$routeId\", job=~\"$gatewayService\"}/spring_cloud_gateway_requests_seconds_count{routeId=~\"$routeId\", job=~\"$gatewayService\"}",
     "legendFormat": "{{ job }} / {{ status }}"
    }
   ]
  },
  { "title": "Successful API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "$routeId Success API Gateway Calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "increase(spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"$routeId\", job=~\"$gatewayService\"}[$__range])",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    }
   ]
  },
  { "title": "Unsuccessful API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "$routeId Unsuccessful GW Calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "increase(spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", routeId=~\"$routeId\", job=~\"$gatewayService\"}[$__range])",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    }
   ]
  },
  { "title": "API / HTTP Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "$routeId",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "repeat": "routeId",
   "targets": [
    {
     "expr": "sum(increase(spring_cloud_gateway_requests_seconds_count{routeId=~\"$routeId\", job=~\"$gatewayService\"}[$__range])) by (job, status)",
     "legendFormat": "{{ job }} / {{ status }}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=~\"$gatewayService\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$gatewayService\"}) by (job, instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=~\"$gatewayService\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total/jvm_gc_memory_allocated_bytes_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}