{
 "title": "Vitam - Secondary site reconstruction dashboard",
 "tags": [
  "vitam",
  "reconstruction"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(vitam_metadata_reconstruction_metadata_latency_seconds, tenant)"
    }
   },
   {
    "name": "strategy",
    "label": "Storage strategy",
    "query": {
     "query": "label_values(vitam_metadata_reconstruction_metadata_latency_seconds, strategy)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metadata reconstruction",
   "type": "timeseries",
   "description": "Reconstruction latency of Metadata (Units  & Object Groups)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "ceil(max(min by(tenant) (vitam_metadata_reconstruction_metadata_latency_seconds{collection=\"unit\", tenant=~\"$tenant\", strategy=~\"$strategy\"})) / 60)",
     "legendFormat": "Units"
    },
    {
     "expr": "ceil(max(min by(tenant) (vitam_metadata_reconstruction_metadata_latency_seconds{collection=\"objectgroup\", tenant=~\"$tenant\", strategy=~\"$strategy\"})) / 60)",
     "legendFormat": "Object Groups"
    },
    {
     "expr": "ceil(min(vitam_metadata_reconstruction_graph_latency_seconds{collection=\"unit\"}) / 60)",
     "legendFormat": "Units Graph"
    },
    {
     "expr": "ceil(min(vitam_metadata_reconstruction_graph_latency_seconds{collection=\"objectgroup\"}) / 60)",
     "legendFormat": "Object Groups Graph"
    }
   ]
  },
  {
   "title": "Logbook reconstruction",
   "type": "timeseries",
   "description": "Reconstruction latency of Logbook Operations",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "ceil(max(min by(tenant) (vitam_logbook_reconstruction_operation_latency_seconds{tenant=~\"$tenant\"})) / 60)",
     "legendFormat": "Logbook Operations"
    }
   ]
  },
  {
   "title": "Functional administration reconstruction",
   "type": "timeseries",
   "description": "Reconstruction latency of Functional Administration",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "ceil(max(min by(tenant) (vitam_functional_administration_reconstruction_latency_seconds{collection=\"accessionregisterdetail\", tenant=~\"$tenant\"})) / 60)",
     "legendFormat": "Accession Register Details"
    },
    {
     "expr": "ceil(max(min by(tenant) (vitam_functional_administration_reconstruction_latency_seconds{collection=\"accessionregistersymbolic\", tenant=~\"$tenant\"})) / 60)",
     "legendFormat": "Accession Register Symbolic"
    }
   ]
  }
 ]
}