# INA Tape Proxy Configuration

jettyConfig: jetty-config.xml

# =============================================================================
# STATUS CONFIGURATION (static values returned by status endpoints)
# =============================================================================

libraryName: INA_LIBRARY
nbDrives: 10
nbSlots: 200
defaultDriveDevice: /dev/ina-tape-proxy-nst0

# =============================================================================
# FILESYSTEM CONFIGURATION
# =============================================================================

exchangeDirectory: /vitam/data/ina-tape-proxy/exchange # Exchange directory for filesystem storage
inaStorageDirectory: /vitam/data/ina-tape-proxy/storage
# =============================================================================
# LATENCIES CONFIGURATION (milliseconds)
# =============================================================================

writeLatencyMs: 30000 # 30 seconds
readLatencyMs: 60000 # 60 seconds
loadLatencyMs: 5000 # 5 seconds
unloadLatencyMs: 4000 # 4 seconds
ejectLatencyMs: 2000 # 2 seconds
roboticLatencyMs: 500 # 500ms (move, rewind, goto...)