<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>fr.gouv.vitam</groupId>
        <artifactId>ihm-recette</artifactId>
        <version>9.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>ihm-recette-web-application</artifactId>
    <name>ihm-recette-web-application</name>

    <properties>
        <!-- Activate javascript sonar analysis -->
        <sonar.sources>src/main</sonar.sources>
        <sonar.exclusions>**/bower_components/**</sonar.exclusions>
        <unix.name>ihm-recette</unix.name>
        <unix.user>vitam</unix.user>
        <unix.group>vitam</unix.group>
        <jib.skip>true</jib.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-jaxrs2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.jclouds</groupId>
            <artifactId>jclouds-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.jclouds.api</groupId>
            <artifactId>filesystem</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.jclouds.api</groupId>
            <artifactId>openstack-swift</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.openstack4j.core</groupId>
            <artifactId>openstack4j-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.openstack4j.core.connectors</groupId>
            <artifactId>openstack4j-httpclient</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>com.opencsv</groupId>
            <artifactId>opencsv</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>apache-client</artifactId>
        </dependency>
        <dependency>
            <groupId>co.elastic.clients</groupId>
            <artifactId>elasticsearch-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver-sync</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>storage-engine-client</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>ihm-recette-front</artifactId>
            <version>${project.version}</version>
            <classifier>bundle</classifier>
            <type>zip</type>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>functional-test</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- use for cucumber assertion -->
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
        </dependency>
        <dependency>
            <groupId>net.javacrumbs.json-unit</groupId>
            <artifactId>json-unit</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>common-private</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>common-public</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>functional-administration-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>logbook-common-server</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>metadata-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>ihm-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>ihm-demo-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>ingest-external-client</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>logbook-operations-client</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>storage-engine-server</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- shiro dependencies -->
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-core</artifactId>
            <classifier>jakarta</classifier>
        </dependency>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-web</artifactId>
            <classifier>jakarta</classifier>
        </dependency>

        <!-- Jetty -->
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-http</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-xml</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava-testlib</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.googlecode.java-diff-utils</groupId>
            <artifactId>diffutils</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.wnameless.json</groupId>
            <artifactId>json-flattener</artifactId>
        </dependency>

        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-csv</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
        </dependency>
        <!-- ########################## Security ########################## -->

        <dependency>
            <groupId>com.mikesamuel</groupId>
            <artifactId>json-sanitizer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-css</artifactId>
        </dependency>
        <dependency>
            <groupId>org.owasp.antisamy</groupId>
            <artifactId>antisamy</artifactId>
        </dependency>
        <dependency>
            <groupId>org.owasp.esapi</groupId>
            <artifactId>esapi</artifactId>
        </dependency>
        <!-- ####################### Metrics ####################### -->
        <!-- Prometheus common -->
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_common</artifactId>
        </dependency>
        <!-- Prometheus the client -->
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient</artifactId>
        </dependency>
        <!-- Prometheus hotspot JVM metrics-->
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_hotspot</artifactId>
        </dependency>
        <!-- Prometheus get dropwizard metrics-->
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_dropwizard</artifactId>
        </dependency>

        <!-- ####################### Json validation ####################### -->
        <dependency>
            <groupId>com.github.java-json-tools</groupId>
            <artifactId>json-schema-validator</artifactId>
        </dependency>

        <!-- rx java -->
        <dependency>
            <groupId>io.reactivex.rxjava2</groupId>
            <artifactId>rxjava</artifactId>
        </dependency>

        <!-- ####################### Quartz Scheduler ####################### -->

        <dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz-jobs</artifactId>
        </dependency>

        <dependency>
            <groupId>io.fluidsonic.mirror</groupId>
            <artifactId>quartz-mongodb</artifactId>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-path</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.wiremock</groupId>
            <artifactId>wiremock-standalone</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.xmlunit</groupId>
            <artifactId>xmlunit-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.xmlunit</groupId>
            <artifactId>xmlunit-matchers</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>retrofit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>converter-jackson</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>common-junit</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.easymock</groupId>
            <artifactId>easymock</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jackson2-provider</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-afterburner</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
            <artifactId>jackson-jakarta-rs-json-provider</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
            <artifactId>jackson-jakarta-rs-base</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
        </dependency>
        <dependency>
            <groupId>xml-resolver</groupId>
            <artifactId>xml-resolver</artifactId>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk18on</artifactId>
        </dependency>

        <!-- ########################## Logger ########################## -->

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-access</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jul-to-slf4j</artifactId>
        </dependency>

        <!-- ####################### Extra Logger ####################### -->
        <dependency>
            <groupId>com.flipkart.zjsonpatch</groupId>
            <artifactId>zjsonpatch</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-to-slf4j</artifactId>
        </dependency>

        <dependency>
            <groupId>fr.gouv.vitam</groupId>
            <artifactId>cas-tape-library-simulator</artifactId>
        </dependency>

        <!-- jakarta dependencies -->
        <dependency>
            <groupId>jakarta.transaction</groupId>
            <artifactId>jakarta.transaction-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-csv</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-cbor</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-smile</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-client</artifactId>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
            <!-- Include static resources (from ihm-recette-front) -->
            <resource>
                <directory>target/front</directory>
            </resource>
            <!-- Include ontologie file from ansible deployment configuration to avoid duplication -->
            <resource>
                <directory>../../../deployment/environments/ontology</directory>
                <includes>
                    <include>VitamOntology.json</include>
                </includes>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.4.1</version>
                <configuration>
                    <from>
                        <image>gcr.io/distroless/java21</image>
                    </from>
                    <allowInsecureRegistries>true</allowInsecureRegistries>
                    <container>
                        <labels>
                            <git.commit.id>${git.commit.id}</git.commit.id>
                            <mvn.build.version>${project.version}</mvn.build.version>
                        </labels>
                    </container>
                    <to>
                        <image>${env.SERVICE_DOCKER_PUSH_URL}/vitam/ihm-recette</image>
                        <tags>
                            <tag>${git.commit.id.describe-short}</tag>
                            <tag>${project.version}</tag>
                        </tags>
                    </to>
                </configuration>
            </plugin>
            <plugin>
                <!-- Dependency manipulation (copy, unpack) and analysis. -->
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <!-- Extract static ressources into target/front/static folder -->
                    <execution>
                        <id>unpack-static-resources</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/front/static</outputDirectory>
                            <includeGroupIds>fr.gouv.vitam</includeGroupIds>
                            <includeArtifactIds>ihm-recette-front</includeArtifactIds>
                            <classifier>bundle</classifier>
                            <type>zip</type>
                            <failOnMissingClassifierArtifact>true</failOnMissingClassifierArtifact>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/dependencies</outputDirectory>
                            <includeTypes>jar</includeTypes>
                            <includeScope>compile</includeScope>
                            <overWriteReleases>false</overWriteReleases>
                            <overWriteSnapshots>false</overWriteSnapshots>
                            <overWriteIfNewer>true</overWriteIfNewer>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-config-resources</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/conf/sysconfig</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${basedir}/src/main/conf</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <!-- Debian -->
                    <execution>
                        <id>copy-debian-controlFiles</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/control</outputDirectory>
                            <overwrite>true</overwrite>
                            <resources>
                                <resource>
                                    <directory>${basedir}/src/deb/control</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>fr.gouv.vitam.ihmrecette.appserver.IhmRecetteMain</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>


            <plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>rpm-maven-plugin</artifactId>
				<configuration>
					<disabled>false</disabled>
					<license>CeCILL 2.1</license>
					<distribution>Vitam Project</distribution>
					<group>Application/Archiving</group>
					<packager>Vitam Package Team</packager>
					<defineStatements/>
					<targetOS>linux</targetOS>
					<requires>
						<require>systemd</require>
						<require>${jdk.version.rpm}</require>
						<require>vitam-user-${unix.user}</require>
					</requires>
					<defaultDirmode>750</defaultDirmode>
					<defaultFilemode>640</defaultFilemode>
					<defaultUsername>${unix.user}</defaultUsername>
					<defaultGroupname>${unix.group}</defaultGroupname>
					<mappings>
						<mapping>
							<!-- Caution : keep the artifact & dependency copy in the first mapping element ; or else they will be copied in every mapping before... -->
							<directory>/vitam/lib/${unix.name}</directory>
							<!-- Special marker to exclude non-default artefacts (we only need the jar to be packaged) -->
							<artifact>
								<classifiers>
									<classifier/>
								</classifiers>
							</artifact>
							<!-- Exclude ihm-recette-front zip artefact-->
							<dependency>
								<excludes>
									<exclude>fr.gouv.vitam:ihm-recette-front:zip</exclude>
								</excludes>
							</dependency>
						</mapping>
						<mapping>
							<directory>/vitam/conf/${unix.name}</directory>
							<sources>
								<source>
									<location>${project.build.directory}/conf</location>
								</source>
							</sources>
						</mapping>
                    </mappings>
				</configuration>
			</plugin>

            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>${jetty-maven-plugin.version}</version>
            </plugin>

            <plugin>
				<artifactId>jdeb</artifactId>
				<groupId>org.vafer</groupId>
				<configuration>
					<snapshotExpand>true</snapshotExpand>
					<skip>false</skip>
					<controlDir>${project.build.directory}/control</controlDir>
					<dataSet>

						<!-- Artifacts -->
						<data>
							<src>${project.build.directory}/${project.build.finalName}.jar</src>
							<type>file</type>
							<mapper>
								<type>perm</type>
								<user>${unix.user}</user>
								<group>${unix.group}</group>
								<filemode>0644</filemode>
								<prefix>/vitam/lib/${unix.name}/</prefix>
							</mapper>
						</data>

						<data>
							<src>${project.build.directory}/dependencies</src>
							<type>directory</type>
							<missingSrc>ignore</missingSrc>
							<mapper>
								<type>perm</type>
								<user>${unix.user}</user>
								<group>${unix.group}</group>
								<filemode>0644</filemode>
								<prefix>/vitam/lib/${unix.name}</prefix>
							</mapper>
						</data>
						<data>
							<src>${project.build.directory}/conf</src>
							<type>directory</type>
							<missingSrc>ignore</missingSrc>
							<mapper>
								<type>perm</type>
								<user>${unix.user}</user>
								<group>${unix.group}</group>
								<filemode>0750</filemode>
								<prefix>/vitam/conf/${unix.name}</prefix>
							</mapper>
						</data>
						<!-- Additional templates -->
						<data>
							<type>template</type>
							<paths>
								<path>/vitam/tmp/${unix.name}</path>
								<path>/vitam/log/${unix.name}</path>
							</paths>
							<mapper>
								<type>perm</type>
								<user>${unix.user}</user>
								<group>${unix.group}</group>
							</mapper>
						</data>

					</dataSet>
				</configuration>
			</plugin>

            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>3.0</version>
                <configuration>
                    <header>../../licenses/cecill21.txt</header>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>
