#!/usr/bin/env bash
parentdir="$(dirname "$1")"

cp "$parentdir/result.json" "$1/result.json"
mkdir "$1/output-files"
for i in `ls "$1/input-files"`; do cp -rp "$1/input-files/$i" "$1/output-files/GENERATE-$i.pdf"; done