# Configuration
@access-contract = ContratTNR
@tenant = 0
@operation-id = aeeaaaaaachemhquabfyqaln3wpwptqaaaaq
@dip-id = aeeaaaaaachemhquabfyqaln3wpwptqaaaaq

### Lancement du workflow de création de DIP sur une unité archivistique dont l'identifiant est 'aeaqaaaaaahnh5o2aal76aln3teqq3qaaaba'
POST {{url}}/access-external/v1/dipexport
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}
X-Access-Contract-Id: {{access-contract}}

{
  "$roots": [],
  "$query": [
    {
      "$eq": {
        "#id": "aeaqaaaaaahnh5o2aal76aln3teqq3qaaaba"
      }
    }
  ],
  "$projection": {}
}

### Vérification de l'opération de création de DIP en cours grâce au 'X-Request-Id' de la réponse
GET {{url}}/admin-external/v1/operations/{{operation-id}}
Accept: application/json
X-Tenant-Id: {{tenant}}
X-Access-Contract-Id: {{access-contract}}

### Récupération du journal des opération de la génération du DIP
GET {{url}}/access-external/v1/logbookoperations
Accept: application/json
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}

{
  "$query": {
    "$eq": {
      "#id": "{{operation-id}}"
    }
  },
  "$filter": {
    "$offset": 0,
    "$limit": 100
  },
  "$projection": {}
}

#### Téléchargement du DIP
GET {{url}}/access-external/v1/dipexport/{{operation-id}}/dip
Accept: application/octet-stream
X-Tenant-Id: {{tenant}}
X-Access-Contract-Id: {{access-contract}}

### Lancement du workflow de création de DIP complet avec paramètres et LogBook sur une unité archivistique avec descendance dont l'identifiant est 'aeaqaaaaaahnh5o2aal76aln3teqq3qaaaba'
POST {{url}}/access-external/v2/dipexport
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}
X-Access-Contract-Id: {{access-contract}}

{
 "dipExportType": "FULL",
    "dipRequestParameters": {
        "archivalAgencyIdentifier": "Vitam",
        "messageRequestIdentifier": "tot",
        "requesterIdentifier": "tot"
    },
   "dataObjectVersionToExport": {
        "dataObjectVersions": [
            "BinaryMaster",
            "Thumbnail",
            "TextContent"
        ]
    },  
  "exportWithLogBookLFC": true,
  "dslRequest": {
        "$query": [
            {
                "$or": [
                    {
                        "$eq": {
                            "#id": "aeaqaaaaayhnbfxgaavmgalonijd6raaaaca"
                        }
                    },
                    {
                        "$in": {
                            "#allunitups": [
                                "aeaqaaaaayhnbfxgaavmgalonijd6raaaaca"
                            ]
                        }
                    }
                ]
            }
        ],
        "$filter": {},
        "$projection": {}
    }
}