---

- name: "[{{ __profile.Identifier }}] Set back seda version to default version"
  set_fact:
    __seda_version: "{{ default_seda_version }}"
    __extraction_result:

- block:

  - name: "[{{ __profile.Identifier }}] Download archive profile file"
    uri:
      url: "{{ _archive_profiles_base_url }}/{{ __profile.Identifier | urlencode }}"
      method: GET
      headers:
        X-Tenant-Id: "{{ __profile._tenant }}"
      return_content: true
      client_cert: "{{ _tmp_pem }}"
      validate_certs: false
      status_code:
        - 200
        - 500
      timeout: 36000
    register: __response

  - name: "[{{ __profile.Identifier }}] Extract seda version from RNG file"
    set_fact:
      __extraction_result: "{{ __response.content | regex_search(_seda_version_pattern, '\\1') }}"
    when: __response.status == 200

  - name: "[{{ __profile.Identifier }}] Set final seda version if found in RNG"
    set_fact:
      __seda_version: "{{ __extraction_result | first }}"
    when:
      - __extraction_result is defined
      - __extraction_result != None
      - __extraction_result | length > 0

  when: __profile.Format == 'RNG'

- name: "[{{ __profile.Identifier }}] Update archive profile"
  uri:
    url: "{{ _archive_profiles_base_url }}/{{ __profile.Identifier | urlencode }}"
    method: PUT
    body:
      $action:
        - $set:
            SedaVersion: "{{ __seda_version if __profile.Format == 'RNG' else '2.3' }}"
    body_format: json
    headers:
      Content-Type: "application/json"
      X-Tenant-Id: "{{ __profile._tenant }}"
    client_cert: "{{ _tmp_pem }}"
    validate_certs: false
    return_content: true
    status_code:
      - 200
      - 400
    timeout: 36000
  register: __update_response

- name: Check authorized client errors
  assert:
    that:
      - "'Schema definition file not contains seda version' in __update_response.content"
    fail_msg: "Unexpected client error"
    success_msg: "The file {{ __profile.Identifier }} must contain a SEDA versioned namespace"
  when:
    - __update_response is defined
    - __update_response.status == 400
