---

- block:

  - name: Install python3-libselinux
    package:
      name: python3-libselinux
      state: present
    register: result
    retries: "{{ packages_install_retries_number }}"
    until: result is succeeded
    delay: "{{ packages_install_retries_delay }}"

  - name: Enable SELinux
    selinux:
      policy: "{{ selinux_policy }}"
      state: "{{ selinux_state }}"
    register: result

  - name: Relabel the filesystem if needed
    file:
      path: /.autorelabel
      state: touch
    when:
      - selinux_relabel |bool
      - result.reboot_required

  - name: Reboot the server if needed
    reboot:
    when:
      - result.reboot_required
      - selinux_reboot

  - name: Install vitam-selinux package
    package:
      name: vitam-selinux
      state: latest
    register: result
    retries: "{{ packages_install_retries_number }}"
    until: result is succeeded
    delay: "{{ packages_install_retries_delay }}"

  # For each vitam component, set the ports mapped to it's setype

  - name: Set access_external ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.access_external.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.access_external.port_service }}"
        - "{{ vitam.access_external.port_admin }}"

  - name: Set access_internal ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.access_internal.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.access_internal.port_service }}"
        - "{{ vitam.access_internal.port_admin }}"

  - name: Set functional_administration ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.functional_administration.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.functional_administration.port_service }}"
        - "{{ vitam.functional_administration.port_admin }}"

  - name: Set elastic_kibana_interceptor ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.elastic_kibana_interceptor.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.elastic_kibana_interceptor.port_service }}"
        - "{{ vitam.elastic_kibana_interceptor.port_admin }}"

  - name: Set batch_report ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.batch_report.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.batch_report.port_service }}"
        - "{{ vitam.batch_report.port_admin }}"

  - name: Set ingest_external ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.ingest_external.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.ingest_external.port_service }}"
        - "{{ vitam.ingest_external.port_admin }}"

  - name: Set ingest_internal ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.ingest_internal.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.ingest_internal.port_service }}"
        - "{{ vitam.ingest_internal.port_admin }}"

  - name: Set ihm_demo ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.ihm_demo.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.ihm_demo.port_service }}"
        - "{{ vitam.ihm_demo.port_admin }}"

  - name: Set logbook ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.logbook.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.logbook.port_service }}"
        - "{{ vitam.logbook.port_admin }}"

  - name: Set metadata ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.metadata.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.metadata.port_service }}"
        - "{{ vitam.metadata.port_admin }}"

  - name: Set processing ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.processing.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.processing.port_service }}"
        - "{{ vitam.processing.port_admin }}"

  - name: Set security_internal ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.security_internal.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.security_internal.port_service }}"
        - "{{ vitam.security_internal.port_admin }}"

  - name: Set storage ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.storage.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.storage.port_service }}"
        - "{{ vitam.storage.port_admin }}"

  - name: Set offer ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.offer.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.offer.port_service }}"
        - "{{ vitam.offer.port_admin }}"

  - name: Set worker ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.worker.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.worker.port_service }}"
        - "{{ vitam.worker.port_admin }}"

  - name: Set workspace ports
    seport:
      proto: tcp
      setype: "vitam_{{ vitam.workspace.vitam_component | regex_replace('-','_') }}_port_t"
      ports:
        - "{{ vitam.workspace.port_service }}"
        - "{{ vitam.workspace.port_admin }}"

  when:
    - selinux_state | lower in ["enforcing", "permissive"]
    - selinux_policy | lower == "targeted" # We don"t handle mls mode for now
