path: /vitam/data/ingest-external
jettyConfig: jetty-config.xml
authentication: false
tenantFilter : true
ignoreAntivirusCheck : false
baseUploadPath : /vitam/upload/ingest-external
fileActionAfterUpload : NONE
successfulUploadDir : /vitam/upload/ingest-external/success
failedUploadDir : /vitam/upload/ingest-external/failure
