#!/bin/sh
case "$1" in
  remove|upgrade|deconfigure)
    # systemd: On uninstall (not upgrade), disable and stop the unit
    if [ -x /bin/systemctl ]; then
      systemctl --no-reload disable vitam-${unix.name}.service >/dev/null 2>&1 || true
      systemctl stop vitam-${unix.name}.service >/dev/null 2>&1 || true
    fi
    ;;

  failed-upgrade)
    ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac