#!/bin/sh
getent group  vitam >/dev/null || groupadd  vitam
getent passwd vitamdb >/dev/null || useradd -g vitam -s /bin/bash -c "Vitam database user" vitamdb
getent group  vitamdb-admin >/dev/null || groupadd  vitamdb-admin
