#!/usr/bin/env bash

echo '{"requestId":"REQUEST_ID","id":"batch-reference","outputs":{"TEST_ID":[{"input":{"Name":"TEST_ID","FormatId":"fmt/41"},"status":"OK","analyseResult":"NOT_VALID","action":"ANALYSE"}]}}' > "$1/result.json"