#!/usr/bin/env bash

echo '{"RequestId":"REQUEST_ID","Id":"batch-reference","Outputs":{"TEST_ID":[{"Input":{"Name":"TEST_ID","FormatId":"fmt/41"},"Status":"OK","AnalyseResult":"NOT_VALID","Action":"ANALYSE"}]}}' > "$1/result.json"