#%RAML 0.8
title: Configuration Service
version: v1
baseUri: http://vitam
schemas: !include resourceTypes/ResourceTypes.raml
traits:  !include traits/StandardTraits.raml
resourceTypes: !include resourceTypes/DataDefinition.raml

/components:
  description: Administration des Composants
  get:
    description: Sélection de composants
  post:
    description: Permet d'ajouter un composant

  /{id_comp}:
    description: Permet la gestion d'un composant
    get:
      description: Donne accès à un composant
    patch:
      description: Permet si nécessaire de modifier un composant
    delete:
      description: Permet de retirer un composant

    /services:
      description: Permet de récupérer les services associés à ce composant
      get:
        description: Récupère les services associés à ce composant.

/services:
  description: Administration des Services
  get:
    description: Sélection des services
  post:
    description: Permet d'ajouter un Service

  /{id_service}:
    description: Permet la gestion d'un composant
    get:
      description: Donne accès à un service
    patch:
      description: Permet de modifier un Service
    delete:
      description: Permet de retirer un Service

    /components:
      description: Permet de récupérer les composants associés à ce service
      get:
        description: Récupère les composants associés à ce service.

    /templates:
      description: Permet de récupérer les templates associés à ce service
      get:
        description: Récupère les templates associés à ce service.

/templates:
  description: Administration des Templates
  get:
    description: Permet la sélection de templates
  post:
    description: Permet d'ajouter un Template

  /{id_template}:
    description: Permet la gestion d'un template
    get:
      description: permet l'accès à un template
    patch:
      description: Permet si nécessaire de modifier un Template
    delete:
      description: Permet de retirer un Template

    /services:
      description: Permet de récupérer les services associés à ce Template
      get:
        description: Récupère les services associés à ce Template.

    /servers:
      description: Permet de récupérer les serveurs associés à ce Template
      get:
        description: Récupère les serveurs associés à ce Template.

/servers:
  description: Administration des Serveurs
  get:
    description: Permet la sélection de serveurs
  post:
    description: Permet d'ajouter un Serveurs

  /{id_server}:
    description: Permet la gestion d'un serveur
    get:
      description: Permet l'accès à un serveur
    patch:
      description: Permet si nécessaire de modifier un Serveur
    delete:
      description: Permet de retirer un Serveur

    /templates:
      description: Permet de récupérer les Templates associés à ce Serveur
      get:
        description: Récupère les Templates associés à ce Serveur.

/status:
  description: Statut du moteur d'exécution, comme sa charge actuelle.
  get:
    description: Permet de récupérer le statut du moteur
