---

- include_tasks: prometheus_elasticsearch_exporter_enabled.yml
  when: prometheus.elasticsearch_exporter.enabled | default(true) | bool

- include_tasks: prometheus_elasticsearch_exporter_disabled.yml
  when: not prometheus.elasticsearch_exporter.enabled | default(true) | bool
