# -*- coding: utf-8 -*-
#
# VITAM - Plate-forme de développement documentation build configuration file, created by
# sphinx-quickstart on Fri Mar 25 00:25:11 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# General information about the project.
project = u'VITAM - Manuel de développement'
copyright = u'2016, VITAM'
author = u'VITAM'
doc_id = 'vitam-manuel-developpement'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'0.0.1'
# The full version, including alpha/beta/rc tags.
release = u'0.0.1'

execfile("../conf-common.py")
