---

- include_tasks: prometheus_consul_exporter_enabled.yml
  when: prometheus.consul_exporter.enabled | default(true) | bool

- include_tasks: prometheus_consul_exporter_disabled.yml
  when: not prometheus.consul_exporter.enabled | default(true) | bool
