# root endpoint request
displayName: ObjectGroups
description: API qui définie l'accès à tous les Groupes d'Objets.
type: { complexCollection: { queryModel: query, exampleQueryModel: !include ../samples/query.sample, answearModel: answearList, exampleAnswearModel: !include ../samples/answearList.sample, updateModel: update, exampleUpdateModel: !include ../samples/update.sample, createModel: create, exampleCreateModel: !include ../samples/create.sample } }

/{id_object_group}: !include ObjectGroup.raml

/check:
  displayName: Object Groups Check
  description: API qui permet de vérifier tous les Groupes d'Objets.
  type: collection
