# root endpoint request
displayName: Object
description: API qui définie l'accès à un unique Objet.
type: object-item

/check:
  displayName: Object Check
  description: API qui permet de vérifier un Objet particulier.
  type: object-item-check
