---

- include_tasks: prometheus_blackbox_exporter_enabled.yml
  when: prometheus.blackbox_exporter.enabled | default(true) | bool

- include_tasks: prometheus_blackbox_exporter_disabled.yml
  when: not prometheus.blackbox_exporter.enabled | default(true) | bool
