# Configuration
@access-contract = ContratTNR
@tenant = 0

### Lancement de l'audit de cohérence sur la unit dont l'ID est aeeaaaaaachemhquabfyqaln3wpwptqaaaaq
POST {{url-access}}/admin-external/v1/evidenceaudit
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}
X-Access-Contract-Id: {{access-contract}}

{
  "$roots": [],
  "$query": [
    {
      "$eq": {
        "#id": "aeeaaaaaachemhquabfyqaln3wpwptqaaaaq"
      }
    }
  ],
  "$projection": {},
  "$threshold": 1000
}

### Lancement de l'audit de sécurisation sur les journaux crées entre deux dates
POST {{url-access}}/admin-external/v1/traceability/linkedchecks
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}
X-Access-Contract-Id: {{access-contract}}

{
    "$query": {
        "$and": [
            {
                "$lt": {
                    "evDateTime": "2020-08-01T06:00:00.000"
                }
            },
            {
                "$gt": {
                    "evDateTime": "2019-08-06T18:00:00.000"
                }
            }
        ]
    },
    "$filter": {},
    "$projection": {}
}


### Lancement de l'audit sur les collections d'administration fonctionnelle et techniques
POST {{url-access}}/admin-external/v1/audits/referential
Accept: application/json
Content-Type: application/json
X-Tenant-Id: {{tenant}}

{
  "collectionName": "Profile"
}

### Lancer L'audit de cohérance de données Mongo & ES
GET  {{url-access}}/access-external/v1/auditDataConsistency
Accept: application/json
Content-Type: application/json
X-Access-Contract-Id: {{access-contract}}
X-Tenant-Id: {{tenant}}

{
}